// Full production runtime plus an explicit native-CSS-transition model derived from
// 2cff754's1440 keyboard cycle. This is causal state evidence, not pixel acceptance.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),code=fs.readFileSync(input,'utf8'),fixture=fs.readFileSync(path.join(__dirname,'transitions-library-card-input-policy.test.cjs'),'utf8'),scope={require,__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(fixture.slice(0,fixture.indexOf('const alive='))+'\nthis.makeFixture=make;',scope);
function make(source=code){
 const f=scope.makeFixture(source);let now=0,lastTarget=1,current=1,backgroundJob=null;const jobs=[],other={effect:{target:f.surface},transitionProperty:'color',cancelled:0,cancel(){this.cancelled++}};jobs.push(other);
 const originalComputed=f.env.context.getComputedStyle,baseGetAnimations=f.surface.getAnimations;
 const original={background:'',boxShadow:'',borderColor:'',overflow:'hidden',isolation:'',transitionProperty:'all, color',transitionDuration:'100ms, 240ms',transitionDelay:'0ms, 25ms'};Object.assign(f.surface.style,original);
 const list=(v,d)=>String(v||d).split(',').map(x=>x.trim()),ms=s=>parseFloat(s)*(String(s).endsWith('ms')?1:1000);
 const duration=()=>{const props=list(f.surface.style.transitionProperty,'all'),times=list(f.surface.style.transitionDuration,'100ms');let result=0;props.forEach((p,i)=>{if(p==='all'||p==='background-color')result=ms(times[i%times.length]);});return result;};
 const alpha=()=>backgroundJob&&!backgroundJob.cancelled?backgroundJob.from+(backgroundJob.to-backgroundJob.from)*Math.min(1,(now-backgroundJob.start)/backgroundJob.ms):current;
 const newJob=(from,to,clock)=>{const job={effect:{target:f.surface},transitionProperty:'background-color',from,to,start:now,ms:clock,cancelled:0,cancel(){this.cancelled++;current=lastTarget;}};jobs.push(job);backgroundJob=job;};
 const color=a=>`rgba(255, 255, 255, ${Math.round(a*1000000)/1000000})`;
 f.surface.getAnimations=()=>[...baseGetAnimations.call(f.surface),...jobs.filter(j=>!j.cancelled)];
 f.env.context.getComputedStyle=e=>{
  const cs=originalComputed(e);if(e!==f.surface)return cs;
  const target=f.surface.style.background==='transparent'?0:1;
  if(target!==lastTarget){const from=alpha(),clock=duration();lastTarget=target;if(clock){newJob(from,target,clock);}else{if(backgroundJob&&!backgroundJob.cancelled)backgroundJob.cancelled++;backgroundJob=null;current=target;}}
  const rendered=alpha();return {...cs,background:color(rendered),backgroundColor:color(rendered),boxShadow:'none',border:'0px none rgba(0, 0, 0, 0)',borderRadius:'18px',borderTopLeftRadius:'18px'};
 };
 const paint=()=>f.surface.children.findLast(e=>e.className==='st-expand-paint'&&e.isConnected);
 return {f,original,jobs,other,setTime:x=>now=x,read:()=>f.env.context.getComputedStyle(f.surface),paint,seedRestoring(){lastTarget=1;current=.83;newJob(.83,1,100);},alpha:e=>Number(/,\s*([\d.]+)\)/.exec(e.style.background)?.[1]??0)};
}
function cycle(source=code){const m=make(source),f=m.f;f.S.expand(f.source,f.detail,{keyboard:true});m.read();m.setTime(17);const first=m.alpha(m.paint());f.S.collapse(f.detail,{keyboard:true});m.read();f.S.expand(f.source,f.detail,{keyboard:true});const initial=m.alpha(m.paint());m.read();m.setTime(34);const firstRAF=m.alpha(m.paint());return {m,f,first,initial,firstRAF};}
const observed=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/transitions/native-card-background-transfer-observed.json'),'utf8'));assert.equal(observed.freshInitial.paint.opacity,1);assert.equal(observed.freshInitial.paint.backgroundAlpha,.83);assert.equal(observed.freshFirstRAF.paint.backgroundAlpha,.83);assert(observed.freshInitial.surface.animations.some(a=>a.type==='CSSTransition'&&a.transitionProperty==='background-color'));
const good=cycle();assert.equal(good.first,1);assert.equal(good.initial,1);assert.equal(good.firstRAF,1);assert.equal(good.m.other.cancelled,0,'Unrelated surface color clock survives all transfers');assert.equal(good.m.jobs.filter(j=>j.transitionProperty==='background-color').length,0,'No new surface background fade starts at transfer');
const begin=code.indexOf(' function transferExpandPaint('),end=code.indexOf(' function expandPaint(',begin);assert(begin>0&&end>begin);const bypass=code.slice(0,begin)+' function transferExpandPaint(surface, update) { return update(); }\n'+code.slice(end),bad=cycle(bypass);assert.equal(bad.first,1);assert.equal(bad.initial,.83,'Removed transfer guard reproduces the observed permanent83% paint');assert.equal(bad.firstRAF,.83);
const noFlush=code.replace('   getComputedStyle(surface).backgroundColor;','');assert.notEqual(noFlush,code);const uncommitted=cycle(noFlush);assert(uncommitted.m.jobs.some(j=>j.transitionProperty==='background-color'),'Without endpoint commit, restored durations create a new background transition');
for(const priority of ['', 'important']){
 const m=make(),f=m.f,properties={'background':'rgb(255, 255, 255)','box-shadow':'0 1px 4px black','border-color':'rgb(3, 4, 5)','overflow':'hidden','isolation':'auto','transition-property':'all, color','transition-duration':'100ms, 240ms','transition-delay':'0ms, 25ms'};for(const [key,value]of Object.entries(properties))f.surface.style.setProperty(key,value,priority);
 f.S.expand(f.source,f.detail,{keyboard:true});assert.equal(m.alpha(m.paint()),1);for(const key of ['transition-property','transition-duration','transition-delay']){assert.equal(f.surface.style.getPropertyValue(key),properties[key]);assert.equal(f.surface.style.getPropertyPriority(key),priority);}f.S.collapse(f.detail,{keyboard:true});for(const [key,value]of Object.entries(properties)){assert.equal(f.surface.style.getPropertyValue(key),value);assert.equal(f.surface.style.getPropertyPriority(key),priority);}assert.equal(m.other.cancelled,0);
}
const restoring=make();restoring.seedRestoring();restoring.f.S.expand(restoring.f.source,restoring.f.detail,{keyboard:true});assert.equal(restoring.alpha(restoring.paint()),1);assert.equal(restoring.jobs.find(j=>j.transitionProperty==='background-color').cancelled,1,'Pre-existing owned background transition is retired before sampling');assert.equal(restoring.other.cancelled,0);
const noCancel=code.replace("   for (const animation of surface.getAnimations?.() || []) if (animation.effect?.target === surface && !animation.effect.pseudoElement && expandPaintProperties.includes(animation.transitionProperty)) animation.cancel();",'');assert.notEqual(noCancel,code);const retained=make(noCancel);retained.seedRestoring();retained.f.S.expand(retained.f.source,retained.f.detail,{keyboard:true});assert.equal(retained.alpha(retained.paint()),.83,'Without retirement, an existing restoration transition contaminates the cloned paint');
const mixed=make(),mf=mixed.f;mf.surface.style.setProperty('background-color','rgb(255, 255, 255)','important');mf.surface.style.setProperty('background-image','linear-gradient(white,white)','');mf.surface.style.setProperty('border-top-color','rgb(3, 4, 5)','important');mf.S.expand(mf.source,mf.detail,{keyboard:true});mf.S.collapse(mf.detail,{keyboard:true});assert.equal(mf.surface.style.getPropertyValue('background-color'),'rgb(255, 255, 255)');assert.equal(mf.surface.style.getPropertyPriority('background-color'),'important');assert.equal(mf.surface.style.getPropertyValue('background-image'),'linear-gradient(white,white)');assert.equal(mf.surface.style.getPropertyPriority('background-image'),'');assert.equal(mf.surface.style.getPropertyValue('border-top-color'),'rgb(3, 4, 5)');assert.equal(mf.surface.style.getPropertyPriority('border-top-color'),'important');
const pseudo=make(),pseudoJob={effect:{target:pseudo.f.surface,pseudoElement:'::before'},transitionProperty:'background-color',cancelled:0,cancel(){this.cancelled++}};pseudo.jobs.push(pseudoJob);pseudo.f.S.expand(pseudo.f.source,pseudo.f.detail,{keyboard:true});assert.equal(pseudoJob.cancelled,0,'Pseudo-element paint ownership remains independent');
// CSSOM overflow shorthand writes reset both longhands, including their priorities.
function overflowCycle(source){const m=make(source),f=m.f,values={...f.surface.style},priorities={},camel=k=>k.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());Object.defineProperties(values,{getPropertyValue:{value:k=>values[camel(k)]||''},getPropertyPriority:{value:k=>priorities[k]||''},setProperty:{value:(key,value,priority='')=>{values[camel(key)]=value;priorities[key]=priority;if(key==='overflow'){const [x='',y=x]=value.trim().split(/\s+/);values.overflowX=x;values.overflowY=y;priorities['overflow-x']=priorities['overflow-y']=value?priority:'';}else if(key==='overflow-x'||key==='overflow-y'){values.overflow=priorities['overflow-x']===priorities['overflow-y']?`${values.overflowX||''} ${values.overflowY||''}`.trim():'';priorities.overflow=values.overflow?priorities['overflow-x']:'';}}}});f.surface.style=values;values.setProperty('overflow-x','visible','important');values.setProperty('overflow-y','clip','');f.S.expand(f.source,f.detail,{keyboard:true});f.S.collapse(f.detail,{keyboard:true});return {x:values.getPropertyValue('overflow-x'),xp:values.getPropertyPriority('overflow-x'),y:values.getPropertyValue('overflow-y'),yp:values.getPropertyPriority('overflow-y')};}
assert.deepEqual(overflowCycle(code),{x:'visible',xp:'important',y:'clip',yp:''});const noAxes=code.replace("'overflow','overflow-x','overflow-y','isolation']","'overflow','isolation']");assert.notEqual(noAxes,code);assert.notDeepEqual(overflowCycle(noAxes),{x:'visible',xp:'important',y:'clip',yp:''},'Omitting longhand snapshots loses mixed authored overflow after a shorthand transfer');
console.log('11/11 Card backing-transfer contracts pass; observed83% alpha, omitted commit/retirement negatives, priority restoration and unrelated color ownership covered');
