// Actual collectors/instant guards plus exact failed native snapshots. Relationship
// reconstruction below is explicitly modeled; it does not amend the old native evidence.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const browserPath=path.join(__dirname,'transitions-library-dialog.browser.mjs'),videoPath=path.join(__dirname,'transitions-library-dialog-video.browser.mjs'),browser=fs.readFileSync(browserPath,'utf8'),video=fs.readFileSync(videoPath,'utf8');
const raw=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/transitions/dialog-ccfaff-reduced-feedback.json'),'utf8'));
const section=(code,start,end)=>{const a=code.indexOf(start),b=code.indexOf(end,a);assert(a>=0&&b>a);return code.slice(a,b);};
const common=code=>section(code,'function dialogAnimationEvidence(',code===browser?'function inspect(':'function assertAcceptedCoverage(').trim();
assert.equal(common(browser),common(video),'Both collectors must use identical identity/property semantics and instant guard');
const context={assert};vm.createContext(context);vm.runInContext(section(browser,'const parse=v=>','const settle=')+section(browser,'function backdropState(style){','async function earlyOpen(')+'\nthis.helpers={dialogAnimationEvidence,assertInstantAnimations,assertPaint};',context);
const {dialogAnimationEvidence,assertInstantAnimations,assertPaint}=context.helpers;
const acceptedLoop=section(video,'   for(const entry of run.observations.accepted)','\n   for(const {state:s}');
const videoCheck=s=>{const c={assert,run:{observations:{accepted:[{kind:'open',trusted:true,detail:1,state:{...s,opacity:s.dialog.opacity,transform:s.dialog.transform,backdropOpacity:s.backdrop.opacity}}]}}};vm.runInNewContext(common(video)+acceptedLoop,c);};
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split('\n')[0]});}}
const surface={id:'dialog-1',className:'project-dialog',tagName:'DIALOG'},child={id:'',className:'st-button',tagName:'BUTTON'},outside={...child};surface.contains=target=>target===surface||target===child;
const record=(target=child,properties=['backgroundColor'],pseudo=null)=>dialogAnimationEvidence({effect:{target,pseudoElement:pseudo,getKeyframes:()=>[{offset:0,computedOffset:0,easing:'linear',composite:'replace',...Object.fromEntries(properties.map(p=>[p,'before']))},{offset:1,...Object.fromEntries(properties.map(p=>[p,'after']))}]}},surface);
const enrich=first=>({...first,animations:first.animations.map(a=>({...a,...record(child,a.properties,a.pseudo)}))});
for(const row of raw.records){
 test(row.file+': preserve the actual failure and all raw property inventories',()=>{assert.equal(row.status,'failed');assert(row.error.includes('2 !== 0'));assert.equal(row.first.animations.length,2);assert.deepEqual(row.first.animations.map(a=>a.properties),[['backgroundColor'],['boxShadow']]);assert(row.first.animations.every(a=>a.target==='st-button'&&a.pseudo===null&&a.duration===100));assert.throws(()=>assertPaint(row.first,{motion:'reduce',input:'pointer'}),'Old raw data without target relationship must not silently pass');});
 test(row.file+': actual full paint and video guards accept explicitly measured descendant feedback',()=>{const before=JSON.stringify(row.first),s=enrich(row.first);assertPaint(s,{motion:'reduce',input:'pointer'});videoCheck(s);assert.equal(JSON.stringify(row.first),before,'Raw evidence stays unchanged');assert.equal(s.animations.length,2,'Do not filter feedback out of raw inventory');for(let i=0;i<2;i++){assert.equal(s.animations[i].targetRelationship,'descendant');assert.deepEqual(Array.from(s.animations[i].properties),row.first.animations[i].properties);assert.equal(s.animations[i].duration,100);}});
}
test('empty inventory remains a valid instant state',()=>assertInstantAnimations([]));
test('explicit descendant feedback properties can share one job',()=>assertInstantAnimations([record(child,['backgroundColor','boxShadow'])]));
test('target relationship uses actual identity/containment rather than class or id text',()=>{assert.equal(record(surface).targetRelationship,'surface');assert.equal(record(child).targetRelationship,'descendant');assert.equal(record(outside).targetRelationship,'outside');assert.equal(record(null).targetRelationship,'unknown');const duplicate={...surface};assert.equal(record(duplicate).targetRelationship,'outside');});
for(const [name,job] of [
 ['surface background',record(surface,['backgroundColor'])],['surface geometry',record(surface,['transform'])],['backdrop opacity',record(surface,['opacity'],'::backdrop')],['backdrop paint',record(surface,['backgroundColor'],'::backdrop')],['descendant pseudo paint',record(child,['backgroundColor'],'::before')],['outside button paint',record(outside)],['unknown target',record(null)],['empty properties',record(child,[])],['unrecorded relationship',{target:'st-button',pseudo:null,properties:['backgroundColor']}],['unrecorded pseudo',{targetRelationship:'descendant',properties:['backgroundColor']}],
 ...['opacity','filter','backdropFilter','transform','translate','scale','rotate','width','height','clipPath','visibility','backgroundImage','color','unknownProperty'].map(p=>['descendant '+p,record(child,[p])]),
 ['mixed feedback and geometry',record(child,['backgroundColor','transform'])],['mixed feedback and unknown',record(child,['boxShadow','unknownProperty'])]
])test('both actual instant guards reject '+name,()=>{assert.throws(()=>assertInstantAnimations([job]));const s=enrich(raw.records[0].first);s.animations=[job];assert.throws(()=>assertPaint(s,{motion:'reduce',input:'pointer'}));assert.throws(()=>videoCheck(s));});
test('allowed transient feedback does not weaken settled cleanup',()=>{const s=enrich(raw.records[0].first);assert.throws(()=>assertPaint(s,{motion:'reduce',input:'pointer',settled:true}));});
test('feedback permission preserves paint, contrast, focus and geometry assertions',()=>{for(const mutate of [s=>s.dialog.opacity=.5,s=>s.backdrop.opacity=0,s=>s.heading.color='rgb(255, 255, 255)',s=>s.cancel.rect.width=0,s=>s.inert=true]){const s=JSON.parse(JSON.stringify(enrich(raw.records[0].first)));mutate(s);assert.throws(()=>assertPaint(s,{motion:'reduce',input:'pointer'}));}});
const report={sourceCommit:raw.sourceCommit,source:{browser:crypto.createHash('sha256').update(browser).digest('hex'),video:crypto.createHash('sha256').update(video).digest('hex')},scope:'Actual extracted collectors/guards and unmodified failed native first snapshots with separately modeled target containment. No fresh native render or raster acceptance.',passed:results.filter(r=>r.pass).length,total:results.length,results};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
