// Exact production runtime with deterministic DOM/WAAPI and read-only exposure of
// existing closure helpers. These are lifecycle/causal checks, not rendered acceptance.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),source=fs.readFileSync(input,'utf8');
const logic=fs.readFileSync(path.join(__dirname,'transitions-library-logic.test.cjs'),'utf8'),prefix=logic.slice(0,logic.indexOf('const results=[];'));
function fixture(code=source){
 const marker=' window.SeenryTransitions = {';assert(code.includes(marker));code=code.replace(marker,' window.__blurQA={stop,stopAll};\n'+marker);
 const shim={...fs,readFileSync:(p,...a)=>path.resolve(p)===input?code:fs.readFileSync(p,...a)};
 const scope={require:n=>n==='fs'?shim:require(n),__dirname,process:{argv:['node','test',input],on(){}},console};vm.runInNewContext(prefix+'\ncompleted=true;this.env={E,S,animations,context,helpers:context.window.__blurQA,setReduced:v=>reduce=v};',scope);
 const f=scope.env,animate=f.E.prototype.animate;f.E.prototype.animate=function(...args){const a=animate.apply(this,args);a.owner=this;a.effect={target:this,pseudoElement:args[1]?.pseudoElement||null,getKeyframes:()=>a.frames};const finish=a.finish;a.finish=()=>{a.done=true;finish()};return a;};
 f.context.getComputedStyle=(e,pseudo)=>{if(pseudo)return {filter:'brightness(.9)',opacity:'1'};const cs={filter:'none',opacity:'1',...e.style,...e.rendered};for(const a of f.animations)if(a.owner===e&&!a.effect?.pseudoElement&&!a.cancelled&&!a.done&&a.frames.some(k=>'filter'in k))cs.filter=a.renderedFilter||a.frames[0].filter;return cs;};
 f.E.prototype.getAnimations=function(){return f.animations.filter(a=>a.owner===this&&!a.cancelled&&!a.done)};
 f.element=()=>{const e=new f.E();e.style.opacity='1';e.style.filter='contrast(1.1)';e.closest=()=>({dataset:{stBlur:'8'}});return e;};
 f.for=e=>f.animations.filter(a=>a.owner===e);f.blur=e=>f.for(e).findLast(a=>a.frames.some(k=>'filter'in k));f.opacity=e=>f.for(e).findLast(a=>a.frames.some(k=>'opacity'in k));
 f.enter=(e,key='o',options={})=>f.S.play(e,[{opacity:0},{opacity:1}],{ms:120,delay:150,channel:key,fade:true,...options});return f;
}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
(async()=>{const results=[];const record=(name,result)=>results.push({name,pass:true,result});
 {const f=fixture(),e=f.element();f.enter(e);const b=f.blur(e),o=f.opacity(e);f.helpers.stop(e,'o');assert(b.cancelled>0&&o.cancelled>0);assert.equal(e.style.filter,'contrast(1.1)');record('Matching channel stop retires delayed filter and opacity without writing authored filter',{blurCancelled:b.cancelled,opacityCancelled:o.cancelled});}
 {const f=fixture(),e=f.element();f.enter(e,'alpha');const b=f.blur(e),o=f.opacity(e);f.helpers.stop(e,'geometry');assert.equal(b.cancelled,0);assert.equal(o.cancelled,0);f.helpers.stop(e,'alpha');assert(b.cancelled>0);record('Unrelated channel stop does not cancel another channel’s companion');}
 {const f=fixture(),e=f.element();f.enter(e,'alpha');const old=f.blur(e);f.enter(e,'beta');const current=f.blur(e);assert(old.cancelled>0);f.helpers.stop(e,'alpha');assert.equal(current.cancelled,0);f.helpers.stopAll(e);assert(current.cancelled>0);assert(f.for(e).every(a=>a.cancelled>0));record('Latest filter owner survives old-channel stop and stopAll retires every owned animation');}
 for(const option of [{blur:false},{fade:false,blur:false}]){const f=fixture(),e=f.element();f.enter(e);const old=f.blur(e);f.enter(e,'o',option);assert(old.cancelled>0);assert.equal(f.for(e).filter(a=>a.frames.some(k=>'filter'in k)).length,1);record('A matching replacement that does not request blur retires the old companion',option);}
 for(const key of ['o','geometry']){const f=fixture(),e=f.element();f.enter(e);const old=f.blur(e);f.setReduced(true);const n=f.animations.length;f.S.play(e,[{transform:'translateY(20px)'},{transform:'none'}],{channel:key});assert(old.cancelled>0);assert.equal(f.animations.length,n);record('Reduced replacement retires old blur even when new non-fade returns early',{key});}
 for(const incoming of [true,false]){const f=fixture(),e=f.element();f.enter(e);const old=f.blur(e);old.renderedFilter='contrast(1.1) blur(2px)';e.rendered={opacity:'.5'};f.S.play(e,[{opacity:incoming?0:1},{opacity:incoming?1:0}],{ms:120,channel:'o',fade:true});const next=f.blur(e);assert(old.cancelled>0);assert.equal(next.frames[0].filter,'contrast(1.1) blur(2px)');assert.equal(next.frames.at(-1).filter,`contrast(1.1) blur(${incoming?0:4.8}px)`);record('Reversal preserves the currently rendered complete filter',{incoming,frames:next.frames});}
 {const f=fixture(),e=f.element();f.enter(e);const b=f.blur(e);assert.equal(b.options.duration,300);assert.equal(b.options.delay,150);assert.equal(b.frames[0].filter,'contrast(1.1) blur(8px)');assert.equal(b.frames[1].filter,'contrast(1.1) blur(0px)');b.finish();await flush();assert(b.cancelled>0);assert.equal(e.style.filter,'contrast(1.1)');record('Fresh premium blur retains its300ms clock, delay and authored base filter');}
 {const f=fixture(),e=f.element();f.enter(e,'alpha');const old=f.blur(e);f.enter(e,'beta');const latest=f.blur(e);old.finish();await flush();assert.equal(latest.cancelled,0);f.helpers.stop(e,'beta');assert(latest.cancelled>0);record('Old completion cannot retire or orphan the newer companion owner');}
 {const f=fixture(),e=f.element();e.getBoundingClientRect=()=>({width:500,height:500});f.enter(e);assert.equal(f.blur(e),undefined);record('Large surfaces remain outside the existing160000px² blur limit');}
 {const f=fixture(),e=f.element();e.closest=()=>null;f.enter(e);assert.equal(f.blur(e),undefined);record('Unopted elements do not receive blur');}
 {const f=fixture(),e=f.element();f.enter(e);const old=f.blur(e);f.S.play(e,[{filter:'contrast(1.1)'},{filter:'contrast(1.2)'}],{channel:'filter'});assert(old.cancelled>0);record('An explicit filter animation supersedes the companion without inheriting it');}
 for(const single of [true,false]){const f=fixture(),e=f.element();f.enter(e);const old=f.blur(e);old.renderedFilter='contrast(1.1) blur(2px)';const frames=single?[{filter:'contrast(1.2)'}]:[{filter:'contrast(1)'},{filter:'contrast(1.2)'}];f.S.play(e,frames,{channel:'filter'});const next=f.for(e).at(-1);assert(old.cancelled>0);assert.equal(next.frames[0].filter,'contrast(1.1) blur(2px)');assert.equal(next.frames.at(-1).filter,'contrast(1.2)');record('Explicit filter replacement samples the rendered companion before retiring it',{single});}
 {const f=fixture(),e=f.element();f.enter(e);const old=f.blur(e);f.S.play(e,[{filter:'brightness(1)'}],{channel:'filter',pseudo:'::backdrop'});const pseudo=f.for(e).at(-1);assert.equal(old.cancelled,0);assert.equal(pseudo.frames[0].filter,'brightness(.9)');f.helpers.stop(e,'filter::backdrop');assert.equal(old.cancelled,0);record('Pseudo-element filter replacement and stop preserve the element’s independent companion');}
 {const f=fixture(),e=f.element();f.S.play(e,[{filter:'blur(3px)'},{filter:'blur(0px)'}],{ms:280,channel:'f',current:false});const explicit=f.blur(e);f.enter(e,'o',{ms:320,delay:0});assert.equal(f.for(e).filter(a=>a.frames.some(k=>'filter'in k)).length,1);assert.equal(explicit.cancelled,0);explicit.finish();await flush();assert.equal(f.context.getComputedStyle(e).filter,'contrast(1.1)');record('Thinking f→o choreography retains the deliberate filter and creates no residual second blur');}
 {const f=fixture(),e=f.element();const authored=e.animate([{filter:'brightness(.8)'},{filter:'brightness(1)'}],{duration:500});f.enter(e);assert.equal(f.for(e).filter(a=>a.frames.some(k=>'filter'in k)).length,1);f.helpers.stop(e,'o');assert.equal(authored.cancelled,0);record('An unrelated authored active filter keeps property ownership over opt-in auto blur');}
 {const f=fixture(),e=f.element();const job=f.S.play(e,[{filter:'contrast(1.2)'}],{channel:'f',fill:'forwards'});const explicit=f.blur(e);explicit.finish();await job;f.enter(e);assert.equal(f.for(e).filter(a=>a.frames.some(k=>'filter'in k)).length,1);assert.equal(e.style.filter,'contrast(1.2)');record('A held explicit filter remains owned until its channel is released');}
 {const f=fixture(),e=f.element();f.S.play(e,[{filter:'brightness(1)'}],{channel:'f',pseudo:'::backdrop'});f.enter(e);assert.equal(f.for(e).filter(a=>a.frames.some(k=>'filter'in k)).length,2);record('A pseudo-element filter does not block auto blur on the element itself');}
 for(const held of [false,true]){const f=fixture(),e=f.element();const job=f.S.play(e,[{filter:'contrast(1.2)'}],{channel:'f',fill:held?'forwards':undefined});const explicit=f.blur(e);if(held){explicit.finish();await job;}e.style.opacity='.5';f.enter(e,'f');const automatic=f.blur(e);assert.notEqual(automatic,explicit);assert(explicit.cancelled>0);assert.equal(automatic.frames[0].filter,'contrast(1.1) blur(8px)');record('Matching replacement releases explicit property ownership before automatic blur',{held});}
 for(const all of [false,true]){const f=fixture(),e=f.element();f.S.play(e,[{filter:'contrast(1.2)'}],{channel:'f'});const explicit=f.blur(e);all?f.helpers.stopAll(e):f.helpers.stop(e,'f');f.enter(e);assert.notEqual(f.blur(e),explicit);assert(explicit.cancelled>0);record('Stopped explicit filter no longer reserves the auto-blur property',{all});}
 {const f=fixture(),e=f.element();f.S.play(e,[{filter:'contrast(1.2)'}],{channel:'f'});const old=f.blur(e);e.style.opacity='.5';f.enter(e,'f');const automatic=f.blur(e);old.finish();await flush();assert.equal(automatic.cancelled,0);f.helpers.stop(e,'f');assert(automatic.cancelled>0);record('Late canceled explicit owner cannot suppress or orphan its automatic replacement');}
 {const f=fixture(),e=f.element();f.S.play(e,[{filter:'brightness(1)'}],{channel:'f',pseudo:'::backdrop'});f.enter(e);assert.equal(f.blur(e).frames[0].filter,'contrast(1.1) blur(8px)');record('Pseudo filter never becomes the element’s authored base filter');}
 {const conflict=source.replace('if (blurHost && !ownsFilter','if (blurHost');assert.notEqual(conflict,source);const f=fixture(conflict),e=f.element();f.S.play(e,[{filter:'blur(3px)'},{filter:'blur(0px)'}],{ms:280,channel:'f',current:false});f.enter(e);assert.equal(f.for(e).filter(a=>a.frames.some(k=>'filter'in k)).length,2);assert.equal(f.blur(e).frames.at(-1).filter,'blur(3px) blur(0px)');record('Removed explicit-filter precedence reproduces the thinking residual3px base');}
 const retire="  if (!o.pseudo) { if (reduced() || frames.some(f => 'filter' in f)) stopBlur(el); else stopBlur(el, key); }";assert(source.includes(retire));
 {const premature=source.replace(retire,'').replace('  let map = channels.get(el);',retire+'\n  let map = channels.get(el);');const f=fixture(premature),e=f.element();f.enter(e);f.blur(e).renderedFilter='contrast(1.1) blur(2px)';f.S.play(e,[{filter:'contrast(1.2)'}],{channel:'filter'});assert.equal(f.for(e).at(-1).frames[0].filter,'contrast(1.1)');record('Premature retirement causal control drops the currently rendered2px on explicit handoff');}
 {const unscoped=source.replace(retire,"  if (reduced() || frames.some(f => 'filter' in f)) stopBlur(el); else stopBlur(el, key);");const f=fixture(unscoped),e=f.element();f.enter(e);const old=f.blur(e);f.S.play(e,[{filter:'brightness(1)'}],{channel:'filter',pseudo:'::backdrop'});assert(old.cancelled>0);record('Removed pseudo scoping causal control cancels an unrelated element companion');}
 const start=source.indexOf(' function stopBlur('),end=source.indexOf('\n function play(',start);assert(start>=0&&end>start);const noRetirement=source.slice(0,start)+' function stopBlur(el, key) {}'+source.slice(end);
 {const f=fixture(noRetirement),e=f.element();f.enter(e);const b=f.blur(e);f.helpers.stopAll(e);assert.equal(b.cancelled,0);record('Removed retirement causal control reproduces a blur surviving stopAll');}
 {const reset=source.replace('const firstFilter = renderedBlur || blurFilter','const firstFilter = blurFilter');assert.notEqual(reset,source);const f=fixture(reset),e=f.element();f.enter(e);f.blur(e).renderedFilter='contrast(1.1) blur(2px)';e.rendered={opacity:'.5'};f.enter(e);assert.equal(f.blur(e).frames[0].filter,'contrast(1.1) blur(8px)');record('Removed rendered-filter causal control reproduces a2→8px restart');}
 const report={sourceSha256:require('crypto').createHash('sha256').update(source).digest('hex'),scope:'Full-runtime deterministic lifecycle/ownership evidence; fresh cloud screenshots remain required',passed:results.length,total:results.length,results};if(process.argv[3])fs.writeFileSync(process.argv[3],JSON.stringify(report,null,2)+'\n');console.log(`${results.length}/${results.length} blur ownership/continuity checks pass; causal controls reproduce baseline and review-found gaps`);
})().catch(e=>{console.error(e);process.exitCode=1});
