// Execute actual reduced-input phase selection and instant acceptance predicates.
// These are modeled predicate controls, not native keyboard/pixel coverage.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const file=path.join(__dirname,'transitions-library-reduced-expand-reopen.browser.mjs'),source=fs.readFileSync(file,'utf8');
const cut=(a,b)=>{const i=source.indexOf(a),j=source.indexOf(b,i);assert(i>=0&&j>i);return source.slice(i,j);};
(async()=>{const {cardReadableFindings}=await import('./transitions-library-card-readable.mjs'),scope={assert,findingsJson:row=>JSON.stringify(cardReadableFindings(row))};vm.createContext(scope);vm.runInContext('const cardReadableFindings=row=>JSON.parse(findingsJson(row));'+cut('function assertFrame(', 'const saveReport=')+cut('const phases=','saveReport();')+'\nthis.helpers={assertFrame,assertInstantClosed,phasesForInput};',scope);const {assertFrame,assertInstantClosed,phasesForInput}=scope.helpers;
const rect={left:0,top:0,right:300,bottom:300,width:300,height:300},p=()=>({shown:true,opacity:1,effectiveOpacity:1,backgroundAlpha:1,ownsCenter:true,filters:['none'],rect:{...rect}}),leaf=text=>({text,painted:true,visibility:'visible',display:'block',effectiveDisplay:true,opacity:1,colorAlpha:1,filter:'none',ancestorFilters:[{filter:'none'}],clipPath:'none',paintAncestors:[{clipPath:'none'}],glyphs:[{left:20,top:20,right:80,bottom:40,width:60,height:20}]}),frame=()=>({nativeReducedMotion:true,blurEnabled:true,open:'true',inert:false,focusedClose:true,focusVisible:true,surface:p(),paint:p(),close:p(),content:[p()],sourceVisibility:'hidden',shell:rect,keyboardText:{cue:leaf('3-track preview'),tracks:[1,2,3].map(i=>({name:leaf('Track '+i),duration:leaf('3:12')}))}}),closed=()=>({open:'false',closing:null,inert:true,instant:true,focusedSource:true,sourceVisibility:'visible',sourceGroupInert:false,ghosts:0,visualAnimations:[]}),event=()=>({trusted:true,key:'Escape',observedAt:'document-bubble'});
let passed=0;const test=fn=>{fn();passed++;};
test(()=>{const keyboard=phasesForInput(true),pointer=phasesForInput(false);assert.equal(keyboard.length,1);assert.equal(keyboard[0].name,'keyboard-immediate-cycle');assert(keyboard[0].required&&keyboard[0].instant);assert.equal(pointer.length,4);assert.equal(pointer.filter(p=>p.required).length,3);assert.equal(pointer.find(p=>!p.required).name,'natural-80');assert(pointer.find(p=>p.controlled));assert.equal(2*(keyboard.filter(p=>p.required).length+pointer.filter(p=>p.required).length),8,'Count real distinct required behavior, not obsolete keyboard exit windows');});
test(()=>{assertFrame(frame(),true);assertInstantClosed(closed(),event());});
for(const change of [f=>f.open='true',f=>f.closing='true',f=>f.instant=false,f=>f.focusedSource=false,f=>f.sourceVisibility='hidden',f=>f.sourceGroupInert=true,f=>f.ghosts=1,f=>f.visualAnimations=[{properties:['opacity']}],f=>f.inert=false])test(()=>{const f=closed();change(f);assert.throws(()=>assertInstantClosed(f,event()));});
for(const change of [e=>e.trusted=false,e=>e.key='Enter',e=>e.observedAt='target'])test(()=>{const e=event();change(e);assert.throws(()=>assertInstantClosed(closed(),e));});
for(const change of [f=>f.keyboardText.tracks[0].name.opacity=0,f=>f.keyboardText.tracks[0].name.colorAlpha=.5,f=>f.keyboardText.tracks[0].name.filter='blur(8px)',f=>f.keyboardText.tracks[0].name.paintAncestors=[{clipPath:'none',overflow:'hidden',clipRect:{left:0,top:0,right:300,bottom:1}}],f=>f.keyboardText.cue.text='Preview',f=>f.focusVisible=false,f=>f.surface.effectiveOpacity=.5,f=>f.close.ownsCenter=false,f=>f.close.filters=['blur(8px)']])test(()=>{const f=frame();change(f);assert.throws(()=>assertFrame(f,true),'Actual acceptance rejects missing full readable keyboard state');});
const alphaScope={};vm.createContext(alphaScope);vm.runInContext(cut('   const alpha=c=>','\n   const overflowBounds=')+'\nthis.alpha=alpha;',alphaScope);for(const [color,expected]of [['rgb(0,0,0)',1],['rgba(0,0,0,0)',0],['rgb(0 0 0 / 50%)',.5],['color(srgb 0 0 0 / 50%)',.5],['color(srgb 0 0 0 / 0)',0],['transparent',0],['invalid',0]])test(()=>assert.equal(alphaScope.alpha(color),expected));
assert(source.includes("window.__reducedInput={trusted:e.isTrusted,detail:e.detail,observedAt:'document-bubble'}"));assert(source.includes("document.addEventListener('click',observe)"));assert(source.includes("document.addEventListener('keydown',observe)"));assert(source.indexOf('if(keyboard){\n   assert.equal(run.opening.input.detail,0)')<source.indexOf('   SeenryTransitions.collapse(detail)'));
console.log(`${passed}/${passed} reduced keyboard contract cases pass; pointer lifecycle predicates remain separate`);
})().catch(e=>{console.error(e);process.exitCode=1});
