// Full runtime source-group ownership. Native tab order and CSS anchors are separate browser checks.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),code=fs.readFileSync(input,'utf8'),test=fs.readFileSync(path.join(__dirname,'transitions-library-card-input-policy.test.cjs'),'utf8'),scope={require,__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(test.slice(0,test.indexOf('const alive='))+'\nthis.make=make;',scope);
function make(source=code,original=false,unsafe=false){const f=scope.make(source),group=new f.env.E();group.inert=original;group.append(f.source,new f.env.E('button'),new f.env.E('button'));if(unsafe)group.append(f.detail);const closest=f.source.closest;f.source.closest=s=>s==='[data-st-expand-sources]'?group:closest(s);return {...f,group};}
let n=0;
for(const keyboard of [false,true])for(const original of [false,true]){const f=make(code,original);let atReturn=null;f.source.focus=()=>{atReturn=f.group.inert;f.env.setActive(f.source)};f.S.expand(f.source,f.detail,{keyboard});assert.equal(f.group.inert,true);assert.equal(f.detail.inert,false);f.S.collapse(f.detail,{keyboard:true});assert.equal(f.group.inert,original);assert.equal(atReturn,original,'Authored inert state restores before focus return');n++;}
const reverse=make();reverse.S.expand(reverse.source,reverse.detail,{keyboard:false});reverse.S.collapse(reverse.detail,{keyboard:false});assert.equal(reverse.detail.dataset.stClosing,'true');assert.equal(reverse.group.inert,true);reverse.S.expand(reverse.source,reverse.detail,{keyboard:false});assert.equal(reverse.group.inert,true);reverse.S.collapse(reverse.detail,{keyboard:true});assert.equal(reverse.group.inert,false,'Reversal must not snapshot owned inert=true as authored state');n++;
const unsafe=make(code,false,true);unsafe.S.expand(unsafe.source,unsafe.detail,{keyboard:true});assert.equal(unsafe.group.inert,false,'Never inert an ancestor containing the active detail');n++;
const native=make();native.detail.tagName='DIALOG';native.detail.open=false;native.detail.showModal=()=>{assert.equal(native.group.inert,false,'Native modal remembers the live trigger before local source ownership begins');native.detail.open=true;native.control.focus()};native.detail.close=()=>{assert.equal(native.group.inert,false,'Native focus return sees the restored group');native.detail.open=false};native.S.expand(native.source,native.detail,{keyboard:true});assert.equal(native.group.inert,true);native.S.collapse(native.detail,{keyboard:true});n++;
const noHold=code.replace('  holdExpandSources(source, detail, s);','');assert.notEqual(noHold,code);const uncovered=make(noHold);uncovered.S.expand(uncovered.source,uncovered.detail,{keyboard:true});assert.equal(uncovered.group.inert,false,'Removing the owner reproduces covered sources in the focus order');n++;
const noRelease=code.replace("   releaseExpandSources(s);\n   source.style.visibility", "   source.style.visibility");assert.notEqual(noRelease,code);const retained=make(noRelease);retained.S.expand(retained.source,retained.detail,{keyboard:true});retained.S.collapse(retained.detail,{keyboard:true});assert.equal(retained.group.inert,true,'Removing release leaves source choices disabled after close');n++;
// Two details share the same production API and marked group, not separate runtimes.
function shared(source=code,original=false){const a=make(source,original),b=scope.make(source);a.group.append(b.source);const closest=b.source.closest;b.source.closest=q=>q==='[data-st-expand-sources]'?a.group:closest(q);return {a,b,group:a.group};}
for(const original of [false,true])for(const reverseOrder of [false,true]){
 const {a,b,group}=shared(code,original);a.S.expand(a.source,a.detail,{keyboard:true});a.S.expand(b.source,b.detail,{keyboard:true});
 // Repeated acquisition by the same layer is idempotent, including interruption.
 a.S.expand(a.source,a.detail,{keyboard:true});const [first,last]=reverseOrder?[b,a]:[a,b];a.S.collapse(first.detail,{keyboard:true});
 assert.equal(group.inert,true,'An open co-owner keeps the covered group inert');assert.equal(last.detail.dataset.stOpen,'true');a.S.collapse(last.detail,{keyboard:true});assert.equal(group.inert,original,'Last release restores the original, not another owner’s inert value');n++;
}
const overlap=shared();overlap.a.S.expand(overlap.a.source,overlap.a.detail,{keyboard:false});overlap.a.S.expand(overlap.b.source,overlap.b.detail,{keyboard:false});overlap.a.S.collapse(overlap.a.detail,{keyboard:false});overlap.a.S.expand(overlap.a.source,overlap.a.detail,{keyboard:false});overlap.a.S.collapse(overlap.b.detail,{keyboard:true});assert.equal(overlap.group.inert,true);overlap.a.S.collapse(overlap.a.detail,{keyboard:true});assert.equal(overlap.group.inert,false);n++;
const transfer=shared(),otherGroup=new transfer.a.env.E();otherGroup.inert=false;transfer.a.S.expand(transfer.a.source,transfer.a.detail,{keyboard:true});transfer.a.S.expand(transfer.b.source,transfer.b.detail,{keyboard:true});transfer.a.source.closest=q=>q==='[data-st-expand-sources]'?otherGroup:null;transfer.a.S.expand(transfer.a.source,transfer.a.detail,{keyboard:true});assert.equal(transfer.group.inert,true);assert.equal(otherGroup.inert,true);transfer.a.S.collapse(transfer.b.detail,{keyboard:true});assert.equal(transfer.group.inert,false);assert.equal(otherGroup.inert,true);transfer.a.S.collapse(transfer.a.detail,{keyboard:true});assert.equal(otherGroup.inert,false);n++;
// Expose only the actual production observer callback; the removal logic is unchanged.
const observed=source=>source.replace('new MutationObserver(records => {','new MutationObserver(globalThis.__cardMutation = records => {');
function removal(source=code,original=false,reconnected=false){const f=shared(observed(source),original);f.a.S.expand(f.a.source,f.a.detail,{keyboard:true});f.a.S.expand(f.b.source,f.b.detail,{keyboard:true});f.a.detail.nodeType=1;f.a.detail.isConnected=reconnected;f.a.env.context.__cardMutation([{type:'childList',addedNodes:[],removedNodes:[f.a.detail]}]);return f;}
for(const original of [false,true]){const f=removal(code,original);assert.equal(f.group.inert,true,'Removal must preserve a remaining owner');f.a.S.collapse(f.b.detail,{keyboard:true});assert.equal(f.group.inert,original,'Disconnected owner releases its group hold');n++;}
const moved=removal(code,false,true);moved.a.S.collapse(moved.b.detail,{keyboard:true});assert.equal(moved.group.inert,true,'A reconnected/reparented detail retains ownership');moved.a.S.collapse(moved.a.detail,{keyboard:true});assert.equal(moved.group.inert,false);n++;
const earlyRelease=code.replace('if (!held.owners.size) { group.inert = held.inert; expandSourceOwners.delete(group); }','group.inert = held.inert; expandSourceOwners.delete(group);');assert.notEqual(earlyRelease,code);const premature=shared(earlyRelease);premature.a.S.expand(premature.a.source,premature.a.detail,{keyboard:true});premature.a.S.expand(premature.b.source,premature.b.detail,{keyboard:true});premature.a.S.collapse(premature.a.detail,{keyboard:true});assert.equal(premature.group.inert,false,'Removing last-owner guard reproduces premature source reactivation');n++;
const noRemoval=code.replace('releaseExpandSources(layers.get(l)); active.delete(l);','active.delete(l);');assert.notEqual(noRemoval,code);const leaked=removal(noRemoval);leaked.a.S.collapse(leaked.b.detail,{keyboard:true});assert.equal(leaked.group.inert,true,'Removing disconnect release leaves a stale owner');n++;
console.log(`${n}/${n} Card source-ownership contracts pass; shared groups are last-owner, reversal and disconnect safe`);
