// Current cloud evidence + exact source geometry contract; repaired pixels remain required.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const htmlFile=process.argv[2]||path.resolve(__dirname,'../skills/seenry/assets/components/transitions/gallery.html'),html=fs.readFileSync(htmlFile,'utf8'),js=fs.readFileSync(path.join(path.dirname(htmlFile),'gallery.js'),'utf8');
const observed=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/transitions/cloud-e260-card-observed.json'),'utf8')),results=[],record=(name,fn)=>{fn();results.push({name,pass:true})};
record('Actual hover has zero inset and a one-pixel lift',()=>{assert.equal(observed.hover.rest.padding,'0px');assert.equal(observed.hover.hover.padding,'0px');assert.equal(observed.hover.rest.y-observed.hover.hover.y,1);assert.equal(observed.hover.hover.cover.y,observed.hover.hover.y);assert.equal(observed.hover.hover.cover.x,observed.hover.hover.x);assert.equal(observed.hover.hover.hovered,true);});
record('Both generic row variants and the anchored row override retain real6px padding',()=>{assert.equal((html.match(/grid-template-columns:60px minmax\(0,1fr\);column-gap:12px;padding:6px;margin:0;align-items:center/g)||[]).length,3);assert(!html.includes('column-gap:12px;padding:0;margin:0;align-items:center'));});
record('Source radius is concentric with12px artwork plus6px inset',()=>{assert(html.includes('.cover{display:block;aspect-ratio:1;border-radius:12px}'));assert(/\.cover-card\{[^}]*padding:6px[^}]*border-radius:18px/.test(html));assert.equal(12+6,18);});
record('Hover only changes tint; the intended press scale remains available',()=>{assert(!/\.cover-card:hover\{[^}]*translate/.test(html));assert(html.includes('.cover-card:active{transform:scale(.98)}'));assert(html.includes('.cover-card:hover{background:var(--hover)}'));});
record('Intrinsic preview height preserves a separate Replay lane for all three rows',()=>{assert(html.includes('.card[data-key="expand"]>.stage{height:auto;min-height:324px;padding-bottom:72px}'));const rows=3*(60+2*6)+2*8;assert.equal(rows,232);assert.equal(20+rows+72,324);assert(72-44-16>=12);});
record('Original Why this works note is exposed in the detail Why this works section',()=>{assert(/data-key="expand"[^>]*data-why="A 6px inset/.test(html));assert(html.includes('id="detail-why"'));assert(html.includes('still hover edge.'));assert(html.includes('Keyboard changes are instant; reduced motion removes travel and blur.'));assert(html.includes('3-track preview keeps the album’s total count, and Replay has its own space.'));assert(js.includes("why.querySelector('p').textContent = card.dataset.why || ''"));});
record('Current trusted keyboard evidence distinguishes native cue from mere programmatic focus',()=>{const k=observed.keyboard;assert.equal(k.action,'trusted-keyboard-click');assert.equal(k.close.focusVisible,true);assert.equal(k.close.inputMode,'keyboard');assert.equal(k.close.opacity,'0');assert.equal(k.close.filter,'blur(8px)');assert(k.actualPauseMs>=90&&k.actualPauseMs<=120);});
console.log(`${results.length}/${results.length} Card inset/hover/source-contract checks pass; actual repaired cloud screenshots required`);
