// Focused full-runtime model: deterministic ownership/lifecycle, not browser modality or pixels.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const runtime=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js'));
const fixtureText=fs.readFileSync(path.join(__dirname,'transitions-library-focus-escape.test.cjs'),'utf8');
const scope={require,__dirname,process:{argv:['node','dialog-test',runtime]},console};
vm.runInNewContext(fixtureText.slice(0,fixtureText.indexOf('async function test('))+'\nthis.makeFixture=fixture;',scope);
const source=fs.readFileSync(runtime,'utf8'),html=fs.readFileSync(path.join(path.dirname(runtime),'gallery.html'),'utf8'),results=[];
const flush=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
function modal(reduce=false,keyboard=false){const f=scope.makeFixture(reduce),trigger=new f.E('button'),dialog=new f.E('dialog'),heading=new f.E('h3'),body=new f.E('p'),row=new f.E(),cancel=new f.E('button'),confirm=new f.E('button');dialog.dataset.st='modal';row.className='dialog-actions';cancel.setAttribute('autofocus','');row.append(cancel,confirm);dialog.append(heading,body,row);f.host.append(trigger,dialog);f.S.init(dialog);trigger.focus();if(keyboard)f.key(trigger,'Enter');f.S.open(dialog,trigger,{keyboard});return {...f,trigger,dialog,heading,body,row,cancel,confirm};}
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split("\n")[0]});}}
function controlledModal(keyboard=true){const f=scope.makeFixture(false),trigger=new f.E('button'),dialog=new f.E('dialog'),cancel=new f.E('button'),confirm=new f.E('button'),other=new f.E('button');dialog.dataset.st='modal';cancel.setAttribute('autofocus','');dialog.append(cancel,confirm);f.host.append(trigger,dialog,other);f.S.init(dialog);const events=[];dialog.addEventListener('st:open',()=>events.push('open'));dialog.addEventListener('st:close',()=>events.push('close'));dialog.showModal=()=>{dialog.open=true;dialog.modal=true;cancel.focus();};trigger.focus();if(keyboard)f.key(trigger,'Enter');return {...f,trigger,dialog,cancel,confirm,other,events,begin:()=>f.S.open(dialog,trigger,{keyboard})};}
(async()=>{
await test('gallery uses named native dialog and explicit background blur reduction',()=>{assert(/<dialog class="project-dialog" id="dialog-1" data-st="modal" aria-labelledby="dlg-title" aria-describedby="dlg-description">/.test(html));assert(!/<div[^>]+id="dialog-1"/.test(html));assert(/project-dialog::backdrop\{[^}]*backdrop-filter:blur\(6px\)/.test(html));assert(/@media\(prefers-reduced-motion:reduce\)\{\.project-dialog::backdrop\{[^}]*backdrop-filter:none/.test(html));assert(!html.includes('.stage:has([data-st="modal"][data-st-open="true"]) .app'));assert(/dialog-actions[^\n]+autofocus>Cancel/.test(html));});
await test('destructive semantic role has opaque contrast pair independent of status token',()=>{const bg=/--dialog-danger-surface:(#[\da-f]{6})/.exec(html)?.[1],fg=/--dialog-danger-ink:(#[\da-f]{3,6})/.exec(html)?.[1];assert(bg&&fg);const lum=v=>{v=v.slice(1);if(v.length===3)v=[...v].map(x=>x+x).join('');return [0,2,4].map(i=>parseInt(v.slice(i,i+2),16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((n,x,i)=>n+x*[.2126,.7152,.0722][i],0);};assert((Math.max(lum(bg),lum(fg))+.05)/(Math.min(lum(bg),lum(fg))+.05)>=4.5);assert(/\.project-dialog \.dialog-destructive\{background:var\(--dialog-danger-surface\);color:var\(--dialog-danger-ink\)/.test(html));});
for(const reduce of [false,true])for(const keyboard of [false,true]){
 const label=`${reduce?'reduce':'normal'}/${keyboard?'keyboard':'pointer'}`;
 await test(`${label}: safe focus is immediately readable without delayed content fades`,()=>{const f=modal(reduce,keyboard);assert(f.dialog.open&&f.dialog.modal);assert.equal(f.doc.activeElement,f.cancel);assert.equal(f.trigger.getAttribute('aria-expanded'),'true');assert.equal(f.dialog.inert,false);assert(!f.animations.some(a=>[f.heading,f.body,f.row,f.cancel].includes(a.node)),'No content fade/blur may hide the initial focus');assert(!f.animations.some(a=>a.node===f.dialog&&!a.options.pseudoElement&&a.frames.some(x=>'opacity'in x)),'A newly opened modal has an opaque backing');if(keyboard||reduce)assert(!f.animations.some(a=>a.frames.some(x=>'transform'in x)),'Keyboard/reduced entrance has no travel');});
 await test(`${label}: interrupted close/reopen refocuses safe action and defeats stale close`,async()=>{const f=modal(reduce,keyboard);await f.settle();f.S.close(f.dialog);if(keyboard){assert(!f.dialog.open,'Keyboard close removes native modality synchronously');assert(f.doc.activeElement===f.trigger,'Keyboard close restores focus synchronously');}else assert(f.dialog.open&&f.dialog.inert,'Pointer exit retains open native modal while making controls inactive');assert.equal(f.trigger.getAttribute('aria-expanded'),'false');f.S.open(f.dialog,f.trigger,{keyboard});assert(f.doc.activeElement===f.cancel,'An already-open closing native dialog must refocus on reversal');await f.settle();assert(f.dialog.open&&f.dialog.modal&&!f.dialog.inert);assert.equal(f.dialog.dataset.stOpen,'true');assert.equal(f.trigger.getAttribute('aria-expanded'),'true');assert(f.animations.every(a=>a.cancelled),'Finite effects release after settlement');});
 await test(`${label}: native cancel is managed once and returns focus after cleanup`,async()=>{const f=modal(reduce,keyboard);await f.settle();const event=new f.Event('cancel');f.dialog.dispatchEvent(event);assert(event.defaultPrevented);const count=f.animations.length;f.dialog.dispatchEvent(new f.Event('cancel'));assert.equal(f.animations.length,count,'Repeated cancel must not restart exit');await f.settle();assert(!f.dialog.open);assert.equal(f.dialog.dataset.stOpen,'false');assert.equal(f.doc.activeElement,f.trigger);assert(f.animations.every(a=>a.cancelled));});
}
await test('native child owns Escape above a non-modal parent, including pointer outgoing interval',async()=>{const f=scope.makeFixture(false),parent=new f.E(),child=new f.E('dialog'),trigger=new f.E('button'),cancel=new f.E('button');parent.dataset.st='panel';child.dataset.st='modal';cancel.setAttribute('autofocus','');parent.append(trigger,child);child.append(cancel);f.host.append(parent);f.S.init(child);f.S.open(parent);f.S.open(child,trigger,{keyboard:true});await f.settle();const key=f.key(cancel);assert(!key.defaultPrevented,'Document must leave native child Escape to its cancel event');child.dispatchEvent(new f.Event('cancel'));assert(!child.open,'Native keyboard cancellation is immediate');assert.equal(parent.dataset.stOpen,'true');assert(f.doc.activeElement===trigger);f.doc.dispatchEvent(new f.Event('pointerdown'));f.S.open(child,trigger);await f.settle();f.S.close(child);assert(child.open&&child.inert,'Pointer close has a real outgoing interval');for(let i=0;i<2;i++){const again=f.key(f.doc.body);assert(!again.defaultPrevented,'Outgoing native child retains cancellation ownership');child.dispatchEvent(new f.Event('cancel'));assert(child.open&&child.inert,'Repeated Escape must not end or restart the pointer close');assert.equal(parent.dataset.stOpen,'true');}await f.settle();assert(!child.open);assert.equal(parent.dataset.stOpen,'true');assert(f.doc.activeElement===trigger);});
await test('externally closed native dialog cannot intercept later parent Escape',async()=>{const f=scope.makeFixture(false),parent=new f.E(),child=new f.E('dialog'),trigger=new f.E('button'),cancel=new f.E('button');parent.dataset.st='panel';child.dataset.st='modal';cancel.setAttribute('autofocus','');parent.append(trigger,child);child.append(cancel);f.host.append(parent);f.S.init(child);f.S.open(parent);f.S.open(child,trigger);await f.settle();child.close();assert(!child.open);assert(f.key(trigger).defaultPrevented,'Closed native top entry must not mask active parent');await f.settle();assert.equal(parent.dataset.stOpen,'false');});
await test('manual child menu above native modal owns only the first Escape',async()=>{const f=modal(false,true);await f.settle();const menu=new f.E(),item=new f.E('button');menu.dataset.st='menu';menu.dataset.stContained='';item.setAttribute('role','menuitem');menu.append(item);f.dialog.append(menu);f.S.open(menu,f.confirm,{keyboard:true});await f.settle();assert(f.key(item).defaultPrevented,'Manual inner menu must handle Escape before the native modal');assert(f.dialog.open&&!f.dialog.inert);assert(f.key(f.cancel).defaultPrevented,'Repeated key while menu exits must not fall through');await f.settle();assert.equal(menu.dataset.stOpen,'false');const next=f.key(f.cancel);assert(!next.defaultPrevented,'Next key is native modal cancellation');f.dialog.dispatchEvent(new f.Event('cancel'));await f.settle();assert(!f.dialog.open);});
await test('first-frame fine-pointer geometry preserves authored44px without mislabeling scale as clipping',()=>{const authored=44,scale=.97,rendered=authored*scale;assert.equal(rendered,42.68);assert(rendered<44&&rendered>=24);assert(source.includes("translateY(4px) scale(.97)"));});
await test('native modal survives shell fade completion until longer backdrop job finishes',async()=>{const f=modal();await f.settle();const start=f.animations.length;f.S.close(f.dialog);const jobs=f.animations.slice(start),backdrop=jobs.find(a=>a.options.pseudoElement==='::backdrop');assert(backdrop);jobs.filter(a=>a!==backdrop).forEach(a=>a.finish());await flush();assert(f.dialog.open,'Shell opacity alone must not remove the top layer');backdrop.finish();await flush();assert(!f.dialog.open);assert.equal(f.doc.activeElement,f.trigger);});
await test('reduced exit owns opacity only, with no delay or blur companions',async()=>{const f=modal(true);await f.settle();const n=f.animations.length;f.S.close(f.dialog);for(const a of f.animations.slice(n)){assert(a.options.duration<=100);assert.equal(a.options.delay,0);assert(a.frames.every(x=>Object.keys(x).every(k=>k==='opacity')));}await f.settle();});
await test('autofocus host close aborts obsolete open before backdrop work or open event',()=>{const f=controlledModal(),focus=f.cancel.focus.bind(f.cancel);let count=0;f.cancel.focus=()=>{focus();if(++count===1)f.S.close(f.dialog);};f.begin();assert(!f.dialog.open);assert.equal(f.dialog.dataset.stOpen,'false');assert.equal(f.trigger.getAttribute('aria-expanded'),'false');assert(f.dialog.inert);assert(f.doc.activeElement===f.trigger);assert.deepEqual(f.events,['close']);assert.equal(f.animations.filter(a=>!a.cancelled).length,0);assert.equal(count,1);});
await test('autofocus close/reopen keeps the new owner and host focus redirect',async()=>{const f=controlledModal(),focus=f.cancel.focus.bind(f.cancel);let count=0;f.cancel.focus=()=>{focus();if(++count===1){f.S.close(f.dialog);f.S.open(f.dialog,f.trigger,{keyboard:true});f.confirm.focus();}};f.begin();assert.deepEqual(f.events,['close','open']);assert.equal(count,2,'One native focus acquisition per actual modal open');assert(f.doc.activeElement===f.confirm,'Outer open must not reclaim focus');assert.equal(f.animations.length,1,'Only the new owner starts backdrop work');await f.settle();assert(f.dialog.open&&!f.dialog.inert);assert.equal(f.dialog.dataset.stOpen,'true');});
await test('autofocus redirect without a state change is preserved',()=>{const f=controlledModal(),focus=f.cancel.focus.bind(f.cancel);let count=0;f.cancel.focus=()=>{count++;focus();f.confirm.focus();};f.begin();assert.equal(count,1);assert(f.doc.activeElement===f.confirm);assert.deepEqual(f.events,['open']);});
await test('reversal focus callback may close without a stale subsequent open event',async()=>{const f=controlledModal(false);f.begin();await f.settle();f.S.close(f.dialog);assert(f.dialog.open&&f.dialog.inert);f.key(f.trigger,'Enter');f.events.length=0;const focus=f.cancel.focus.bind(f.cancel);let count=0;f.cancel.focus=()=>{focus();if(++count===1)f.S.close(f.dialog);};f.S.open(f.dialog,f.trigger,{keyboard:true});assert(!f.dialog.open);assert.equal(f.dialog.dataset.stOpen,'false');assert(f.doc.activeElement===f.trigger);assert.deepEqual(f.events,['close']);assert(f.animations.every(a=>a.cancelled));});
await test('reversal focus close/reopen preserves the newest focus and event owner',async()=>{const f=controlledModal(false);f.begin();await f.settle();f.S.close(f.dialog);f.key(f.trigger,'Enter');f.events.length=0;const focus=f.cancel.focus.bind(f.cancel);let count=0;f.cancel.focus=()=>{focus();if(++count===1){f.S.close(f.dialog);f.S.open(f.dialog,f.trigger,{keyboard:true});f.confirm.focus();}};f.S.open(f.dialog,f.trigger,{keyboard:true});assert(f.dialog.open&&!f.dialog.inert);assert.equal(f.dialog.dataset.stOpen,'true');assert(f.doc.activeElement===f.confirm);assert.deepEqual(f.events,['close','open']);await f.settle();assert(f.dialog.open);});
for(const nativeReturn of [false,true])await test(`${nativeReturn?'native':'explicit'} return-focus reopening survives old close cleanup and event dispatch`,async()=>{const f=controlledModal();f.begin();await f.settle();f.events.length=0;const focus=f.trigger.focus.bind(f.trigger);let once=false;f.trigger.focus=()=>{focus();if(!once){once=true;f.S.open(f.dialog,f.trigger,{keyboard:true});f.confirm.focus();}};if(nativeReturn)f.dialog.close=()=>{f.dialog.open=false;f.dialog.modal=false;f.trigger.focus();};f.S.close(f.dialog);assert(once);assert(f.dialog.open&&!f.dialog.inert);assert.equal(f.dialog.dataset.stOpen,'true');assert.equal(f.trigger.getAttribute('aria-expanded'),'true');assert(f.doc.activeElement===f.confirm);assert.deepEqual(f.events,['open'],'An obsolete close must not be emitted after the new open');await f.settle();assert(f.dialog.open);assert.equal(f.dialog.dataset.stOpen,'true');});
await test('return-focus host redirect is not acquired again',async()=>{const f=controlledModal();f.begin();await f.settle();f.events.length=0;const focus=f.trigger.focus.bind(f.trigger);let count=0;f.trigger.focus=()=>{count++;focus();f.other.focus();};f.S.close(f.dialog);assert.equal(count,1);assert(f.doc.activeElement===f.other);assert(!f.dialog.open);assert.deepEqual(f.events,['close']);});
for(const nativeReturn of [false,true])await test(`${nativeReturn?'native':'explicit'} pointer-return reopen starts after old held opacity and transform retire`,async()=>{const f=controlledModal(false);f.begin();await f.settle();const initial={opacity:f.dialog.style.opacity,transform:f.dialog.style.transform};f.events.length=0;const focus=f.trigger.focus.bind(f.trigger);let observed=null;f.trigger.focus=()=>{focus();if(!observed){observed={opacity:f.dialog.style.opacity,transform:f.dialog.style.transform};f.S.open(f.dialog,f.trigger);f.confirm.focus();}};if(nativeReturn)f.dialog.close=()=>{f.dialog.open=false;f.dialog.modal=false;f.trigger.focus();};f.S.close(f.dialog);assert(f.dialog.open&&f.dialog.inert);await f.settle();assert(observed);assert.equal(observed.opacity,initial.opacity,'Held opacity0 must retire before host native-return callback');assert.equal(observed.transform,initial.transform,'Held exit transform must retire before host native-return callback');assert(f.dialog.open&&!f.dialog.inert);assert.equal(f.dialog.dataset.stOpen,'true');assert.notEqual(f.dialog.style.opacity,'0');assert.deepEqual(f.events,['open']);assert(f.doc.activeElement===f.confirm);});
await test('pointer autofocus close retains native Escape ownership through its outgoing interval',async()=>{const f=controlledModal(false),parent=new f.E();parent.dataset.st='panel';f.host.append(parent);parent.append(f.trigger,f.dialog);f.S.open(parent);const focus=f.cancel.focus.bind(f.cancel);let once=false;f.cancel.focus=()=>{focus();if(!once){once=true;f.S.close(f.dialog);}};f.begin();assert(f.dialog.open&&f.dialog.inert,'Host requested a real pointer exit during autofocus');const key=f.key(f.doc.body,'Escape');assert(!key.defaultPrevented,'Native outgoing child must remain above its active non-modal parent');f.dialog.dispatchEvent(new f.Event('cancel'));assert.equal(parent.dataset.stOpen,'true');await f.settle();assert(!f.dialog.open);assert.equal(parent.dataset.stOpen,'true');assert.deepEqual(f.events,['close']);});
const report={sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),htmlSha256:crypto.createHash('sha256').update(html).digest('hex'),scope:'Deterministic modeled full-runtime and source contract. Does not establish native modality, trusted input, timing or pixels.',passed:results.filter(x=>x.pass).length,total:results.length,results};if(process.argv[3])fs.writeFileSync(process.argv[3],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})();
