// Execute the actual page-side settlement collector under a deterministic RAF/timer
// model. This tests re-observation and atomic snapshot ownership, not browser pixels.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const file=path.join(__dirname,'transitions-library-dialog.browser.mjs'),source=fs.readFileSync(file,'utf8');
const start=source.indexOf('async function settledDialogSnapshot('),end=source.indexOf('const waitClosed=',start);assert(start>=0&&end>start);const helper=source.slice(start,end);
const results=[];async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split('\n')[0]});}}
function fixture(){
 let now=0,nextId=1,inventory=[],inspects=0,inventoryReads=0,inspectHook=()=>{},readHook=()=>{},stopped=false;const rafs=new Map(),timers=new Map(),listeners=new Map();
 const d={isConnected:true,open:true,inert:false,dataset:{stOpen:'true'},matches:()=>d.open,getAnimations(){inventoryReads++;readHook(inventoryReads);return [...inventory];}};
 const window={addEventListener:(name,fn)=>{const set=listeners.get(name)||new Set();set.add(fn);listeners.set(name,set);},removeEventListener:(name,fn)=>listeners.get(name)?.delete(fn),dialogAnimationEvidence:a=>a.evidence,__dialogInspect:()=>{inspects++;inspectHook(inspects);return {open:d.open,modal:d.open,inert:d.inert,animations:inventory.map(a=>({...a.evidence,playState:a.playState})),at:now,paintMarker:'captured-'+inspects};}};
 const context={window,document:{querySelector:()=>d},performance:{now:()=>now},requestAnimationFrame:fn=>{const id=nextId++;rafs.set(id,fn);return id;},cancelAnimationFrame:id=>rafs.delete(id),setTimeout:(fn,delay)=>{const id=nextId++;timers.set(id,{fn,at:now+delay});return id;},clearTimeout:id=>timers.delete(id)};
 vm.createContext(context);vm.runInContext(helper+'\nthis.run=settledDialogSnapshot;this.retain=retainSettlementFailure;',context);
 const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
 const tick=async(ms=16)=>{now+=ms;for(const [id,timer]of [...timers])if(timer.at<=now){timers.delete(id);timer.fn();}const batch=[...rafs];rafs.clear();for(const [,fn]of batch)fn(now);await flush();};
 const job=(name='backgroundColor')=>({playState:'running',evidence:{target:'st-button',targetRelationship:'descendant',targetTag:'BUTTON',pseudo:null,properties:[name],duration:100}});
 const run=options=>{const state={status:'pending',value:null,error:null};state.promise=context.run(options).then(value=>{state.status='resolved';state.value=value;},error=>{state.status='rejected';state.error=error;});return state;};
 return {d,window,tick,flush,job,run,rafs,timers,listeners,retain:context.retain,get inspects(){return inspects;},get reads(){return inventoryReads;},setJobs:jobs=>{inventory=jobs;},onInspect:fn=>{inspectHook=fn;},onInventory:fn=>{readHook=fn;},advance:ms=>{now+=ms;},emit:(name,event={})=>{for(const fn of [...(listeners.get(name)||[])])fn(event);},clean:()=>{assert.equal(rafs.size,0);assert.equal(timers.size,0);assert([...listeners.values()].every(x=>x.size===0),'Collector listeners release');}};
}
(async()=>{
await test('two quiet RAF observations return the verified snapshot with no later read',async()=>{const f=fixture(),r=f.run();await f.tick();assert.equal(r.status,'pending');await f.tick();assert.equal(r.status,'resolved');assert.equal(r.value.animations.length,0);assert.equal(r.value.paintMarker,'captured-1');assert.equal(r.value.settlement.quietFrames,2);assert.equal(f.inspects,1);f.setJobs([f.job()]);assert.equal(r.value.animations.length,0,'Returned capture is an atomic past snapshot, not a later protocol read');f.clean();});
await test('new jobs after initial inventory are re-observed through completion',async()=>{const f=fixture(),first=f.job('transform'),hover=f.job();f.setJobs([first]);const r=f.run();await f.tick();f.setJobs([]);await f.tick();f.setJobs([hover]);await f.tick();assert.equal(r.status,'pending');f.setJobs([]);await f.tick();assert.equal(r.status,'pending');await f.tick();assert.equal(r.status,'resolved');assert.equal(r.value.animations.length,0);assert(r.value.settlement.observations.some(o=>o.animations.some(a=>a.properties.includes('backgroundColor'))));f.clean();});
await test('hover started by the full inspection invalidates the quiet window',async()=>{const f=fixture();f.onInspect(n=>{if(n===1)f.setJobs([f.job('backgroundColor'),f.job('boxShadow')]);});const r=f.run();await f.tick();await f.tick();assert.equal(r.status,'pending');assert.equal(f.inspects,1);f.setJobs([]);await f.tick();await f.tick();assert.equal(r.status,'resolved');assert.equal(f.inspects,2);assert(r.value.settlement.observations.some(o=>o.inspectionAnimations?.length===2));f.clean();});
await test('job introduced after snapshot inventory is caught by the synchronous final inventory',async()=>{const f=fixture();f.onInventory(n=>{if(n===3)f.setJobs([f.job()]);});const r=f.run();await f.tick();await f.tick();assert.equal(r.status,'pending');f.setJobs([]);await f.tick();await f.tick();assert.equal(r.status,'resolved');f.clean();});
await test('cancelled animation replaced by another job cannot falsely settle',async()=>{const f=fixture(),a=f.job(),b=f.job('boxShadow');f.setJobs([a]);const r=f.run();await f.tick();a.playState='idle';f.setJobs([b]);await f.tick();assert.equal(r.status,'pending');f.setJobs([]);await f.tick();assert.equal(r.status,'pending');await f.tick();assert.equal(r.status,'resolved');f.clean();});
await test('persistent or repeatedly replaced jobs fail at the bounded deadline',async()=>{const f=fixture(),r=f.run({timeoutMs:64});for(let i=0;i<4;i++){f.setJobs([f.job()]);await f.tick();}assert.equal(r.status,'rejected');assert.match(r.error.message,/deadline/);f.clean();});
await test('deadline timer rejects even when RAF never fires',async()=>{const f=fixture(),r=f.run({timeoutMs:20});f.rafs.clear();await f.tick(21);assert.equal(r.status,'rejected');assert.match(r.error.message,/deadline/);f.clean();});
await test('inspection cannot return success after its deadline',async()=>{const f=fixture();f.onInspect(()=>f.advance(100));const r=f.run({timeoutMs:64});await f.tick();await f.tick();assert.equal(r.status,'rejected');assert.match(r.error.message,/deadline/);f.clean();});
for(const field of ['open','isConnected','inert'])await test('modal cancellation rejects when '+field+' changes',async()=>{const f=fixture(),r=f.run();await f.tick();f.d[field]=field==='inert';await f.tick();assert.equal(r.status,'rejected');assert.match(r.error.message,/cancelled/);f.clean();});
await test('cancellation during inspection cannot return a closed snapshot as settled',async()=>{const f=fixture();f.onInspect(()=>f.d.open=false);const r=f.run();await f.tick();await f.tick();assert.equal(r.status,'rejected');assert.match(r.error.message,/cancelled/);f.clean();});
for(const [event,detail,pattern] of [['error',{message:'native fixture page error'},/Page error/],['unhandledrejection',{reason:'fixture rejected'},/Page rejection/],['pagehide',{},/cancelled/]])await test(event+' rejects and releases scheduled observations',async()=>{const f=fixture(),r=f.run();await f.tick();f.emit(event,detail);await f.flush();assert.equal(r.status,'rejected');assert.match(r.error.message,pattern);f.clean();});
await test('inventory exception fails rather than masquerading as an empty inventory',async()=>{const f=fixture();f.onInventory(()=>{throw new Error('inventory unavailable');});const r=f.run();await f.tick();assert.equal(r.status,'rejected');assert.match(r.error.message,/inventory unavailable/);f.clean();});
await test('settled paint still requires an empty inventory and callers consume returned snapshots',()=>{assert(source.includes("if(settled)assert.equal(s.animations.length,0,'No owned effects remain after settlement')"));assert(!/await settle\(page\);(?:const settled|r\.controlled\.settled|r\.liveReduction|run\.blurOff)=await page\.evaluate/.test(source));for(const use of ['const settled=await settle(page)','r.controlled.settled=await settle(page)','r.liveReduction=await settle(page)','run.blurOff=await settle(page)','assertPaint(await settle(page)'])assert(source.includes(use),use);});
await test('deadline retains a serializable frozen observation inventory without swallowing rejection',async()=>{const f=fixture(),job=f.job();f.setJobs([job]);const r=f.run({timeoutMs:32});await f.tick();await f.tick();assert.equal(r.status,'rejected');const failure=f.window.__dialogSettlementFailure;assert.equal(failure.status,'failed');assert.equal(failure.error.message,r.error.message);assert.equal(failure.elapsedMs,32);assert.equal(failure.timeoutMs,32);assert.equal(failure.observations.length,1);assert.equal(failure.observations[0].animations[0].properties[0],'backgroundColor');job.evidence.properties[0]='transform';assert.equal(failure.observations[0].animations[0].properties[0],'backgroundColor','Snapshot is detached from later mutable data');assert.doesNotThrow(()=>JSON.stringify(failure));f.clean();});
await test('cancelled modal retains terminal state and prior observations',async()=>{const f=fixture(),r=f.run();await f.tick();f.d.open=false;await f.tick();const failure=f.window.__dialogSettlementFailure;assert.equal(r.status,'rejected');assert.equal(failure.state.open,false);assert.equal(failure.observations.length,1);assert.match(failure.error.message,/cancelled/);f.clean();});
await test('page error retains its cause while rejecting the same failure',async()=>{const f=fixture(),r=f.run();await f.tick();f.emit('error',{message:'render exploded'});await f.flush();const failure=f.window.__dialogSettlementFailure;assert.equal(r.status,'rejected');assert.equal(failure.error.message,r.error.message);assert.match(failure.error.message,/render exploded/);assert.equal(failure.observations.length,1);f.clean();});
await test('inventory exception preserves original Error identity and retained earlier evidence',async()=>{const f=fixture(),original=new Error('inventory exploded'),r=f.run();await f.tick();f.onInventory(()=>{throw original;});await f.tick();assert.equal(r.error,original);assert.equal(f.window.__dialogSettlementFailure.error.message,original.message);assert.equal(f.window.__dialogSettlementFailure.observations.length,1);f.clean();});
await test('last full snapshot survives a deadline during inspection',async()=>{const f=fixture();f.onInspect(()=>f.advance(100));const r=f.run({timeoutMs:64});await f.tick();await f.tick();assert.equal(r.status,'rejected');const failure=f.window.__dialogSettlementFailure;assert.equal(failure.lastSnapshot.paintMarker,'captured-1');assert.equal(failure.lastSnapshot.animations.length,0);assert.equal(failure.observations.length,2);f.clean();});
await test('new attempt clears stale failure and success keeps the resolved snapshot contract',async()=>{const f=fixture(),first=f.run({timeoutMs:16});await f.tick();assert.equal(first.status,'rejected');assert(f.window.__dialogSettlementFailure);const next=f.run();assert.equal(f.window.__dialogSettlementFailure,null);await f.tick();await f.tick();assert.equal(next.status,'resolved');assert.equal(next.value.paintMarker,'captured-1');assert.equal(f.window.__dialogSettlementFailure,null);f.clean();});
await test('serialization failure retains a fallback cause and does not replace the original error',async()=>{const f=fixture(),cyclic={};cyclic.self=cyclic;const original=new Error('original failure');f.window.__dialogInspect=()=>cyclic;const r=f.run();await f.tick();f.onInventory(n=>{if(n===3)throw original;});await f.tick();assert.equal(r.error,original);assert.equal(f.window.__dialogSettlementFailure.error.message,original.message);assert.match(f.window.__dialogSettlementFailure.evidenceSerializationError,/circular/i);f.clean();});
const catchStart=source.indexOf("}catch(e){run.status='failed';"),catchEnd=source.indexOf('\n  finally',catchStart);assert(catchStart>=0&&catchEnd>catchStart);const catchBody=source.slice(catchStart+10,catchEnd-1);
for(const unavailable of [false,true])await test('actual failed-case handler '+(unavailable?'records unavailable evidence':'copies evidence before first save')+' without changing failure',async()=>{const failure={status:'failed',observations:[{elapsedMs:16,animations:[]}]},original=new Error('original run failure'),run={},writes=[];const page={evaluate:async()=>{if(unavailable)throw new Error('execution context destroyed');return failure;},screenshot:async()=>{}};const c={e:original,run,page,retainSettlementFailure:fixture().retain,save:()=>writes.push(JSON.parse(JSON.stringify(run))),out:'out',label:'case',join:path.join};vm.createContext(c);await vm.runInContext('(async()=>{'+catchBody+'})()',c);assert.equal(run.status,'failed');assert.equal(run.error,original.stack);assert.equal(writes.length,1);if(unavailable){assert.match(writes[0].settlementFailureUnavailable,/execution context destroyed/);assert.equal(writes[0].settlementFailure,undefined);}else assert.deepEqual(writes[0].settlementFailure,failure);});
const report={harnessSha256:crypto.createHash('sha256').update(source).digest('hex'),scope:'Actual page-side collector in modeled RAF/timer/DOM events. Fresh native frame timing and pixels remain unverified.',passed:results.filter(r=>r.pass).length,total:results.length,results};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})();
