const assert=require('node:assert/strict');
(async()=>{const {cardReadableFindings}=await import('./transitions-library-card-readable.mjs');
const leaf=text=>({text,painted:true,visibility:'visible',display:'block',effectiveDisplay:true,opacity:1,colorAlpha:1,filter:'none',ancestorFilters:[{filter:'none'}],clipPath:'none',paintAncestors:[{clipPath:'none'}],glyphs:[{left:20,top:20,right:80,bottom:40,width:60,height:20}]});
const row={shell:{left:0,top:0,right:300,bottom:300},details:[{painted:true,opacity:1}],keyboardText:{cue:leaf('3-track preview'),tracks:[1,2,3].map(i=>({name:leaf('Track '+i),duration:leaf('3:12')}))}};
assert.deepEqual(cardReadableFindings(row),[]);let n=1;
for(const mutate of [x=>x.painted=false,x=>delete x.opacity,x=>delete x.colorAlpha,x=>delete x.ancestorFilters,x=>x.opacity=0,x=>x.colorAlpha=0,x=>x.filter='blur(8px)',x=>x.ancestorFilters[0].filter='blur(8px)',x=>x.glyphs=[],x=>x.glyphs[0].width=0,x=>x.clipPath='inset(100%)',x=>x.paintAncestors[0].clipPath='inset(100%)',x=>x.text='',x=>{x.glyphs[0].right=400;x.glyphs[0].width=380}]){const bad=structuredClone(row);mutate(bad.keyboardText.tracks[1].name);assert.equal(bad.details[0].painted,true);assert(cardReadableFindings(bad).length>0,'A painted wrapper cannot mask an unreadable child');n++;}
for(const target of ['cue','tracks']){const bad=structuredClone(row);if(target==='cue')bad.keyboardText.cue=null;else bad.keyboardText.tracks.pop();assert(cardReadableFindings(bad).length>0);n++;}
for(const overflow of ['hidden','clip']){const bad=structuredClone(row);bad.keyboardText.tracks[1].name.paintAncestors.unshift({clipPath:'none',overflow,rect:{left:0,top:0,right:300,bottom:1}});assert(cardReadableFindings(bad).some(f=>f.kind==='overflow-clipped-leaf'));n++;const good=structuredClone(row);good.keyboardText.tracks[1].name.paintAncestors.unshift({clipPath:'none',overflow,rect:row.shell});assert.deepEqual(cardReadableFindings(good),[]);n++;}
for(const [overflowX,overflowY,rect] of [['hidden','visible',{left:0,top:0,right:300,bottom:1}],['visible','clip',{left:0,top:0,right:1,bottom:300}]]){const good=structuredClone(row);good.keyboardText.tracks[0].name.paintAncestors.unshift({clipPath:'none',overflowX,overflowY,rect});assert.deepEqual(cardReadableFindings(good),[],'Visible axis must not be constrained by the other clipped axis');n++;}
const inner=structuredClone(row);inner.keyboardText.cue.paintAncestors.unshift({clipPath:'none',overflow:'hidden',rect:row.shell,clipRect:{left:0,top:0,right:300,bottom:1}});assert(cardReadableFindings(inner).some(f=>f.kind==='overflow-clipped-leaf'),'Client/padding clip bounds must win over an enclosing border box');n++;
console.log(`${n}/${n} instant Card leaf-paint contracts pass; hidden, transparent, blurred and clipped children cannot hide behind a painted wrapper`);
})().catch(e=>{console.error(e);process.exitCode=1});
