import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {timingWindow,finiteState,rectInside,classifyObservation,escapeOwnership,parseColor,over,contrast,effectivePaint,keyboardFirstPaint,verifyPins,sha256,reducedMotionFindings,trustedActionEvidence,parentOwnedOpen,canSendParentEscape,identityValue,nativeClipGeometry,actionCollectionIssues,collectionSummary,collectNativeAction,makeBoundedFinalizer,lifecycleObservation,nativeBoundaryReady,createClockedEventListeners,inputEventBoundary} from './transitions-library-menu-discovery-helpers.mjs';
const dir=dirname(fileURLToPath(import.meta.url));
const layer=(extra={})=>({node:'item',background:'rgb(255, 255, 255)',backgroundImage:'none',mixBlendMode:'normal',opacity:'1',filter:'none',backdropFilter:'none',visibility:'visible',display:'block',...extra});
test('a missed first-frame window is blocked, not passed or product-failed',()=>{for(const ms of [51,NaN,Infinity,-1])assert.equal(timingWindow(ms).status,'blocked');assert.equal(timingWindow(16).status,'observed-in-window');});
test('held finished animations and pending transitions cannot impersonate released native settlement',()=>{const a=[{iterations:1,playState:'finished',fill:'forwards'},{iterations:1,playState:'idle',pending:true},{iterations:null,playState:'running'},{iterations:Infinity,playState:'running'}];assert.equal(finiteState(a).held.length,1);assert.equal(finiteState(a).running.length,1);assert.equal(finiteState(a).unknown.length,1);});
test('positive whole last-row containment is required, not document overflow or its center',()=>{const clip={left:0,top:0,right:100,bottom:100};assert(rectInside({left:0,top:56,right:100,bottom:100,width:100,height:44},clip));for(const r of [{left:0,top:90,right:100,bottom:134,width:100,height:44},{left:0,top:0,right:0,bottom:0,width:0,height:0}])assert(!rectInside(r,clip));});
test('a menu item covering the original trigger is a finding even when ARIA is right',()=>{const s={expanded:'true',triggerPoint:{x:5,y:5},triggerHit:{isTrigger:false,top:'Rename'},inert:false};assert.equal(classifyObservation(s)[0].kind,'original-trigger-covered');assert.equal(classifyObservation({...s,triggerHit:{isTrigger:true}}).length,0);});
test('outgoing inert paint is allowed but interactive outgoing paint is not',()=>{assert.equal(classifyObservation({expanded:'false',inert:true,presentation:'true'}).length,0);assert.equal(classifyObservation({expanded:'false',inert:false,presentation:'true'})[0].kind,'outgoing-menu-interactive');});
test('child Escape must preserve parent, hash and moved stage; later Escape returns title focus',()=>{const before={parent:{tag:'DIALOG',nativeOpen:true,modal:true,presentation:'true',hidden:false,inert:false,display:'block',visibility:'visible'},hash:'#t/menu',stageOwner:'detail',expanded:'true'};const after={...before,expanded:'false',inert:true,focus:{id:'menu-trigger',control:'menu-trigger',inParent:true}};assert(escapeOwnership(before,after,'child'));for(const bad of [{hash:''},{stageOwner:'gallery'},{parent:{presentation:'false'}},{expanded:'true'},{focus:{id:'BODY'}}])assert(!escapeOwnership(before,{...after,...bad},'child'));assert(escapeOwnership(before,{parent:{nativeOpen:false,modal:false,presentation:'false'},stageOwner:'gallery',hash:'',focus:{detail:'menu',control:'detail-title'}},'parent'));});
test('alpha compositing handles transparent ancestors and group opacity',()=>{assert.deepEqual(parseColor('rgb(0 0 0 / 50%)'),[0,0,0,.5]);assert.deepEqual(over([0,0,0,.5],[1,1,1,1]),[.5,.5,.5,1]);assert.equal(contrast([0,0,0,1],[1,1,1,1]),21);const p=effectivePaint({color:'rgb(0, 0, 0)',chain:[layer({opacity:'.1'}),layer()]});assert.equal(p.effectiveOpacity,.1);assert(p.samples[0].ratio<1.3);assert.equal(p.status,'modeled-only');});
test('blur, images, invisible text and unsupported colors do not become contrast passes',()=>{for(const bad of [{filter:'blur(4px)'},{backgroundImage:'linear-gradient(red,blue)'},{mixBlendMode:'multiply'},{backdropFilter:'blur(4px)'}])assert.equal(effectivePaint({color:'rgb(0,0,0)',chain:[layer(bad)]}).status,'unverified-effects');assert.equal(effectivePaint({color:'nonsense',chain:[layer()]}).status,'unverified');assert.equal(effectivePaint({color:'rgb(0,0,0)',chain:[layer({visibility:'hidden'})]}).visible,false);});
test('keyboard first sample requires trusted activation and cannot relabel a late rAF',()=>{const state={expanded:'true',inert:false,focus:{control:'menuitem:0'},first:{node:{control:'menuitem:0'},focused:true,color:'rgb(0,0,0)',chain:[layer()]}};const a={events:[{type:'keydown',trusted:true,key:'Enter',target:{control:'menu-trigger'},at:99},{eventId:2,type:'click',trusted:true,detail:0,target:{control:'menu-trigger'},at:100,eventAt:100}],accepted:[{type:'click',trusted:true,detail:0,target:{control:'menu-trigger'},at:100,eventAt:100,captureEventId:2,clockStatus:'linked-capture-event',state}],frames:[{...state,at:117}]};assert.equal(keyboardFirstPaint(a).status,'measured-not-pixel-reviewed');assert.equal(keyboardFirstPaint({...a,accepted:[{...a.accepted[0],trusted:false}]}).status,'blocked');assert.equal(keyboardFirstPaint({...a,frames:[{...a.frames[0],at:170}]}).status,'blocked');});
test('all product and harness hashes are enforced, including a same-length mutation',()=>{const root=mkdtempSync(join(tmpdir(),'menu-pin-test-'));try{writeFileSync(join(root,'gallery.html'),'A');writeFileSync(join(root,'h.mjs'),'B');const pins={assets:{'gallery.html':sha256(join(root,'gallery.html'))},harness:{'h.mjs':sha256(join(root,'h.mjs'))}};verifyPins(join(root,'gallery.html'),pins,root);writeFileSync(join(root,'gallery.html'),'Z');assert.throws(()=>verifyPins(join(root,'gallery.html'),pins,root),/SOURCE_PIN_MISMATCH/);writeFileSync(join(root,'gallery.html'),'A');writeFileSync(join(root,'h.mjs'),'C');assert.throws(()=>verifyPins(join(root,'gallery.html'),pins,root),/HARNESS_PIN_MISMATCH/);}finally{rmSync(root,{recursive:true});}});
test('source contract: one bounded three-case pinned-CI route and no production mutations',()=>{const s=readFileSync(join(dir,'transitions-library-menu-discovery.browser.mjs'),'utf8');assert.match(s,/process\.env\.GITHUB_ACTIONS!==['"]true/);assert.match(s,/version!==['"]1\.63\.0/);assert.match(s,/105_000/);assert.match(s,/D1/);assert.match(s,/D2/);assert.match(s,/D3/);assert.doesNotMatch(s,/SeenryTransitions\.(open|close|toggle)|\.pause\(|setPlaybackRate|addStyleTag|\.style\s*[.=]|dispatchEvent|\.focus\(/);assert.match(s,/document\.addEventListener\(type,accepted\)/);assert.match(s,/animations:'allow'/);assert.match(s,/verifyPins\(gallery,pins,here\)/);assert.match(s,/first-paint-window/);assert.match(s,/scope:'discovery-only'/);});

test('reduced evidence rejects nonidentity movement and long opacity without penalizing identity channels',()=>{const a={target:{id:'menu-1'},values:{transform:['none','matrix(1, 0, 0, 1, 0, 0)'],filter:['blur(0px)']},properties:['opacity'],duration:100};assert.equal(reducedMotionFindings([{animations:[a]}]).length,0);assert.equal(reducedMotionFindings([{animations:[{...a,values:{transform:['scale(.96)','none']}}]}])[0].kind,'reduced-motion-nonidentity-keyframes');assert.equal(reducedMotionFindings([{animations:[{...a,duration:101}]}])[0].kind,'reduced-opacity-duration-over-100ms');});

test('semantic endpoints cannot substitute for trusted pointer and keyboard input',()=>{assert(!trustedActionEvidence({name:'blur-off-pointer-open',events:[{type:'click',trusted:false,detail:1}]}));assert(!trustedActionEvidence({name:'blur-off-pointer-open',events:[{type:'click',trusted:true,detail:1}]}));assert(trustedActionEvidence({name:'blur-off-pointer-open',events:[{type:'pointerdown',trusted:true,target:{control:'menu-trigger'},at:1},{type:'click',trusted:true,detail:1,target:{control:'menu-trigger'},at:2}]}));assert(trustedActionEvidence({name:'blur-off-keyboard-open-Space',events:[{type:'keydown',trusted:true,key:' ',target:{control:'menu-trigger'},at:1}]}));assert(!trustedActionEvidence({name:'blur-off-keyboard-open-Enter',events:[{type:'keydown',trusted:true,key:'Escape'}]}));});

test('a faint row focus tint cannot become a 3:1 cue simply because text contrast is high',()=>{const p=effectivePaint({color:'rgb(0,0,0)',chain:[layer({background:'rgba(0,0,0,.05)'}),layer()]});assert(p.samples[0].ratio>15);assert(p.samples[0].backgroundCueRatio<1.2);assert.equal(p.status,'modeled-only');});

const goodParent=()=>({tag:'DIALOG',nativeOpen:true,modal:true,presentation:'true',hidden:false,inert:false,display:'block',visibility:'visible'});
const goodState=()=>({parent:goodParent(),stageOwner:'detail',hash:'#t/menu',expanded:'true',inert:false,focus:{control:'menuitem:0',inParent:true}});
const goodClosed=()=>({...goodState(),expanded:'false',inert:true,focus:{control:'menu-trigger',inParent:true}});
const goodAction=()=>({id:'D1:0',name:'blur-off-pointer-open',status:'collected',events:[{type:'pointerdown',trusted:true,target:{control:'menu-trigger'},at:10},{type:'click',trusted:true,detail:1,target:{control:'menu-trigger'},at:11}],accepted:[],frames:[],after:{animations:[]},settlement:{status:'native-finite-settlement-observed'},trustedInputObserved:true});
const goodRun=()=>({id:'D1',actions:[goodAction()],pngs:[{name:'first',status:'captured',before:{at:1},after:{at:2}}],errors:[],blocked:[],findings:[],nativeSequenceCompleted:true,rasterCompleted:true,video:{finalized:true,bytes:10}});

test('collection summary propagates settlement, input, trace, PNG and video incompleteness independently of product findings',()=>{
 const good=goodRun();good.findings.push({kind:'original-trigger-covered'});assert.equal(collectionSummary(good).status,'collected');
 for(const mutate of [r=>r.actions[0].settlement={status:'blocked',reason:'missed'},r=>r.actions[0].trustedInputObserved=false,r=>r.actions[0].after=null,r=>r.actions[0].error='trace retrieval failed',r=>r.pngs[0].status='blocked',r=>r.pngs[0].after=null,r=>r.video.finalized=false,r=>r.video.probe={status:'blocked',reason:'no pts'},r=>r.nativeSequenceCompleted=false,r=>r.rasterCompleted=false,r=>r.actions[0].status='requested']){const run=goodRun();mutate(run);assert.equal(collectionSummary(run).status,'incomplete');}
});
test('real action collector persists a stub before arming/dispatch and preserves failures in run.blocked',async()=>{
 for(const failing of ['arm','input','afterInput','settle','finish']){
  const run={id:'D1',actions:[],blocked:[]},order=[],persist=()=>order.push('persist');
  const call=name=>async()=>{order.push(name);if(name===failing)throw new Error(name+' failure');if(name==='arm')return {requestedAt:1};if(name==='settle')return {status:'native-finite-settlement-observed'};if(name==='finish')return goodAction();};
  const result=await collectNativeAction({run,name:'blur-off-pointer-open',arm:call('arm'),input:call('input'),afterInput:call('afterInput'),settle:call('settle'),finish:call('finish'),persist});
  assert.equal(order[0],'persist');assert.equal(run.actions.length,1);assert.equal(run.actions[0],result);assert.equal(result.status,'blocked');assert(run.blocked.length>0);if(failing==='arm')assert(!order.includes('input'));
 }
});
test('real action collector rejects a stale action trace and a blocked native settlement even with trusted input',async()=>{
 for(const mode of ['wrong-id','blocked-settlement']){const run={id:'D1',actions:[],blocked:[]};const result=await collectNativeAction({run,name:'blur-off-pointer-open',arm:async()=>({requestedAt:1}),input:async()=>{},settle:async()=>({status:mode==='blocked-settlement'?'blocked':'native-finite-settlement-observed'}),finish:async()=>{const {settlement,...trace}=goodAction();return {...trace,id:mode==='wrong-id'?'D1:previous':'D1:0'};},persist:()=>{}});assert.equal(result.status,'blocked');assert(run.blocked.length);}
});
test('bounded finalization retrieves trace then closes context and saves video even after retrieval timeout; duplicate calls share completion',async()=>{
 const order=[],errors=[],saved=[];const finalize=makeBoundedFinalizer([{name:'trace',run:()=>{order.push('trace');return new Promise(()=>{});}},{name:'context',run:async()=>order.push('context')},{name:'video',run:async()=>order.push('video')}],{timeoutMs:5,onError:e=>errors.push(e),persist:r=>saved.push(r.map(x=>x.status))});
 const [a,b]=await Promise.all([finalize(),finalize()]);assert.equal(a,b);assert.deepEqual(order,['trace','context','video']);assert.equal(errors[0].name,'trace');assert.equal(a[0].status,'blocked');assert.equal(a[2].status,'completed');assert(saved.length>=6);
});
test('same-point pointer close rejects a trusted Delete click, mixed controls and pre-arm stale input',()=>{
 const valid={...goodAction(),name:'blur-off-original-point-close',requestedAt:9};assert(trustedActionEvidence(valid));
 for(const events of [valid.events.map(e=>({...e,target:{control:'menuitem:4'}})),[valid.events[0],{...valid.events[1],target:{control:'menuitem:4'}}],valid.events.map(e=>({...e,at:1})),valid.events.map(({at,...e})=>e)])assert(!trustedActionEvidence({...valid,events}));
});
test('first paint rejects unrelated trusted click, wrong focus, absent key provenance and wrong first-item identity',()=>{
 const state={expanded:'true',inert:false,focus:{control:'menuitem:0'},first:{node:{control:'menuitem:0'},focused:true,color:'rgb(0,0,0)',chain:[layer()]}};
 const valid={events:[{type:'keydown',trusted:true,key:'Enter',at:9,target:{control:'menu-trigger'}},{eventId:2,type:'click',trusted:true,detail:0,at:10,eventAt:10,target:{control:'menu-trigger'}}],accepted:[{type:'click',trusted:true,detail:0,at:10,eventAt:10,captureEventId:2,clockStatus:'linked-capture-event',target:{control:'menu-trigger'},state}],frames:[{...state,at:26}]};assert.equal(keyboardFirstPaint(valid).status,'measured-not-pixel-reviewed');
 for(const bad of [{events:[]},{events:[{...valid.events[0],target:{control:'menuitem:4'}}]},{accepted:[{...valid.accepted[0],target:{control:'outside'}}]},{frames:[{...state,at:26,focus:{control:'menuitem:4'}}]},{frames:[{...state,at:26,first:{...state.first,node:{control:'menuitem:4'}}}]},{frames:[{...state,at:26,inert:true}]}])assert.equal(keyboardFirstPaint({...valid,...bad}).status,'blocked');
});
test('D3 parent Escape is blocked after failed ownership or hidden/inert/non-native parent despite stale presentation',()=>{
 const before=goodState(),after=goodClosed(),child={before,after,status:'collected',trustedInputObserved:true,ownership:true};assert(canSendParentEscape(child,after));
 for(const parent of [{hidden:true},{inert:true},{nativeOpen:false},{modal:false},{display:'none'},{visibility:'hidden'}]){const current={...after,parent:{...after.parent,...parent}};assert(!parentOwnedOpen(current));assert(!escapeOwnership(before,current,'child'));assert(!canSendParentEscape(child,current));}
 for(const c of [{...child,ownership:false},{...child,status:'blocked'},{...child,trustedInputObserved:false}])assert(!canSendParentEscape(c,after));
 assert(!canSendParentEscape(child,{...after,hash:''}));assert(!canSendParentEscape(child,{...after,focus:{control:'menuitem:4',inParent:true}}));
});
test('actual geometry helper scales client box consistently and intersects ancestor clipping',()=>{
 const menu={node:'menu',axisAligned:true,rect:{left:20,top:30,width:96,height:192},offsetWidth:100,offsetHeight:200,clientLeft:2,clientTop:2,clientWidth:96,clientHeight:196};
 const viewport={left:0,top:0,right:390,bottom:780};const measured=nativeClipGeometry(menu,[],viewport);assert.equal(measured.status,'measured-axis-aligned-intersection');assert.equal(measured.rect.left,21.92);assert.equal(measured.rect.right,114.08);assert.equal(measured.rect.bottom,220.07999999999998);
 const ancestor={...menu,node:'stage',rect:{left:0,top:0,width:150,height:150},offsetWidth:150,offsetHeight:150,clientLeft:0,clientTop:0,clientWidth:150,clientHeight:150,clipX:true,clipY:true};const clipped=nativeClipGeometry(menu,[ancestor],viewport);assert.equal(clipped.rect.bottom,150);const row={left:30,right:110,top:140,bottom:180,width:80,height:40};assert(rectInside(row,measured.rect));assert(!rectInside(row,clipped.rect));assert.equal(classifyObservation({last:{focused:true,rect:row},menuClip:clipped.rect,clipGeometry:clipped})[0].kind,'focused-last-row-outside-scroll-clip');
 for(const bad of [{...menu,axisAligned:false},{...menu,offsetWidth:0},{...menu,unsupportedClip:true}])assert.equal(nativeClipGeometry(bad,[],viewport).status,'blocked');assert.equal(nativeClipGeometry(menu,[{...ancestor,unsupportedClip:true,clipX:false,clipY:false}],viewport).status,'blocked');
});
test('strict identity parser never aliases scalar scale 11 or 111 with two or three identity tokens',()=>{
 for(const v of ['1','1 1','1 1 1','1.0','+1'])assert(identityValue('scale',v));
 for(const v of ['11','111','1,1','1 11','0','-1','NaN','Infinity','1e1','1 1 1 1'])assert(!identityValue('scale',v));
 assert(identityValue('transform','matrix(1, 0, 0, 1, 0, 0)'));assert(!identityValue('transform','matrix(1, 0, 0, 11, 0, 0)'));assert(!identityValue('transform','scale(11)'));assert(!identityValue('transform','translateX(1px)'));assert(!identityValue('transform','matrix(1,0,0,1,0)'));
 for(const v of ['11','111'])assert.equal(reducedMotionFindings([{animations:[{target:{id:'menu'},values:{scale:[v]},properties:['scale']}]}])[0].kind,'reduced-motion-nonidentity-keyframes');
});
test('post-JS bubble and native cancel dispatch never claim native default or settled completion',()=>{
 const state=goodState();for(const phase of ['document-bubble-after-production-js','dialog-lifecycle-dispatch']){const row=lifecycleObservation(phase,{type:'cancel',isTrusted:true},state);assert.equal(row.nativeDefaultMayStillBePending,true);assert.equal(row.settled,false);assert.equal(row.state.parent.nativeOpen,true);}
 const after=lifecycleObservation('next-raf-after-lifecycle',{type:'close',isTrusted:true},{...state,parent:{...state.parent,nativeOpen:false}});assert.equal(after.nativeDefaultMayStillBePending,false);assert.equal(after.settled,false);
});

test('real action collector completes only a correctly attributed trace with observed native settlement',async()=>{const run={id:'D1',actions:[],blocked:[]};const {settlement,...trace}=goodAction();const result=await collectNativeAction({run,name:trace.name,arm:async()=>({requestedAt:1}),input:async()=>{},settle:async()=>settlement,finish:async()=>trace,persist:()=>{}});assert.equal(result.status,'collected');assert.equal(run.blocked.length,0);assert.equal(actionCollectionIssues(result).length,0);});
test('production harness calls the tested collectors, ownership gate, geometry and lifecycle helpers',()=>{const s=readFileSync(join(dir,'transitions-library-menu-discovery.browser.mjs'),'utf8');for(const call of ['collectNativeAction({run','canSendParentEscape(child,preParent)','nativeClipGeometry.toString()','lifecycleObservation.toString()','makeBoundedFinalizer([','collectionSummary(run)'])assert(s.includes(call));assert(s.indexOf("const {chromium}=await import")>s.indexOf('async function execute()'));assert.match(s,/115_000/);assert.match(s,/if\(executionFinished\)clearTimeout\(hardStop\)/);assert.doesNotMatch(s,/menuClip:\{left:r.left\+menu.clientLeft/);});

test('native parent Escape cannot settle on the document bubble snapshot before native cancel/close',()=>{const action={name:'detail-parent-Escape',lifecycle:[]},closed={parent:{nativeOpen:false,modal:false}};assert(!nativeBoundaryReady(action,closed));const dispatched={...action,lifecycle:[{type:'cancel',trusted:true,phase:'dialog-lifecycle-dispatch'}]};assert(!nativeBoundaryReady(dispatched,{parent:{nativeOpen:true,modal:true}}));assert(nativeBoundaryReady(dispatched,closed));assert(!nativeBoundaryReady({...action,lifecycle:[{type:'keydown',trusted:true,phase:'document-bubble-after-production-js'}]},closed));assert(!nativeBoundaryReady({...action,lifecycle:[{type:'close',trusted:false,phase:'dialog-lifecycle-dispatch'}]},closed));assert(nativeBoundaryReady({name:'detail-child-Escape'},closed));});

test('exact listener costly-snapshot regression: click100, snapshot100→180, firstRAF196 is 96ms and blocked',()=>{
 let clock=99;
 const state={expanded:'true',inert:false,focus:{control:'menuitem:0'},first:{node:{control:'menuitem:0'},focused:true,color:'rgb(0,0,0)',chain:[layer()]}};
 const listeners=createClockedEventListeners({now:()=>clock,describe:target=>target,snapshot:()=>{clock+=80;return state;}});
 const key={type:'keydown',key:'Enter',isTrusted:true,target:{control:'menu-trigger'},timeStamp:99};
 const keyRow=listeners.capture(key);clock=100;
 const click={type:'click',detail:0,isTrusted:true,target:{control:'menu-trigger'},timeStamp:100};
 const clickRow=listeners.capture(click),accepted=listeners.accepted(click);
 assert.equal(accepted.at,100);assert.equal(accepted.eventAt,100);assert.equal(accepted.observerStartedAt,100);assert.equal(accepted.snapshotStartedAt,100);assert.equal(accepted.snapshotCompletedAt,180);
 const action={events:[keyRow,clickRow],accepted:[accepted],frames:[{...state,at:196,rafCallbackAt:196,rafTimestamp:195,snapshotStartedAt:196,snapshotCompletedAt:196}]};
 const result=keyboardFirstPaint(action);assert.equal(result.window.actualMs,96);assert.equal(result.status,'blocked');assert.equal(196-accepted.snapshotCompletedAt,16,'Old completion-as-input mistake would have looked in-window');
 assert.equal(timingWindow(196-inputEventBoundary(action,accepted).eventAt).status,'blocked','PNG timing uses the same original event boundary');
 assert.equal(keyboardFirstPaint({...action,accepted:[{...accepted,at:180}]}).window.actualMs,96,'Legacy at fields cannot replace the capture link');
});
test('exact lifecycle listeners retain event time while dispatch and later snapshots have independent clocks',()=>{
 let clock=200;const listeners=createClockedEventListeners({now:()=>clock,describe:target=>target,snapshot:()=>{clock+=80;return {parent:{nativeOpen:false}};}});
 const event={type:'close',isTrusted:true,target:{control:'parent-control'},timeStamp:200};const raw=listeners.capture(event),dispatch=listeners.lifecycle(event);clock=296;const later=listeners.later(event,295);
 assert.equal(raw.eventAt,200);assert.equal(dispatch.eventAt,200);assert.equal(dispatch.snapshotStartedAt,200);assert.equal(dispatch.snapshotCompletedAt,280);assert.equal(later.eventAt,200);assert.equal(later.observerStartedAt,296);assert.equal(later.snapshotStartedAt,296);assert.equal(later.snapshotCompletedAt,376);assert.equal(later.rafTimestamp,295);
});
test('missing or mismatched capture provenance cannot produce first-frame timing, and costly rAF measurement remains blocked',()=>{
 let clock=100;const state={expanded:'true',inert:false,focus:{control:'menuitem:0'},first:{node:{control:'menuitem:0'},focused:true,color:'rgb(0,0,0)',chain:[layer()]}};const listeners=createClockedEventListeners({now:()=>clock,describe:x=>x,snapshot:()=>state});
 const click={type:'click',detail:0,isTrusted:true,target:{control:'menu-trigger'},timeStamp:100};const unlinked=listeners.accepted(click);assert.equal(unlinked.clockStatus,'blocked-missing-capture-event');assert.equal(unlinked.eventAt,null);
 const raw=listeners.capture(click),accepted=listeners.accepted(click),action={events:[{type:'keydown',trusted:true,key:'Enter',target:{control:'menu-trigger'},at:99},raw],accepted:[accepted],frames:[{...state,at:116,rafCallbackAt:116,snapshotStartedAt:116,snapshotCompletedAt:196}]};
 assert.equal(keyboardFirstPaint(action).window.actualMs,16);assert.equal(keyboardFirstPaint(action).snapshotCompletionWindow.actualMs,96);assert.equal(keyboardFirstPaint(action).status,'blocked');
 assert.equal(inputEventBoundary(action,{...accepted,captureEventId:999}),null);assert.equal(inputEventBoundary(action,{...accepted,eventAt:180}),null);
});
test('native harness uses exact clocked listeners and original linked event time for PNG brackets',()=>{
 const s=readFileSync(join(dir,'transitions-library-menu-discovery.browser.mjs'),'utf8');for(const call of ['createClockedEventListeners.toString()','eventListeners.capture(e)','eventListeners.accepted(e)','eventListeners.lifecycle(e)','eventListeners.later(e,rafTimestamp)','window.__menuInputEventBoundary(action,accepted)','inputBoundary?.eventAt','entry.before?.snapshotStartedAt','entry.after?.snapshotCompletedAt'])assert(s.includes(call));assert(!s.includes("at:performance.now(),target:identify(e.target),state:state"));
});
