// Execute the actual browser observer after the complete production document handler.
// Trusted-event flags and native callback checkpoints are modeled here, not real input.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const browserFile=path.join(__dirname,'transitions-library-dialog.browser.mjs'),browser=fs.readFileSync(browserFile,'utf8');
const fixtureFile=fs.readFileSync(path.join(__dirname,'transitions-library-focus-escape.test.cjs'),'utf8'),runtime=path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js');
const scope={require,__dirname,process:{argv:['node','observer-test',runtime]},console};vm.runInNewContext(fixtureFile.slice(0,fixtureFile.indexOf('async function test('))+'\nthis.makeFixture=fixture;',scope);
const start=browser.indexOf('()=>{window.__pointerExit=null;'),end=browser.indexOf("});await page.locator('#dialog-1 [autofocus]').click()",start);assert(start>=0&&end>start,'Actual pointer-exit observer missing');
const callback=browser.slice(start,end+1),assertion=browser.slice(browser.indexOf('function assertPointerExit('),browser.indexOf('async function earlyOpen('));assert(assertion.startsWith('function assertPointerExit('));
async function fixture(){const f=scope.makeFixture(false),trigger=new f.E('button'),dialog=new f.E('dialog'),cancel=new f.E('button'),other=new f.E('button');dialog.dataset.st='modal';cancel.setAttribute('autofocus','');cancel.setAttribute('data-st-close','');cancel.textContent='Cancel';dialog.append(cancel);f.host.append(trigger,dialog,other);f.S.init(dialog);trigger.focus();f.S.open(dialog,trigger);await f.settle();const oldQuery=f.doc.querySelector.bind(f.doc);f.doc.querySelector=s=>s==='#dialog-1'?dialog:oldQuery(s);let at=0;const window={__dialogInspect:()=>({at:++at,open:dialog.open,modal:dialog.modal,inert:dialog.inert,expanded:trigger.getAttribute('aria-expanded'),reduce:false,dialog:{opacity:1},animations:f.animations.filter(a=>!a.cancelled).map(a=>({pseudo:a.options.pseudoElement||null,properties:a.frames.some(k=>'transform'in k)?['transform']:['opacity']}))})},context={window,document:f.doc,queueMicrotask,assert};vm.runInNewContext('('+callback+')();'+browser.slice(browser.indexOf('function assertInstantAnimations('),browser.indexOf('function inspect('))+assertion+'\nthis.validate=assertPointerExit;',context);return {...f,trigger,dialog,cancel,other,window,validate:context.validate};}
const results=[];async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split('\n')[0]});}}
(async()=>{
for(const descendant of [false,true])await test(`filtered document observer captures ${descendant?'descendant':'button'} target only after delegated close`,async()=>{const f=await fixture();const count=f.doc.handlers.click.length;const unrelated=new f.Event('click',{target:f.other,currentTarget:f.doc,isTrusted:true,detail:1});f.doc.dispatchEvent(unrelated);assert.equal(f.window.__pointerExit,null,'Unrelated clicks cannot consume the filtered observer');assert.equal(f.doc.handlers.click.length,count);let target=f.cancel;if(descendant){target=new f.E('span');f.cancel.append(target);}const click=new f.Event('click',{target,currentTarget:f.doc,isTrusted:true,detail:1});for(const fn of target.handlers.click||[])fn(click);await Promise.resolve();assert.equal(f.window.__pointerExit,null,'A target callback checkpoint must not claim post-document state');f.doc.dispatchEvent(click);const captured=f.window.__pointerExit;assert(captured.modal&&captured.open&&captured.inert);assert.equal(captured.expanded,'false');assert(captured.currentTargetIsDocument);assert.equal(captured.observedAt,'document-bubble');assert.equal(captured.actualTarget.tag,descendant?'SPAN':'BUTTON');assert.equal(f.doc.handlers.click.length,count-1,'Matched observer cleans up');f.key(f.doc.body,'Escape',{isTrusted:true});f.key(f.doc.body,'Escape',{isTrusted:true});const exit={start:captured,keys:f.window.__pointerEscape};f.validate(exit);for(const mutation of [x=>x.start.inert=false,x=>x.start.trusted=false,x=>x.start.detail=0,x=>x.start.currentTargetIsDocument=false,x=>x.keys[1].open=false]){const bad=JSON.parse(JSON.stringify(exit));mutation(bad);assert.throws(()=>f.validate(bad),'Missed or invalid pointer windows must not pass');}await f.settle();assert(!f.dialog.open);});
await test('an explicitly missed native outgoing window is rejected, not skipped',async()=>{const f=await fixture(),click=new f.Event('click',{target:f.cancel,currentTarget:f.doc,isTrusted:true,detail:1});f.doc.dispatchEvent(click);await f.settle();f.key(f.doc.body,'Escape',{isTrusted:true});f.key(f.doc.body,'Escape',{isTrusted:true});assert.throws(()=>f.validate({start:f.window.__pointerExit,keys:f.window.__pointerEscape}));});
const report={runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync(runtime)).digest('hex'),harnessSha256:crypto.createHash('sha256').update(browser).digest('hex'),scope:'Actual harness observer/assertion plus complete production runtime in explicit modeled event ordering; synthetic trust flags, not browser/native acceptance',passed:results.filter(x=>x.pass).length,total:results.length,results};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})();
