// Native-browser Close attachment and input regression. Initial synchronous observation
// is retained separately; assertions use RAF samples and actual current paint geometry.
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const arg=(name,fallback)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1];};
const runtime=arg('--playwright');if(!runtime)throw new Error('Pass --playwright /existing/playwright/index.mjs');
const {chromium}=await import(pathToFileURL(resolve(runtime)).href);
const gallery=resolve(arg('--gallery',fileURLToPath(new URL('../skills/seenry/assets/components/transitions/gallery.html',import.meta.url)))),out=resolve(arg('--out','close-attachment-browser-results'));mkdirSync(out,{recursive:true});
const videoOnly=arg('--video-only','false')==='true';
const recordVideo=videoOnly||arg('--record-video','false')==='true';
const browser=await chromium.launch({headless:true,...(process.env.SEENRY_CHROME_PATH?{executablePath:process.env.SEENRY_CHROME_PATH}:{})});
const sha=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
// Use the visible native label. The transparent input is beneath its visual track.
// A one-time bounded old-path probe preserves the actionability diagnosis separately.
async function enableBlur(page, probeDirect = false) {
 const initial = await page.locator('#blur-toggle').isChecked();
 await page.evaluate(()=>{window.__blurInputs=[];document.querySelector('#blur-toggle').addEventListener('change',e=>window.__blurInputs.push({trusted:e.isTrusted,checked:e.target.checked,at:performance.now()}));});
 let directProbe=null;
 if(probeDirect&&!initial){try{await page.locator('#blur-toggle').check({timeout:1000});directProbe={status:'succeeded'};}catch(e){directProbe={status:'blocked',error:e.message};}}
 if(!await page.locator('#blur-toggle').isChecked())await page.locator('label.blur-switch').click();
 await page.waitForFunction(()=>document.querySelector('#blur-toggle').checked&&document.documentElement.hasAttribute('data-st-blur'));
 const observed=await page.evaluate(()=>({checked:document.querySelector('#blur-toggle').checked,enabled:document.documentElement.hasAttribute('data-st-blur'),events:window.__blurInputs}));
 assert(observed.checked&&observed.enabled,'Visible Blur control must enable the actual product state');
 if(!initial)assert(observed.events.some(e=>e.trusted&&e.checked),'Blur must be enabled through trusted native input');
 return {initial,directProbe,...observed};
}
const profiles=[{label:'390-dark-native',viewport:390,index:1,theme:'dark',spaced:false},{label:'390-light-spaced',viewport:390,index:1,theme:'light',spaced:true},{label:'385-content-light-spaced',viewport:1440,contentWidth:385,index:0,theme:'light',spaced:true}];
const report={mode:videoOnly?'representative-video-only':'native-close-assertions',browser:browser.version(),source:{html:sha(gallery),runtime:sha(join(dirname(gallery),'seenry-transitions.js')),css:sha(join(dirname(gallery),'seenry-transitions.css')),galleryJS:sha(join(dirname(gallery),'gallery.js'))},scope:'Actual Blur-on state, trusted opening click, timed API reversals, RAF geometry, native Escape/Enter and pointer Close during travel. Native viewport390 plus explicit385px component-width reproduction; not physical-touch coverage.',runs:[]};
const saveReport=()=>writeFileSync(join(out,'results.json'),JSON.stringify(report,null,2)+'\n');
saveReport();
const spacing=':root:not(#seenry-text-spacing-test) *{line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}:root:not(#seenry-text-spacing-test) p{margin-block-end:2em!important}';
try{
 if(!videoOnly)for(const profile of profiles)for(const delay of [50,100,150]){
  const context=await browser.newContext({viewport:{width:profile.viewport,height:1000},colorScheme:profile.theme,reducedMotion:'no-preference',serviceWorkers:'block',acceptDownloads:false}),page=await context.newPage(),run={...profile,delay,status:'running'},errors=[];report.runs.push(run);
  const phase=name=>{run.phase=name;saveReport();};phase('create-context');page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,route=>route.abort());
  try{
   phase('navigate');await page.goto(pathToFileURL(gallery).href);phase('fonts');await page.evaluate(()=>document.fonts.ready);phase('enable-blur');run.blurInput=await enableBlur(page,report.runs.length===1);phase('prepare-profile');if(profile.spaced)await page.addStyleTag({content:spacing});
   if(profile.contentWidth)await page.addStyleTag({content:`.grid{display:block!important}.card:not([data-key="expand"]){display:none!important}.card[data-key="expand"]{width:${profile.contentWidth+60}px!important}`});
   phase('locate-card');const card=page.locator('[data-key="expand"]'),source=card.locator('.cover-card').nth(profile.index),close=card.locator('[data-st-close]');await card.scrollIntoViewIfNeeded();await page.waitForTimeout(300);
   run.layout=await page.evaluate(({index,delay})=>{
    const card=document.querySelector('[data-key="expand"]'),source=card.querySelectorAll('.cover-card')[index],detail=card.querySelector('[data-st="expand"]'),surface=detail.querySelector('.expand-surface'),close=surface.querySelector('[data-st-close]'),title=surface.querySelector('[data-st-shared-text]'),meta=[...surface.querySelectorAll('[data-st-shared="meta"]')].find(e=>!e.closest('[data-st-ghost]'));
    const backingAlpha=color=>{if(color==='transparent')return 0;const slash=/\/\s*([\d.]+)(%)?\s*\)/.exec(color);if(slash)return Number(slash[1])/(slash[2]?100:1);const rgba=/^rgba\([^)]*,\s*([\d.]+)\)/.exec(color);return rgba?Number(rgba[1]):1;};
    const state=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();let opacity=1,display=true;for(let n=e;n;n=n.parentElement){const c=getComputedStyle(n);opacity*=Number(c.opacity);if(n.hidden||c.display==='none')display=false;}return {rect:r.toJSON(),visibility:s.visibility,display:s.display,opacity,effectiveDisplay:display,painted:display&&s.visibility==='visible'&&opacity>.01&&r.width>0&&r.height>0,transform:s.transform,translate:s.translate,filter:s.filter,ancestorFilters:[...function*(n){for(let p=n.parentElement;p;p=p.parentElement)yield p;}(e)].map(n=>({tag:n.tagName,id:n.id||null,filter:getComputedStyle(n).filter})),clipPath:s.clipPath,overflow:s.overflow,layoutWidth:e.offsetWidth,layoutHeight:e.offsetHeight,focusVisible:e.matches(':focus-visible'),hovered:e.matches(':hover'),backgroundColor:s.backgroundColor,backgroundAlpha:backingAlpha(s.backgroundColor),color:s.color,zIndex:s.zIndex,outlineColor:s.outlineColor,outlineAlpha:backingAlpha(s.outlineColor),outlineWidth:s.outlineWidth,outlineStyle:s.outlineStyle,focusToken:s.getPropertyValue('--focus-ring').trim()};};
    const text=e=>{const range=document.createRange();range.selectNodeContents(e);const glyphs=[...range.getClientRects()].filter(r=>r.width>0&&r.height>0).map(r=>r.toJSON()),s=state(e);return {...s,painted:s.painted&&glyphs.length>0,glyphs,text:e.textContent.trim()};};
    window.__closeRun={trace:[],actions:[]};
    window.__closeFrame=()=>{
     const paint=surface.querySelector('.st-expand-paint'),r=(paint||surface).getBoundingClientRect(),m=paint&&/inset\(([^)]*)\)/.exec(getComputedStyle(paint).clipPath);let a=m?m[1].split('round')[0].trim().split(/\s+/).map(parseFloat):[0];a=[a[0],a[1]??a[0],a[2]??a[0],a[3]??a[1]??a[0]];
     const c=close.getBoundingClientRect(),hit=document.elementFromPoint(c.left+c.width/2,c.top+c.height/2),closeOwnsCenter=!!hit&&(hit===close||close.contains(hit));
     return {blurEnabled:document.documentElement.hasAttribute('data-st-blur'),shell:{left:r.left+a[3],top:r.top+a[0],right:r.right-a[1],bottom:r.bottom-a[2]},close:{...state(close),ownsCenter:closeOwnsCenter,centerHit:hit?{tag:hit.tagName,id:hit.id||null,shared:hit.getAttribute('data-st-shared'),ghost:hit.hasAttribute('data-st-ghost')}:null},focusedClose:document.activeElement===close,open:detail.dataset.stOpen,closing:detail.dataset.stClosing||null,inert:detail.inert,title:text(title),ghosts:[...surface.querySelectorAll('[data-st-ghost][data-st-shared="title"]')].map(text),meta:meta?text(meta):null,metaGhosts:[...surface.querySelectorAll('[data-st-ghost][data-st-shared="meta"]')].map(text),details:[...surface.querySelectorAll('[data-st-expand-content]')].map(e=>({...text(e),layoutRangesOnly:true,clipAncestors:[e,...function*(n){for(let p=n.parentElement;p;p=p.parentElement)yield p;}(e)].map(n=>({tag:n.tagName,clipPath:getComputedStyle(n).clipPath,overflow:getComputedStyle(n).overflow,rect:n.getBoundingClientRect().toJSON()})).filter(n=>n.clipPath!=='none'||n.overflow!=='visible'),animations:e.getAnimations().map(a=>({type:a.constructor.name,playState:a.playState,currentTime:a.currentTime,duration:a.effect.getComputedTiming().duration,properties:[...new Set(a.effect.getKeyframes().flatMap(k=>Object.keys(k).filter(p=>!['offset','computedOffset','easing','composite'].includes(p))))]}))}))};
    };
    source.addEventListener('click',()=>queueMicrotask(()=>{
     const start=performance.now();window.__closeRun.initial={at:performance.now()-start,...window.__closeFrame()};window.__closeRun.actions.push({action:'trusted-open',at:0});
     const sample=()=>{const at=performance.now()-start;window.__closeRun.trace.push({at,...window.__closeFrame()});if(at<delay*2+600)requestAnimationFrame(sample);};requestAnimationFrame(sample);
     setTimeout(()=>{SeenryTransitions.collapse(detail);window.__closeRun.actions.push({action:'api-close',at:performance.now()-start});},delay);
     setTimeout(()=>{SeenryTransitions.expand(source,detail);window.__closeRun.actions.push({action:'api-reopen',at:performance.now()-start});},delay*2);
    }),{once:true});
    return {blurEnabled:document.documentElement.hasAttribute('data-st-blur'),sourceText:source.querySelector('b').textContent.trim(),sourceMeta:source.querySelector('[data-st-shared="meta"]')?.textContent.trim()||null,source:source.getBoundingClientRect().toJSON(),closeName:close.getAttribute('aria-label')};
   },{index:profile.index,delay});
   assert.equal(run.layout.blurEnabled,true,'Focused Blur-on regression must enable the actual opt-in state');
   phase('trusted-open-and-api-reversals');await source.click();await page.waitForTimeout(delay*2+60);run.movingFrame=`${profile.label}-${delay}-moving.png`;await card.screenshot({path:join(out,run.movingFrame),animations:'allow'});await page.waitForTimeout(750);
   Object.assign(run,await page.evaluate(()=>window.__closeRun));run.settled=await page.evaluate(()=>window.__closeFrame());run.errors=errors;
   assert.equal(run.layout.closeName,'Close album');assert(run.trace.length>=15,'RAF evidence missing');let paintedCloseFrames=0;
   const inside=(r,s)=>r.left>=s.left-.15&&r.top>=s.top-.15&&r.right<=s.right+.15&&r.bottom<=s.bottom+.15;
   for(const row of run.trace){assert.equal(row.blurEnabled,true,'Card flow must not disable Blur to pass');
    const titles=[...row.ghosts.filter(t=>t.painted),...(row.title.painted?[row.title]:[])];assert.equal(titles.length,1,`Exactly one title required at${row.at}ms`);assert.equal(titles[0].text,run.layout.sourceText);
    if(row.close.painted){paintedCloseFrames++;assert(inside(row.close.rect,row.shell),`Painted Close escapes shell at${row.at}ms`);assert(row.close.layoutWidth>=(profile.viewport===390?44:32));assert(row.close.layoutHeight>=(profile.viewport===390?44:32));}
   }
   assert(paintedCloseFrames>5,'Visible Close evidence missing');assert(run.settled.close.painted&&inside(run.settled.close.rect,run.settled.shell));assert(run.settled.focusedClose&&!run.settled.inert);assert.equal(run.settled.ghosts.length,0);
   // Moving metadata/details are diagnostic: Range bounds alone do not describe intentionally clipped ink.
   if(run.layout.sourceMeta){assert(run.settled.meta?.painted,'Settled shared metadata must be visible');assert.equal(run.settled.meta.text,run.layout.sourceMeta);assert.equal(run.settled.metaGhosts.length,0);}assert(run.settled.details.length>0&&run.settled.details.every(d=>d.painted&&d.text),'Settled details must have visible content');
   // Keep actual browser keyboard/focus behavior: Escape returns to the trigger; Enter reopens.
   phase('escape-recovery');await page.keyboard.press('Escape');await page.waitForTimeout(550);assert.equal(await source.evaluate(e=>document.activeElement===e),true,'Escape must restore trigger focus');assert.equal(await card.locator('[data-st="expand"]').getAttribute('data-st-open'),'false');
   await source.evaluate(e=>{e.addEventListener('click',()=>{
    window.__movingCloseOpenAt=performance.now();window.__keyboardCloseTrace=[];
    queueMicrotask(()=>{window.__keyboardCloseInitial={at:performance.now()-window.__movingCloseOpenAt,...window.__closeFrame()};const sample=()=>{const at=performance.now()-window.__movingCloseOpenAt;window.__keyboardCloseTrace.push({at,...window.__closeFrame()});if(at<400)requestAnimationFrame(sample);};requestAnimationFrame(sample);});
   },{once:true});});
   await close.evaluate(e=>{window.__movingCloseClick=null;e.addEventListener('click',event=>{window.__movingCloseClick={trusted:event.isTrusted,targetIsClose:e===event.target||e.contains(event.target),target:event.target.tagName,at:performance.now()-window.__movingCloseOpenAt,openSpringDuration:SeenryTransitions.spring('expand').duration,positionAnimations:e.getAnimations().filter(a=>a.effect.getKeyframes().some(f=>'translate'in f)).map(a=>({playState:a.playState,currentTime:a.currentTime,duration:a.effect.getComputedTiming().duration}))};},{capture:true,once:true});});
   phase('keyboard-moving-close');await page.keyboard.press('Enter');await page.waitForTimeout(205);const during=await page.evaluate(()=>window.__closeFrame());assert(during.close.painted&&inside(during.close.rect,during.shell),'Moving Close must be visible and attached when clicked');
   await page.mouse.click((during.close.rect.left+during.close.rect.right)/2,(during.close.rect.top+during.close.rect.bottom)/2);run.movingCloseInput=await page.evaluate(()=>window.__movingCloseClick);assert(run.movingCloseInput?.trusted&&run.movingCloseInput.targetIsClose,'Trusted click must actually target Close; outside dismissal cannot count');assert(run.movingCloseInput.at<run.movingCloseInput.openSpringDuration,'Trusted Close input must precede open spring settle');assert(run.movingCloseInput.positionAnimations.some(a=>a.playState==='running'&&a.currentTime<a.duration),'Click must occur before the attachment spring settles');await page.waitForTimeout(550);assert.equal(await card.locator('[data-st="expand"]').getAttribute('data-st-open'),'false','Moving Close must remain clickable');assert.equal(await source.evaluate(e=>document.activeElement===e),true,'Pointer Close must restore trigger focus');
   run.keyboardCloseInitial=await page.evaluate(()=>window.__keyboardCloseInitial);run.keyboardCloseTrace=await page.evaluate(()=>window.__keyboardCloseTrace);
   const keyboardOpenFrames=run.keyboardCloseTrace.filter(row=>row.open==='true'&&!row.closing);
   run.keyboardMissingFocusFindings=keyboardOpenFrames.filter(row=>!row.focusedClose||!row.close.focusVisible);
   run.keyboardHitFindings=keyboardOpenFrames.filter(row=>!row.close.ownsCenter);
   run.keyboardFocusFindings=run.keyboardCloseTrace.filter(row=>row.open==='true'&&!row.closing&&row.focusedClose&&row.close.focusVisible&&(!row.close.painted||row.close.opacity<.99));
   assert(keyboardOpenFrames.length>2,'Keyboard test must capture actual open RAF frames');
   for(const row of run.keyboardCloseTrace.filter(row=>row.open==='true'&&!row.closing)){assert.equal(row.blurEnabled,true,'Keyboard focus must not disable the global Blur option');assert(['none','blur(0px)'].includes(row.close.filter)&&row.close.ancestorFilters.every(a=>['none','blur(0px)'].includes(a.filter)),'Keyboard Close must be sharp, without a surviving owned blur');assert(row.close.outlineStyle==='solid'&&parseFloat(row.close.outlineWidth)>=2&&row.close.focusToken,'Keyboard Close must have a resolved visible focus outline');assert(row.close.outlineAlpha>0,'Focus outline must not be transparent');}
   run.geometryAndInputPassed=true;
   // Separate pixel pass: screenshots must not consume the trusted moving-click deadline.
   await source.evaluate(e=>{window.__keyboardPixelFirstRAF=null;e.addEventListener('click',()=>{window.__keyboardPixelOpenAt=performance.now();requestAnimationFrame(()=>window.__keyboardPixelFirstRAF={at:performance.now()-window.__keyboardPixelOpenAt,...window.__closeFrame()});},{once:true});});
   phase('keyboard-early-pixel');await page.keyboard.press('Enter');await page.waitForTimeout(18);run.keyboardFrame={file:`${profile.label}-${delay}-keyboard-early.png`,requestAt:await page.evaluate(()=>performance.now()-window.__keyboardPixelOpenAt)};await card.screenshot({path:join(out,run.keyboardFrame.file),animations:'allow'});run.keyboardFrame.completedAt=await page.evaluate(()=>performance.now()-window.__keyboardPixelOpenAt);run.keyboardPixelFirstRAF=await page.evaluate(()=>window.__keyboardPixelFirstRAF);
   phase('focused-hover');await page.waitForTimeout(450);const settledForHover=await page.evaluate(()=>window.__closeFrame());await page.mouse.move((settledForHover.close.rect.left+settledForHover.close.rect.right)/2,(settledForHover.close.rect.top+settledForHover.close.rect.bottom)/2);await page.waitForTimeout(110);run.keyboardHover=await page.evaluate(()=>window.__closeFrame());assert(run.keyboardHover.focusedClose&&run.keyboardHover.close.focusVisible&&run.keyboardHover.close.hovered,'Hover check must retain native keyboard focus on Close');assert(run.keyboardHover.close.backgroundAlpha>=.99,'Focused hover backing must remain opaque over artwork');run.keyboardHoverFrame=`${profile.label}-${delay}-keyboard-hover.png`;await card.screenshot({path:join(out,run.keyboardHoverFrame),animations:'allow'});
   await page.keyboard.press('Escape');await page.waitForTimeout(550);assert.equal(await source.evaluate(e=>document.activeElement===e),true,'Pixel pass Escape must restore trigger focus');
   assert.equal(await close.evaluate(e=>e.style.translate),'','Completed close must restore authored individual translate');assert.equal(errors.length,0);
   assert.equal(run.keyboardMissingFocusFindings.length,0,'Close must own native visible focus from the first open keyboard RAF');assert.equal(run.keyboardFocusFindings.length,0,'Keyboard-focused Close fades or disappears during the early RAF frames');assert.equal(run.keyboardHitFindings.length,0,'Keyboard-focused Close loses center hit ownership to another element');run.status='passed';
  }catch(e){run.status='failed';run.error=e.stack||e.message;run.errors=errors;console.error(JSON.stringify({profile:profile.label,delay,phase:run.phase,error:run.error}));saveReport();await page.screenshot({path:join(out,`${profile.label}-${delay}-FAILED.png`)}).catch(()=>{});}
  finally{saveReport();await context.close();}
 }
 // Optional single continuous recording runs in its own context after the timing-critical
 // assertions above. It uses the existing Playwright video capability; no dependencies install here.
 if(recordVideo){
  report.video={status:'running',kind:'continuous Chromium recording',viewport:{width:390,height:780},motion:'no-preference',theme:'light',blur:true,source:report.source,browser:report.browser,scope:'One representative flow: trusted pointer open, timed API close/reopen, native Escape/Enter, then trusted settled Close. No screenshot or pause calls in this recording context.'};
  let context,video;
  try{
   context=await browser.newContext({viewport:{width:390,height:780},colorScheme:'light',reducedMotion:'no-preference',recordVideo:{dir:join(out,'video-raw'),size:{width:390,height:780}},serviceWorkers:'block',acceptDownloads:false});
   const page=await context.newPage(),errors=[];video=page.video();page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto(pathToFileURL(gallery).href);await page.evaluate(()=>document.fonts.ready);
   report.video.phase='enable-blur';saveReport();report.video.blurInput=await enableBlur(page);report.video.phase='recording';saveReport();await page.locator('.search-box input').fill('Card expand');await page.waitForTimeout(500);const card=page.locator('[data-key="expand"]'),source=card.locator('#expand-src');await card.scrollIntoViewIfNeeded();
   await page.evaluate(()=>{window.__cardVideoStart=performance.now();window.__cardVideoActions=[];const log=(kind,e)=>window.__cardVideoActions.push({kind,at:performance.now()-window.__cardVideoStart,isTrusted:e?.isTrusted??null});document.querySelector('#expand-src').addEventListener('click',e=>log(e.detail?'pointer-open':'keyboard-open',e));document.querySelector('#expand-1 [data-st-close]').addEventListener('click',e=>log('pointer-close',e));document.addEventListener('keydown',e=>{if(e.key==='Escape')log('keyboard-escape',e);});});
   await source.click();await page.waitForTimeout(70);await page.evaluate(()=>{const detail=document.querySelector('#expand-1'),paint=detail.querySelector('.st-expand-paint'),animations=(paint?.getAnimations()||[]).map(a=>({playState:a.playState,currentTime:a.currentTime,duration:a.effect.getComputedTiming().duration,clip:a.effect.getKeyframes().some(k=>'clipPath'in k)})),valid=detail.dataset.stOpen==='true'&&animations.some(a=>a.clip&&a.playState==='running'&&a.currentTime>0&&a.currentTime<a.duration);window.__cardVideoActions.push({kind:'api-close',at:performance.now()-window.__cardVideoStart,precondition:{open:detail.dataset.stOpen,animations,valid}});if(!valid)throw Error('Video precondition: opening shell must still be moving before close');SeenryTransitions.collapse(detail);});await page.waitForTimeout(70);await page.evaluate(()=>{const detail=document.querySelector('#expand-1'),paint=detail.querySelector('.st-expand-paint'),animations=(paint?.getAnimations()||[]).map(a=>({playState:a.playState,currentTime:a.currentTime,duration:a.effect.getComputedTiming().duration,clip:a.effect.getKeyframes().some(k=>'clipPath'in k)})),valid=detail.dataset.stClosing==='true'&&animations.some(a=>a.clip&&a.playState==='running'&&a.currentTime>0&&a.currentTime<a.duration);window.__cardVideoActions.push({kind:'api-reopen',at:performance.now()-window.__cardVideoStart,precondition:{closing:detail.dataset.stClosing,animations,valid}});if(!valid)throw Error('Video precondition: closing shell must still be moving before reopen');SeenryTransitions.expand(document.querySelector('#expand-src'),detail);});await page.waitForTimeout(650);
   await page.keyboard.press('Escape');await page.waitForTimeout(600);assert(await source.evaluate(e=>document.activeElement===e));await page.keyboard.press('Enter');await page.waitForTimeout(650);await card.locator('[data-st-close]').click();await page.waitForTimeout(600);
   report.video.actions=await page.evaluate(()=>window.__cardVideoActions);assert(report.video.actions.some(a=>a.kind==='pointer-open'&&a.isTrusted));assert(report.video.actions.some(a=>a.kind==='keyboard-open'&&a.isTrusted));assert(report.video.actions.some(a=>a.kind==='pointer-close'&&a.isTrusted));assert.equal(await card.locator('[data-st="expand"]').getAttribute('data-st-open'),'false');assert(await source.evaluate(e=>document.activeElement===e));assert.equal(errors.length,0);report.video.errors=errors;
   assert(video,'Existing Playwright environment did not provide video');await context.close();context=null;report.video.file='390-card-representative.webm';await video.saveAs(join(out,report.video.file));report.video.bytes=readFileSync(join(out,report.video.file)).length;report.video.sha256=sha(join(out,report.video.file));assert(report.video.bytes>0);report.video.status='recorded';
  }catch(e){report.video.status='blocked';report.video.error=e.stack||e.message;console.error(JSON.stringify({video:'blocked',phase:report.video.phase,error:report.video.error}));process.exitCode=1;}finally{
   await context?.close();
   // A failed input/precondition still has useful real recording bytes; never call it a passing flow.
   if(video&&!report.video.file){try{const file='390-card-attempt.webm';await video.saveAs(join(out,file));report.video.file=file;report.video.bytes=readFileSync(join(out,file)).length;report.video.sha256=sha(join(out,file));}catch(e){report.video.captureError=e.message;process.exitCode=1;}}
   saveReport();
  }
 }
}finally{await browser.close();writeFileSync(join(out,'results.json'),JSON.stringify(report,null,2)+'\n');}
if(report.video)console.log(`Representative video: ${report.video.status}${report.video.error?' — '+report.video.error:''}`);
const failed=report.runs.filter(r=>r.status!=='passed');if(videoOnly)console.log('Representative video-only invocation; Close assertions are in the separate native test step');else console.log(`${report.runs.length-failed.length}/${report.runs.length} Close attachment browser cases passed`);if(failed.length){console.log(failed.map(r=>({label:r.label,delay:r.delay,error:r.error})));process.exitCode=1;}
