// Executes exported guards and the exact in-page settlement closure against models.
// These tests are source-only; synthetic trusted flags do not constitute native evidence.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {test} from 'node:test';
import {finalizeSupplementCase,finalizeSupplementReport,reconcileSupplementCase,fixturePins,spacingCSS,appendBounded,boundedFontsReady,startPerformanceProbe,collectPerformanceFlow,opaqueComputedColor,within,scale97,assertSettlement,assertControl,assertTrustedSequence,assertClosedOutcome,assertSpacing,assertZoom200} from './transitions-library-dialog-supplement-helpers.mjs';
const box=(x=0,y=0,width=44,height=44)=>({x,y,left:x,top:y,right:x+width,bottom:y+height,width,height});
const paint=(name,x)=>({identity:name,text:name,connected:true,enabled:true,hitOwned:true,rect:box(x,120,100,44),textRects:[box(x+10,132,75,20)],chain:[{opacity:1,filter:'none',visibility:'visible',display:'block'}],active:false,hover:false,focused:false,focusVisible:false,transform:'none',outlineWidth:'0px',outlineStyle:'none',outlineColor:'rgb(0, 80, 200)',fontSize:'16px',lineHeight:'24px',letterSpacing:'1.92px',wordSpacing:'2.56px'});
function state(){const controls={Invoker:paint('Invoker',20),Cancel:paint('Cancel',24),Delete:paint('Delete',150)};return {open:true,modal:true,inert:false,expanded:'true',focus:'Cancel',viewport:box(0,0,320,780),pointer:{fine:true,coarse:false,hover:true},dialog:{rect:box(16,40,288,400)},controls,heading:{...paint('heading',30),textRects:[box(30,70,200,24)]},description:{...paint('description',30),textRects:[box(30,98,240,20)],marginBlockEnd:'32px'}};}
const copy=v=>structuredClone(v);
const settled=()=>({status:'settled',quietFrames:2,quietRAFAt:[16,32],startedAt:0,finishedAt:200,timeoutMs:1800,jobs:[{owner:'Cancel',properties:['transform'],outcome:'finished',pending:false,playState:'finished',duration:100,endTime:100}],afterJobs:[]});
test('fixture pins are exact and spacing contains all four requested properties',()=>{assert.equal(Object.keys(fixturePins).length,4);assert(Object.values(fixturePins).every(s=>/^[0-9a-f]{64}$/.test(s)));for(const term of ['line-height:1.5','margin-block-end:2em','letter-spacing:.12em','word-spacing:.16em'])assert(spacingCSS.includes(term));});
test('native ownership and actual held scale are affirmative guards',()=>{const s=state();assertControl(s,'Cancel','rest');s.controls.Cancel.hover=true;assertControl(s,'Cancel','hover');Object.assign(s.controls.Cancel,{active:true,focused:true,transform:'matrix(0.97, 0, 0, 0.97, 0, 0)'});assertControl(s,'Cancel','held');assert(scale97('matrix(0.97,0,0,0.97,0,0)'));assert(!scale97('matrix(.97,,0,.97,0,0)'));assert(!scale97('matrix(.98,0,0,.98,0,0)'));assert(!within(box(0,0,0,44),box()));});
for(const [name,mutate] of [
 ['wrong identity',s=>s.controls.Cancel.identity='Delete'],['untrusted hit owner',s=>s.controls.Cancel.hitOwned=false],['inactive held',s=>s.controls.Cancel.active=false],['unfocused held',s=>s.controls.Cancel.focused=false],['still progressing transform',s=>s.controls.Cancel.transform='matrix(.99,0,0,.99,0,0)'],['hidden ancestor',s=>s.controls.Cancel.chain[0].display='none'],['translucent ancestor',s=>s.controls.Cancel.chain[0].opacity=.99],['wrong native modal owner',s=>s.modal=false],['inert modal',s=>s.inert=true],['offscreen',s=>s.controls.Cancel.rect=box(-200,120,100,44)],['clipped label',s=>s.controls.Cancel.textRects=[box(0,0,500,20)]],['emulated coarse mislabeled fine',s=>s.pointer.coarse=true],['disabled control',s=>s.controls.Cancel.enabled=false],
])test('reject '+name,()=>{const s=state();Object.assign(s.controls.Cancel,{active:true,hover:true,focused:true,transform:'matrix(.97,0,0,.97,0,0)'});mutate(s);assert.throws(()=>assertControl(s,'Cancel','held'));});
test('keyboard focus checks actual focus-visible paint',()=>{const s=state(),c=s.controls.Cancel;Object.assign(c,{focused:true,focusVisible:true,outlineWidth:'2px',outlineStyle:'solid'});assertControl(s,'Cancel','keyboard-focus');for(const mutate of [c=>c.focusVisible=false,c=>c.outlineWidth='0px',c=>c.focused=false]){const bad=copy(s);mutate(bad.controls.Cancel);assert.throws(()=>assertControl(bad,'Cancel','keyboard-focus'));}});
test('hover movement cannot masquerade as ordinary hover',()=>{const s=state();Object.assign(s.controls.Cancel,{hover:true,transform:'matrix(1.01,0,0,1.01,0,0)'});assert.throws(()=>assertControl(s,'Cancel','hover'));});
test('settlement permits finished native owner only',()=>assertSettlement(settled()));
for(const [name,mutate] of [['timeout',r=>r.status='failed'],['one quiet frame',r=>r.quietFrames=1],['negative time',r=>r.finishedAt=-1],['at deadline',r=>r.finishedAt=1800],['cancellation',r=>r.jobs[0].outcome='cancelled'],['pending job',r=>r.jobs[0].pending=true],['running job',r=>r.jobs[0].playState='running'],['wrong owner',r=>r.jobs[0].owner=null],['unknown properties',r=>r.jobs[0].properties=[]],['unbounded timing',r=>r.jobs[0].duration=Infinity],['new job after snapshot',r=>r.afterJobs=[{}]]])test('settlement rejects '+name,()=>{const r=settled();mutate(r);assert.throws(()=>assertSettlement(r));});
const events=()=>['pointerdown','pointerup','click'].map((type,i)=>({type,control:'Delete',trusted:true,detail:1,pointerId:1,button:0,buttons:type==='pointerdown'?1:0,boundary:'post-production-document-bubble',eventAt:i*10+1,eventTimeStamp:i*10,snapshotStartAt:i*10+2,snapshotEndAt:i*10+3}));
test('strict input sequence and event-before-snapshot timestamps',()=>assertTrustedSequence(events(),'Delete'));
for(const [name,mutate] of [['synthetic',e=>e[0].trusted=false],['wrong intended owner',e=>e[1].control='Cancel'],['pre-production target listener',e=>e[2].boundary='target'],['keyboard click posing as pointer',e=>e[2].detail=0],['timestamp after expensive snapshot',e=>e[0].eventAt=4],['missing release',e=>e.splice(1,1)]])test('event evidence rejects '+name,()=>{const e=events();mutate(e);assert.throws(()=>assertTrustedSequence(e,'Delete'));});
test('post-demo confirmation requires closed modal and restored intended focus',()=>{const s=state();Object.assign(s,{open:false,modal:false,inert:true,expanded:'false',focus:'Invoker'});assertClosedOutcome(s);for(const change of [{focus:'BODY'},{open:true},{modal:true},{expanded:'true'},{inert:false}])assert.throws(()=>assertClosedOutcome({...s,...change}));});
test('all four spacing properties and reachable native actions are required',()=>{assertSpacing(state());for(const mutate of [s=>s.viewport.width=640,s=>s.description.marginBlockEnd='20px',s=>s.heading.letterSpacing='0px',s=>s.description.wordSpacing='normal',s=>s.controls.Delete.lineHeight='20px',s=>s.controls.Delete.hitOwned=false,s=>s.description.textRects=[box(-10,10,300,20)]]){const s=state();mutate(s);assert.throws(()=>assertSpacing(s));}});
const zoom=()=>({dpr:1,innerWidth:1440,outerWidth:1440,outerHeight:900,visualScale:1,cssZoom:'1'});
test('genuine200% zoom requires fixed outer window plus DPR/layout evidence',()=>assertZoom200(zoom(),{...zoom(),dpr:2,innerWidth:720}));
for(const [name,after] of [['nonpositive window',{...zoom(),outerWidth:0}],['unchanged browser',zoom()],['resize substitute',{...zoom(),innerWidth:720}],['device scale substitute',{...zoom(),dpr:2}],['pinch scale substitute',{...zoom(),dpr:2,innerWidth:720,visualScale:2}],['CSS zoom substitute',{...zoom(),dpr:2,innerWidth:720,cssZoom:'2'}],['window resize',{...zoom(),dpr:2,innerWidth:720,outerWidth:720}]])test('zoom rejects '+name,()=>assert.throws(()=>assertZoom200(zoom(),after)));
// Execute the ACTUAL closure, not a rewritten approximation, with a deterministic RAF model.
const helperSource=readFileSync(new URL('./transitions-library-dialog-supplement-helpers.mjs',import.meta.url),'utf8');
const begin=helperSource.indexOf('window.__supplementSettle='),end=helperSource.indexOf('\n}\n// Standalone',begin);assert(begin>=0&&end>begin);const actualSettleSource=helperSource.slice(begin,end);
function settlementFixture(){let now=0,nextId=0,jobs=[],snapshotCalls=0;const callbacks=new Map(),timers=new Map(),d={isConnected:true,open:true,inert:false,matches:()=>d.open},t={isConnected:true},window={__supplementState:()=>{snapshotCalls++;return {animations:jobs.map(jobRecord)};}},log={settlements:[]};const jobRecord=j=>({...j.record});const context={d,t,window,log,ownedJobs:()=>jobs,jobRecord,performance:{now:()=>now},requestAnimationFrame:fn=>{const id=++nextId;callbacks.set(id,fn);return id;},cancelAnimationFrame:id=>callbacks.delete(id),setTimeout:(fn,delay)=>{const id=++nextId;timers.set(id,{fn,at:now+delay});return id;},clearTimeout:id=>timers.delete(id)};vm.runInNewContext(actualSettleSource,context);
 return {window,log,d,t,elapse:ms=>{now+=ms;},setJobs:j=>{jobs=j;},get snapshots(){return snapshotCalls;},tick:async(ms=16)=>{now+=ms;for(const [id,timer] of [...timers])if(timer.at<=now){timers.delete(id);timer.fn();}const work=[...callbacks];callbacks.clear();for(const [,fn]of work)fn(now);await Promise.resolve();},job:()=>{let fulfill,reject;const j={record:{owner:'Cancel',kind:'CSSTransition',pseudo:null,properties:['transform'],playState:'running',pending:false,duration:100,endTime:100},finished:new Promise((yes,no)=>{fulfill=yes;reject=no;})};return {j,finish:()=>{j.record.playState='finished';fulfill();},cancel:()=>{j.record.playState='idle';reject(Error('cancelled native job'));}};}};
}
test('actual settlement awaits native finished promise plus two quiet RAFs',async()=>{const f=settlementFixture(),j=f.job();f.setJobs([j.j]);const promise=f.window.__supplementSettle({requireOpen:true});await f.tick();assert.equal(f.log.settlements[0].status,'running');j.finish();f.setJobs([]);await Promise.resolve();await f.tick();assert.equal(f.log.settlements[0].status,'running');await f.tick();const r=await promise;assertSettlement(r);assert.equal(r.jobs[0].outcome,'finished');assert.equal(f.snapshots,1);});
test('actual snapshot starting a new owned transition requires another completion',async()=>{const f=settlementFixture(),j=f.job();let calls=0;f.window.__supplementState=()=>{if(++calls===1)f.setJobs([j.j]);return {animations:calls===1?[j.j.record]:[]};};const promise=f.window.__supplementSettle({requireOpen:true});await f.tick();assert.equal(f.log.settlements[0].status,'running');assert.equal(calls,0);await f.tick();assert.equal(calls,1);j.finish();f.setJobs([]);await Promise.resolve();await f.tick();await f.tick();assertSettlement(await promise);assert.equal(calls,2);});
test('actual owned cancellation rejects and preserves error',async()=>{const f=settlementFixture(),j=f.job();f.setJobs([j.j]);const promise=f.window.__supplementSettle({requireOpen:true}),rejection=assert.rejects(promise,/cancelled/);j.cancel();await Promise.resolve();f.setJobs([]);await f.tick();await rejection;assert.equal(f.log.settlements[0].status,'failed');assert.equal(f.log.settlements[0].jobs[0].outcome,'cancelled');});
test('actual hanging native timeline times out and keeps observations',async()=>{const f=settlementFixture(),j=f.job();f.setJobs([j.j]);const promise=f.window.__supplementSettle({requireOpen:true,timeoutMs:100}),rejection=assert.rejects(promise,/deadline/);await f.tick(101);await rejection;assert(f.log.settlements[0].observations.length);assert.equal(f.log.settlements[0].jobs[0].outcome,'pending');});
test('actual native ownership loss is rejected before snapshot',async()=>{const f=settlementFixture();f.d.inert=true;await assert.rejects(f.window.__supplementSettle({requireOpen:true}),/ownership lost/);assert.equal(f.snapshots,0);});

test('native close can retire its own descendant release feedback without claiming completion',async()=>{const f=settlementFixture(),j=f.job();f.setJobs([j.j]);const promise=f.window.__supplementSettle({requireOpen:false});f.d.open=false;f.d.inert=true;f.window.__supplementState=()=>({open:false,modal:false,inert:true,animations:[]});j.cancel();await Promise.resolve();f.setJobs([]);await f.tick();await f.tick();const r=await promise;assertSettlement(r);assert.equal(r.jobs[0].outcome,'cancelled');assert.equal(r.jobs[0].disposition,'native-close-retired');for(const change of [{requireOpen:true},{snapshot:{open:true,modal:true,inert:false}}])assert.throws(()=>assertSettlement({...r,...change}));for(const change of [{kind:'Animation'},{owner:'Dialog'},{owner:'Invoker'},{pseudo:'::backdrop'},{properties:['opacity']},{properties:['filter']},{retirementState:{open:true,modal:true,inert:true}}]){const bad=copy(r);Object.assign(bad.jobs[0],change);assert.throws(()=>assertSettlement(bad));}});

test('empty endpoint counts two distinct actual RAF callbacks, never the synchronous inventory',async()=>{const f=settlementFixture(),promise=f.window.__supplementSettle({requireOpen:true});assert.equal(f.log.settlements[0].status,'running');assert.equal(f.log.settlements[0].observations[0].boundary,'synchronous-inventory');await f.tick();assert.equal(f.log.settlements[0].status,'running');assert.equal(f.snapshots,0);await f.tick();const r=await promise;assertSettlement(r);assert.deepEqual(Array.from(r.quietRAFAt),[16,32]);assert.equal(r.observations.filter(o=>o.boundary==='actual-RAF').length,2);});
test('a repeated RAF timestamp cannot count as a distinct quiet frame',async()=>{const f=settlementFixture(),promise=f.window.__supplementSettle({requireOpen:true});await f.tick(16);await f.tick(0);assert.equal(f.log.settlements[0].status,'running');await f.tick(16);assertSettlement(await promise);});
for(const bad of [[],[16],[16,16],[32,16],[NaN,16]])test('settlement guard rejects non-distinct actual RAF records '+JSON.stringify(bad),()=>{const s=settled();s.quietRAFAt=bad;assert.throws(()=>assertSettlement(s));});
for(const color of ['transparent','rgba(0, 80, 200, 0)','rgb(0 80 200 / 0%)','color(srgb 0 .2 .9 / 0)','rgba(0, 80, 200, .5)','not-a-color'])test('focus paint rejects '+color,()=>{const s=state();Object.assign(s.controls.Cancel,{focused:true,focusVisible:true,outlineWidth:'2px',outlineStyle:'solid',outlineColor:color});assert.throws(()=>assertControl(s,'Cancel','keyboard-focus'));});
test('opaque computed focus color supports RGB and sRGB encodings',()=>{for(const c of ['rgb(0, 80, 200)','rgb(0 80 200 / 100%)','color(srgb 0 .2 .9 / 1)'])assert(opaqueComputedColor(c));});
for(const [name,mutate] of [['out-of-order',e=>e.reverse()],['duplicate intended down',e=>e.splice(1,0,{...e[0]})],['nonmonotonic event time',e=>e[1].eventAt=0],['nonmonotonic native timestamp',e=>e[1].eventTimeStamp=-1],['different releasing pointer',e=>e[1].pointerId=2],['nonprimary button',e=>e[0].button=1]])test('pointer cycle rejects '+name,()=>{const e=events();mutate(e);assert.throws(()=>assertTrustedSequence(e,'Delete'));});
test('console/error/request inventories are capped with explicit dropped counts',()=>{const run={};for(const key of ['console','pageErrors','requestsFailed'])for(let i=0;i<7;i++)appendBounded(run,key,{text:'full message '+i},3);for(const key of ['console','pageErrors','requestsFailed']){assert.equal(run[key].length,3);assert.equal(run.inventory[key].total,7);assert.equal(run.inventory[key].dropped,4);assert(run.inventory[key].overflow);assert.equal(run[key][2].text,'full message 2');}assert(run.inventoryIncomplete);});

function performanceFixture(){
 let now=0,id=0;const frames=new Map(),timers=new Map(),listeners=new Map(),calls=[],observers=[];
 const window={addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)};
 class PerformanceObserver {static supportedEntryTypes=['longtask'];constructor(callback){this.callback=callback;this.records=[];this.connected=false;observers.push(this);}observe(){this.connected=true;calls.push('observe');}takeRecords(){calls.push('drain');const records=this.records;this.records=[];return records;}disconnect(){this.connected=false;calls.push('disconnect');}}
 const context={window,PerformanceObserver,performance:{now:()=>now},requestAnimationFrame:fn=>{const n=++id;frames.set(n,fn);return n;},cancelAnimationFrame:n=>frames.delete(n),setTimeout:(fn,ms)=>{const n=++id;timers.set(n,{fn,at:now+ms});return n;},clearTimeout:n=>timers.delete(n)};
 const evaluate=async(fn,arg)=>vm.runInNewContext('('+fn.toString()+')(input)',{...context,input:arg});
 return {window,calls,observers,frames,timers,evaluate,start:options=>evaluate(startPerformanceProbe,options),tick:(ms=16)=>{now+=ms;for(const [n,t]of [...timers])if(t.at<=now){timers.delete(n);t.fn();}const batch=[...frames];frames.clear();for(const [,fn]of batch)fn(now);},deliver:entries=>observers[0].callback({getEntries:()=>entries}),buffer:entries=>{observers[0].records.push(...entries);},close:()=>listeners.get('pagehide')?.(),stop:reason=>window.__supplementStopPerf(reason)};
}
const task=(i=0)=>({startTime:i*60,duration:60,name:'self',attribution:[]});
test('actual RAF500 cap stops and drains/disconnects; later long tasks cannot mutate output',async()=>{const f=performanceFixture();await f.start({deadlineMs:20000});f.buffer([task()]);for(let i=0;i<500;i++)f.tick();const p=f.window.__supplementPerf;assert.equal(p.rafTimes.length,500);assert.equal(p.longTasks.length,1);assert.equal(p.status,'incomplete');assert.equal(p.stopReason,'raf-cap');assert(p.stopped&&p.observerDisconnected&&Number.isFinite(p.finishedAt)&&p.limitsReached.raf);assert.equal(f.frames.size,0);assert.equal(f.timers.size,0);const before=JSON.stringify(p);f.deliver(Array.from({length:501},(_,i)=>task(i)));f.tick();assert.equal(JSON.stringify(p),before);assert.equal(f.observers[0].connected,false);});
test('actual long-task cap bounds data and explicitly records overflow/incompleteness',async()=>{const f=performanceFixture();await f.start({rafLimit:500,longTaskLimit:3,deadlineMs:8000});f.deliver(Array.from({length:9},(_,i)=>task(i)));const p=f.window.__supplementPerf;assert.equal(p.longTasks.length,3);assert.equal(p.dropped.longTasks,6);assert(p.overflow.longTasks&&p.limitsReached.longTasks&&p.incomplete);assert.equal(p.stopReason,'long-task-cap');assert(p.observerDisconnected&&Number.isFinite(p.finishedAt));const before=JSON.stringify(p);f.deliver([task(99)]);assert.equal(JSON.stringify(p),before);});
test('final drain is capped even when normal flow completed',async()=>{const f=performanceFixture();await f.start({rafLimit:500,longTaskLimit:2,deadlineMs:8000});f.buffer([task(1),task(2),task(3)]);f.stop('completed');const p=f.window.__supplementPerf;assert.equal(p.longTasks.length,2);assert.equal(p.status,'incomplete');assert.equal(p.dropped.longTasks,1);assert(p.observerDisconnected);});
test('performance deadline stops, drains and records an incomplete result',async()=>{const f=performanceFixture();await f.start({rafLimit:500,longTaskLimit:128,deadlineMs:100});f.tick(101);const p=f.window.__supplementPerf;assert.equal(p.stopReason,'deadline');assert.equal(p.status,'incomplete');assert(p.observerDisconnected&&Number.isFinite(p.finishedAt));});
test('page hide stops performance; repeated stop never changes the finalized record',async()=>{const f=performanceFixture();await f.start();f.buffer([task()]);f.close();const before=JSON.stringify(f.window.__supplementPerf);f.stop('completed');assert.equal(JSON.stringify(f.window.__supplementPerf),before);assert.equal(f.window.__supplementPerf.stopReason,'pagehide');});
function hostFixture({metricFailure=false,enableFailure=false}={}){const f=performanceFixture(),run={},saves=[];let metrics=0;const session={send:async name=>{f.calls.push(name);if(enableFailure&&name==='Performance.enable')throw Error('injected enable failure');if(name==='Performance.getMetrics'){metrics++;if(metricFailure&&metrics===2)throw Error('injected final metrics failure');return {metrics:['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(name=>({name,value:metrics}))};}},detach:async()=>{f.calls.push('detach');}};const save=()=>{f.calls.push('save');saves.push(copy(run));};return {...f,run,session,save,saves,page:{evaluate:f.evaluate}};}
test('failure-injected flow always saves partial performance before CDP detach',async()=>{const f=hostFixture();await assert.rejects(collectPerformanceFlow({...f,flow:async()=>{f.tick();f.deliver([task()]);f.buffer([task(1)]);throw Error('injected flow failure');}}),/injected flow failure/);assert.equal(f.run.performance.status,'incomplete');assert.equal(f.run.performance.stopReason,'flow-failed');assert.equal(f.run.performance.longTasks.length,2);assert(f.run.performance.observerDisconnected&&Number.isFinite(f.run.performance.finishedAt));assert(f.calls.indexOf('disconnect')<f.calls.indexOf('detach'));assert(f.saves.some(s=>s.performance?.longTasks.length===2));assert(f.calls.indexOf('save')<f.calls.indexOf('detach'));assert.equal(f.observers[0].connected,false);});
test('final CDP failure cannot discard an already drained partial record',async()=>{const f=hostFixture({metricFailure:true});await assert.rejects(collectPerformanceFlow({...f,flow:async()=>{f.tick();f.buffer([task()]);}}),/finalization incomplete/);assert.equal(f.run.performance.longTasks.length,1);assert(f.run.performance.observerDisconnected);assert(f.run.performanceFinalizationErrors.some(s=>s.includes('Final CDP metrics')));assert(f.calls.indexOf('save')<f.calls.indexOf('detach'));});
test('pre-start failure preserves the blocker and still detaches without inventing performance',async()=>{const f=hostFixture({enableFailure:true});await assert.rejects(collectPerformanceFlow({...f,flow:async()=>{throw Error('must not run');}}),/injected enable failure/);assert.equal(f.run.performance,null);assert(f.run.performanceFinalizationErrors.some(s=>s.includes('never started')));assert(f.calls.includes('detach'));assert.equal(f.observers.length,0);});
test('successful performance flow also drains, saves and disconnects',async()=>{const f=hostFixture();const p=await collectPerformanceFlow({...f,flow:async()=>{f.tick();f.tick();f.tick();f.buffer([task()]);}});assert.equal(p.status,'complete');assert.equal(p.rafTimes.length,3);assert.equal(p.longTasks.length,1);assert(p.observerDisconnected);assert(f.calls.indexOf('save')<f.calls.indexOf('detach'));});

test('actual font readiness success clears its bounded timer',async()=>{let cleared=false;const window={},context={window,document:{fonts:{ready:Promise.resolve()}},performance:{now:()=>0},setTimeout:()=>1,clearTimeout:()=>{cleared=true;}};const r=await vm.runInNewContext('('+boundedFontsReady.toString()+')({timeoutMs:100})',context);assert.equal(r.status,'ready');assert(cleared);});
test('actual hung font readiness rejects on its deadline and retains failed status',async()=>{let timeout,cleared=false;const window={},context={window,document:{fonts:{ready:new Promise(()=>{})}},performance:{now:()=>0},setTimeout:fn=>{timeout=fn;return 1;},clearTimeout:()=>{cleared=true;}};const p=vm.runInNewContext('('+boundedFontsReady.toString()+')({timeoutMs:100})',context),rejection=assert.rejects(p,/Font readiness deadline/);timeout();await rejection;assert.equal(window.__dialogFontsReadiness.status,'failed');assert(cleared);});

test('a costly snapshot cannot turn an elapsed native deadline into settlement success',async()=>{const f=settlementFixture();f.window.__supplementState=()=>{f.elapse(2000);return {animations:[]};};const p=f.window.__supplementSettle({requireOpen:true,timeoutMs:1800}),rejection=assert.rejects(p,/deadline exceeded during snapshot/);await f.tick();await f.tick();await rejection;assert.equal(f.log.settlements[0].status,'failed');});

// Exercise the exact async finalizers wired into the real runner.
const finalizableCase=()=>({status:'running',collectionComplete:true,pageErrors:[],captures:[{status:'captured',file:'original.png'}],observations:{kept:true},partialPerformance:{rafTimes:[1,2]}});
test('case cannot become captured until native context close resolves',async()=>{const run=finalizableCase();let resolve;const wait=new Promise(r=>resolve=r);const p=finalizeSupplementCase(run,()=>wait);assert.equal(run.status,'running');resolve();assert.equal(await p,'captured');});
test('page error arriving during context close forces failed while retaining observations',async()=>{const run=finalizableCase(),before=copy(run.observations);await finalizeSupplementCase(run,async()=>{run.pageErrors.push({message:'late-context-page-error'});});assert.equal(run.status,'failed');assert.match(run.error,/Page errors/);assert.deepEqual(run.observations,before);assert.deepEqual(run.partialPerformance.rafTimes,[1,2]);assert.equal(run.captures[0].file,'original.png');});
test('context-close rejection is retained and fails the case',async()=>{const run=finalizableCase();await finalizeSupplementCase(run,async()=>{throw Error('native context close rejected');});assert.equal(run.status,'failed');assert.match(run.closeError,/native context close rejected/);});
test('original action failure is never overwritten by later close or page errors',async()=>{const run={...finalizableCase(),status:'failed',collectionComplete:false,error:'original action failed'};await finalizeSupplementCase(run,async()=>{run.pageErrors.push({message:'late'});throw Error('close failed');});assert.equal(run.error,'original action failed');assert.equal(run.status,'failed');assert.match(run.closeError,/close failed/);});
test('late inventory overflow remains incomplete after close',async()=>{const run=finalizableCase();await finalizeSupplementCase(run,async()=>{run.inventoryIncomplete=true;});assert.equal(run.status,'failed');assert.match(run.error,/inventory incomplete/);});
test('honest capability block is retained when collection and native close completed',async()=>{const run={...finalizableCase(),status:'blocked',blocker:{reason:'native zoom unsupported'}};await finalizeSupplementCase(run,async()=>{});assert.equal(run.status,'blocked');const report={runs:[run]};assert.equal((await finalizeSupplementReport(report,async()=>{})).exitCode,0);assert.equal(run.status,'blocked');});
test('late error overrides capability-blocked status without deleting its reason',async()=>{const run={...finalizableCase(),status:'blocked',blocker:{reason:'native zoom unsupported'}};await finalizeSupplementCase(run,async()=>{run.pageErrors.push({message:'late'});});assert.equal(run.status,'failed');assert.equal(run.blocker.reason,'native zoom unsupported');});
test('browser-close page error rechecks cases already captured',async()=>{const run=finalizableCase();await finalizeSupplementCase(run,async()=>{});assert.equal(run.status,'captured');const report={runs:[run]},result=await finalizeSupplementReport(report,async()=>{run.pageErrors.push({message:'late-browser-page-error'});});assert.equal(result.exitCode,1);assert.equal(report.status,'failed');assert.equal(run.status,'failed');assert.equal(run.observations.kept,true);});
test('browser-close rejection keeps global failure and all retained captures',async()=>{const run=finalizableCase();await finalizeSupplementCase(run,async()=>{});const report={runs:[run]},result=await finalizeSupplementReport(report,async()=>{throw Error('native browser close rejected');});assert.equal(result.exitCode,1);assert.match(report.browserCloseError,/native browser close rejected/);assert.equal(run.captures[0].file,'original.png');});
test('preexisting fatal failure cannot be cleared by successful closure',async()=>{const run=finalizableCase();await finalizeSupplementCase(run,async()=>{});const report={runs:[run],fatalError:'original fatal'};assert.equal((await finalizeSupplementReport(report,async()=>{})).exitCode,1);assert.equal(report.fatalError,'original fatal');});
test('missing collection and empty report cannot be called captured',async()=>{const run=finalizableCase();delete run.collectionComplete;assert.equal(await finalizeSupplementCase(run,async()=>{}),'failed');assert.equal((await finalizeSupplementReport({runs:[]},async()=>{})).exitCode,1);});
test('successful finalization stays collected, with warnings retained as observations',async()=>{const run={...finalizableCase(),console:[{type:'warning',text:'recorded observation'}]};await finalizeSupplementCase(run,async()=>{});const report={runs:[run]};assert.deepEqual(await finalizeSupplementReport(report,async()=>{}),{status:'collected',exitCode:0});assert.equal(run.console[0].text,'recorded observation');});
test('runner uses actual post-close finalizers before case/report writes',()=>{const s=readFileSync(new URL('./transitions-library-dialog-supplement.browser.mjs',import.meta.url),'utf8');assert(s.includes('await fn(page,run);run.collectionComplete=true;'));assert(s.includes('await finalizeSupplementCase(run,async()=>{if(context)await context.close();});save();'));assert(s.includes('const finalized=await finalizeSupplementReport(report,async()=>{if(browser)await browser.close();});if(finalized.exitCode)process.exitCode=finalized.exitCode;save();'));assert(!s.includes("if(run.status==='running')run.status='captured'"));});
