// Execute the actual capture wrapper; no browser or product fixture is changed.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const source=fs.readFileSync(path.join(__dirname,'transitions-library-dialog-raster.browser.mjs'),'utf8'),a=source.indexOf('async function captureRaster('),b=source.indexOf('function installRasterObserver(',a);assert(a>=0&&b>a);
function fixture({screenshotError=false,afterError=false,empty=false,changed=false}={}){
 let clock=0,reads=0;const events=[],writes=[],entry={requestedPhase:'requested-phase',file:'capture.png',status:'requested'};
 const context={assert,join:path.join,readFileSync:()=>{events.push('read-png');return Buffer.alloc(empty?0:12);},performance:{now:()=>{events.push('host-clock');return ++clock;}},Date};
 vm.createContext(context);vm.runInContext(source.slice(a,b)+'\nthis.capture=captureRaster;',context);
 const page={evaluate:async()=>{events.push(++reads===1?'browser-before':'browser-after');if(reads===2&&afterError)throw Error('after unavailable');return {at:reads*10,open:reads===1||!changed,lastAction:reads===2&&changed?'after-api-close':'after-open'};},screenshot:async options=>{events.push('screenshot');assert.equal(options.animations,'allow');assert.equal(options.path,path.join('out','capture.png'));if(screenshotError)throw Error('capture failed');}};
 const run=()=>context.capture(page,entry,{out:'out',sha:()=>{events.push('hash-png');return 'sha';},save:()=>{events.push('save');writes.push(JSON.parse(JSON.stringify(entry)));}});
 return {run,entry,events,writes};
}
test('PNG request/completion clock surrounds only the screenshot call and preserves both browser bounds',async()=>{const f=fixture();await f.run();assert.deepEqual(f.events,['browser-before','save','host-clock','screenshot','host-clock','hash-png','read-png','browser-after','save']);assert.equal(f.entry.hostCapture.elapsedMs,1);assert.equal(f.entry.before.at,10);assert.equal(f.entry.after.at,20);assert.equal(f.entry.status,'captured');assert.equal(f.entry.sameObservedOpenState,true);assert.equal(f.writes[0].hostCapture,undefined);assert.equal(f.writes[1].sha256,'sha');});
test('failed screenshot retains the host completion and browser-after evidence, then rethrows',async()=>{const f=fixture({screenshotError:true});await assert.rejects(f.run,/capture failed/);assert.equal(f.entry.status,'failed');assert.equal(f.entry.hostCapture.elapsedMs,1);assert.equal(f.entry.after.at,20);assert.equal(f.writes.at(-1).status,'failed');assert(!f.events.includes('hash-png'));});
test('missing after-observation remains explicit instead of implying a stable capture window',async()=>{const f=fixture({afterError:true});await f.run();assert.match(f.entry.after.error,/after unavailable/);assert.equal(f.entry.sameObservedOpenState,false);assert.equal(f.entry.status,'captured-unbracketed');});
test('a transition during capture is retained without pretending the requested phase was photographed',async()=>{const f=fixture({changed:true});await f.run();assert.equal(f.entry.before.open,true);assert.equal(f.entry.after.open,false);assert.equal(f.entry.sameObservedOpenState,false);assert.equal(f.entry.requestedPhase,'requested-phase');});
test('empty PNG output cannot become a captured diagnostic',async()=>{const f=fixture({empty:true});await assert.rejects(f.run);assert.equal(f.entry.status,'failed');assert.equal(f.entry.after.at,20);assert.equal(f.writes.at(-1).status,'failed');});
