// Actual native-harness selectors/classifiers/writer executed with explicit model data.
// Native timeline sampling and raster acceptance remain in the browser job.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const file=path.join(__dirname,'transitions-library-dialog.browser.mjs'),source=fs.readFileSync(file,'utf8');
const slice=(a,b)=>{const x=source.indexOf(a),y=source.indexOf(b,x);assert(x>=0&&y>x);return source.slice(x,y);};
const scope={assert};vm.createContext(scope);vm.runInContext(slice('function assertInstantAnimations(','function inspect(')+slice('function naturalCoverage(','async function controlledInterruption(')+slice('function assertImmediateCycle(','function assertPaint(')+'\nthis.helpers={naturalCoverage,selectMotionJobs,assertControlled,assertImmediateCycle,isDialogExitScale};',scope);
const {naturalCoverage,selectMotionJobs,assertControlled,assertImmediateCycle,isDialogExitScale}=scope.helpers;
const active=(opacity=1)=>({modal:true,open:true,inert:false,expanded:'true',focus:'Cancel',opacity,transform:'matrix(0.995, 0, 0, 0.995, 0, 1)',filter:'none',reduce:false,backdropOpacity:1,animations:[{target:'dialog-1',pseudo:null,properties:['transform'],playState:'running',pending:false,currentTime:10,endTime:100}]});
const outgoing=()=>({...active(1),inert:true,expanded:'false'});
const complete=()=>({modal:false,open:false,inert:true,expanded:'false',opacity:0,animations:[]});
const midpoints=()=>[null,'::backdrop'].map(pseudo=>({target:'dialog-1',pseudo,properties:[pseudo?'opacity':'transform'],playState:'paused',pending:false,currentTime:50,requestedMidpoint:50}));
const positive=()=>({entrySampledJobs:midpoints(),exitSampledJobs:midpoints(),status:'observed',mode:'controlled-native-paused-midpoint-api-interruption',trusted:true,detail:1,observedAt:'post-production-document',entryJobs:2,exitJobs:2,entryRetired:true,exitRetired:true,entryBefore:active(),exitBefore:outgoing(),beforeReopen:{...outgoing(),transform:'matrix(0.984, 0, 0, 0.984, 0, 0.5)'},afterReopen:{...active(),transform:'matrix(0.984, 0, 0, 0.984, 0, 0.5)'}});
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split('\n')[0]});}}
const animations=(target,changes={})=>{const t={duration:100,endTime:100,...changes.timing},last=changes.last??{transform:'scale(.97)'};return {playState:'running',currentTime:10,...changes,effect:{target,pseudoElement:changes.pseudo||null,getComputedTiming:()=>t,getKeyframes:()=>[changes.pseudo?{opacity:1}:{transform:'none'},last]}};};

const videoSource=fs.readFileSync(path.join(__dirname,'transitions-library-dialog-video.browser.mjs'),'utf8');
const helperOf=code=>code.slice(code.indexOf('function isDialogExitScale('),code.indexOf('\n}',code.indexOf('function isDialogExitScale('))+2);
const acceptedStart=videoSource.indexOf('function assertAcceptedCoverage('),acceptedEnd=videoSource.indexOf('// Small state inventories',acceptedStart),acceptedScope={assert};assert(acceptedStart>=0&&acceptedEnd>acceptedStart);vm.runInNewContext(videoSource.slice(acceptedStart,acceptedEnd)+'\nthis.check=assertAcceptedCoverage;',acceptedScope);
const acceptedPhases=[['trusted-pointer-open','open',1],['trusted-pointer-Cancel','close',1],['trusted-keyboard-Enter','open',0],['trusted-keyboard-Escape','keyboard-cancel',null],['trusted-open-then-timed-API-reversal','open',1],['trusted-final-Cancel','close',1]];
const acceptedFixture=()=>acceptedPhases.map(([phase,kind,detail])=>({trusted:true,kind,detail,control:kind==='close'?'Cancel':null,state:{phase}}));
test('video positively requires every trusted accepted action in its actual phase',()=>acceptedScope.check(acceptedFixture()));
for(let missing=0;missing<acceptedPhases.length;missing++)test('video rejects omitted accepted phase '+acceptedPhases[missing][0],()=>{const rows=acceptedFixture();rows.splice(missing,1);assert.throws(()=>acceptedScope.check(rows));});
for(const [label,mutate] of [['empty',x=>x.splice(0)],['untrusted',x=>x[0].trusted=false],['wrong control',x=>x[1].control='Delete project'],['pointer masquerades as keyboard',x=>x[2].detail=1],['wrong phase',x=>x[5].state.phase='unrelated']])test('video accepted coverage rejects '+label,()=>{const rows=acceptedFixture();mutate(rows);assert.throws(()=>acceptedScope.check(rows));});
assert(videoSource.includes('assertAcceptedCoverage(run.observations.accepted);'),'Run positive coverage before detailed per-observation assertions');
test('assertion and video classifiers use byte-identical measured-transform semantics',()=>{assert.equal(helperOf(videoSource),helperOf(source));assert(videoSource.includes('window.__dialogExitScale(a.endTransform)'));assert(source.includes('isDialogExitScale(last?.transform)'));});
for(const value of ['scale(.97)','scale(0.97)','scale(0.9700)','scale(.97, .97)','scale(9.7e-1,0.970)','matrix(0.97, 0, 0, 0.97, 0, 0)'])test('equivalent native exit transform qualifies: '+value,()=>{assert(isDialogExitScale(value));const d={};assert.equal(selectMotionJobs([animations(d,{last:{transform:value}})],d,true).length,1);});
for(const value of ['none','scale(1)','scale(.97001)','scale(.97,.98)','scale(.97) translateY(1px)','translate(0) scale(.97)','matrix(.97,0,0,.97,1,0)','matrix(.97,.001,0,.97,0,0)','matrix(.97,0,0,1,0,0)','matrix(.97,0,0,.97,0,0,0)','scale(NaN)','scale(.97,)','scale(0x1)','scale()'])test('different or malformed transform is rejected: '+value,()=>{assert(!isDialogExitScale(value));const d={};assert.equal(selectMotionJobs([animations(d,{last:{transform:value}})],d,true).length,0);});
test('actual finite geometry/backdrop exits qualify while child and late decoys do not',()=>{const d={},child={},surface=animations(d),pseudo=animations(d,{pseudo:'::backdrop',last:{opacity:0}}),childJob=animations(child);const picked=selectMotionJobs([surface,pseudo,childJob],d,true);assert.equal(picked.length,2);assert(picked.includes(surface)&&picked.includes(pseudo));});
for(const [name,patch]of [['finished',{playState:'finished'}],['paused',{playState:'paused'}],['null time',{currentTime:null}],['past end',{currentTime:110}],['zero duration',{timing:{duration:0}}],['infinite duration',{timing:{duration:Infinity}}],['entrance opacity',{last:{opacity:1}}],['entrance transform',{last:{transform:'none'}}],['surface opacity only',{last:{opacity:0}}],['pseudo transform',{pseudo:'::backdrop',last:{transform:'scale(.97)'}}]])test('exit selector rejects '+name,()=>{const d={};assert.equal(selectMotionJobs([animations(d,patch)],d,true).length,0);});
test('entrance selector retains a real transform job without pretending it is an opacity exit',()=>{const d={},a=animations(d,{last:{transform:'none'}});assert.equal(selectMotionJobs([a],d).length,1);assert.equal(selectMotionJobs([a],d,true).length,0);});
test('natural timing requires both actual running windows',()=>{const r={actions:[{kind:'before-close',...active()},{kind:'before-reopen',...outgoing()}]};assert.equal(naturalCoverage(r).status,'covered');});
test('natural interruption rejects child or backdrop-only jobs after surface geometry has ended',()=>{for(const changes of [{target:'child'},{pseudo:'::backdrop',properties:['opacity']}]){const before=active(),after=outgoing();after.animations[0]={...after.animations[0],...changes};assert.equal(naturalCoverage({actions:[{kind:'before-close',...before},{kind:'before-reopen',...after}]}).status,'blocked');}});
test('actual macOS completed exit remains blocked and unaccepted',()=>{const r={actions:[{kind:'before-close',...active()},{kind:'after-close',at:5100.2,...outgoing()},{kind:'before-reopen',at:5263.6,...complete()}]};const c=naturalCoverage(r);assert.equal(c.status,'blocked');assert(c.openingInterrupted&&!c.exitInterrupted);});
test('late natural first-close or absent actions cannot claim rapid open interruption',()=>{for(const r of [{actions:[]},{actions:[{kind:'before-close',...active(),animations:[]},{kind:'before-reopen',...outgoing()}]}])assert.equal(naturalCoverage(r).status,'blocked');});
test('positive controlled state proves paused real geometry exit with opaque shell and both ownership retirements',()=>assertControlled(positive()));
for(const [name,mutate]of [['still running entry',x=>x.entrySampledJobs[0].playState='running'],['pending exit pause',x=>x.exitSampledJobs[0].pending=true],['unsampled midpoint',x=>x.exitSampledJobs[0].currentTime=0],['missing actual time',x=>x.entrySampledJobs[0].currentTime=null],['missing selected job evidence',x=>x.entrySampledJobs.pop()],['different target',x=>x.exitSampledJobs[0].target='child'],['blocked window',x=>x.status='blocked'],['untrusted opening',x=>x.trusted=false],['keyboard masquerading as pointer',x=>x.detail=0],['target-listener observation',x=>x.observedAt='target'],['missing entry',x=>x.entryJobs=0],['missing exit',x=>x.exitJobs=0],['old entry survives',x=>x.entryRetired=false],['old exit survives',x=>x.exitRetired=false],['closed before reopen',x=>x.beforeReopen.open=false],['not outgoing',x=>x.beforeReopen.inert=false],['zero opacity',x=>x.beforeReopen.opacity=0],['translucent exit',x=>x.beforeReopen.opacity=.5],['unadvanced geometry',x=>x.beforeReopen.transform=x.exitBefore.transform],['geometry missing',x=>x.exitSampledJobs[0].properties=['opacity']],['backdrop missing',x=>x.exitSampledJobs[1].pseudo=null],['translucent reopen',x=>x.afterReopen.opacity=.5],['jumping reopen',x=>x.afterReopen.transform='none'],['reopen remained inert',x=>x.afterReopen.inert=true],['missing safe focus',x=>x.afterReopen.focus='BODY']])test('controlled rejects '+name,()=>{const r=positive();mutate(r);assert.throws(()=>assertControlled(r));});
const instant=()=>({...active(),reduce:true,transform:'none',animations:[]}),immediate=()=>({beforeClose:instant(),afterClose:{...complete(),reduce:true,focus:'dialog-trigger'},afterReopen:instant()});
test('reduced fresh immediate cycle is positively verified without claiming interruption',()=>{const r=immediate();assertImmediateCycle(r);const actions=[{kind:'trusted-open',...instant()},{kind:'before-close',...r.beforeClose},{kind:'after-close',...r.afterClose},{kind:'before-reopen',...r.afterClose},{kind:'after-reopen',...r.afterReopen}];assert.equal(naturalCoverage({actions}).status,'immediate');assertControlled({...r,mode:'reduced-immediate-fresh-cycle',status:'immediate',trusted:true,detail:1,observedAt:'post-production-document'});});
for(const [name,mutate]of [['delayed backdrop',r=>r.afterReopen.animations=[{pseudo:'::backdrop'}]],['transparent backdrop',r=>r.afterReopen.backdropOpacity=0],['translucent shell',r=>r.beforeClose.opacity=.5],['delayed close',r=>r.afterClose.open=true],['lost restoration',r=>r.afterClose.focus='BODY'],['remaining travel',r=>r.afterReopen.transform='scale(.97)']])test('immediate cycle rejects '+name,()=>{const r=immediate();mutate(r);assert.throws(()=>assertImmediateCycle(r));});
test('incremental writer preserves completed profiles and uses a small progress index until final assembly',()=>{const writes=new Map(),run={width:320,height:780,theme:'dark',motion:'reduce',status:'running',routes:[{large:'x'.repeat(20000)}]},report={browser:'model',source:{pin:'exact'},runs:[run]},context={report,out:'out',join:path.join,writeFileSync:(file,data)=>writes.set(file,data)};vm.createContext(context);vm.runInContext(slice('const save=','const parse=')+'\nthis.save=save;',context);context.save();const first=writes.get(path.join('out','320-dark-reduce-case.json'));const index=JSON.parse(writes.get(path.join('out','results.json')));assert.equal(index.format,'incremental-profile-index');assert.equal(index.runs[0].routes,undefined);assert.equal(index.runs[0].caseFile,'320-dark-reduce-case.json');assert(JSON.parse(first).routes[0].large.length===20000);run.status='passed';context.save();const preserved=writes.get(path.join('out','320-dark-reduce-case.json'));report.runs.push({...run,width:390,status:'running',routes:[{actual:'next'}]});context.save();assert.equal(writes.get(path.join('out','320-dark-reduce-case.json')),preserved);assert(writes.get(path.join('out','results.json')).length<1000);context.save(true);const final=JSON.parse(writes.get(path.join('out','results.json')));assert.equal(final.format,undefined);assert.equal(final.runs[0].routes[0].large.length,20000);assert.equal(final.runs[1].routes[0].actual,'next');});
assert(source.includes('r.pointerExit=exit;save();assertPointerExit(exit)'),'Retain a missed pointer exit before rejecting its precondition');assert(source.includes("document.addEventListener('click',observe);"),'Natural and controlled opening observers belong after production delegation');assert(source.includes("elapsed:performance.now()-start"),'Relative clock must not overwrite absolute browser time');
const report={harnessSha256:crypto.createHash('sha256').update(source).digest('hex'),passed:results.filter(r=>r.pass).length,total:results.length,scope:'Actual helper/model controls; natural timing and native raster results remain separate',results};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
