// Actual native-harness selectors/classifiers/writer executed with explicit model data.
// Native timeline sampling and raster acceptance remain in the browser job.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const file=path.join(__dirname,'transitions-library-dialog.browser.mjs'),source=fs.readFileSync(file,'utf8');
const slice=(a,b)=>{const x=source.indexOf(a),y=source.indexOf(b,x);assert(x>=0&&y>x);return source.slice(x,y);};
const scope={assert};vm.createContext(scope);vm.runInContext(slice('function naturalCoverage(','async function controlledInterruption(')+slice('function assertControlled(','function assertPaint(')+'\nthis.helpers={naturalCoverage,selectMotionJobs,assertControlled};',scope);
const {naturalCoverage,selectMotionJobs,assertControlled}=scope.helpers;
const active=(opacity=1)=>({modal:true,open:true,inert:false,expanded:'true',focus:'Cancel',opacity,animations:[{playState:'running',currentTime:10,endTime:100}]});
const outgoing=()=>({...active(.5),inert:true,expanded:'false'});
const complete=()=>({modal:false,open:false,inert:true,expanded:'false',opacity:0,animations:[]});
const midpoints=()=>[1,2].map(()=>({target:'dialog-1',playState:'paused',pending:false,currentTime:50,requestedMidpoint:50}));
const positive=()=>({entrySampledJobs:midpoints(),exitSampledJobs:midpoints(),status:'observed',mode:'controlled-native-paused-midpoint-api-interruption',trusted:true,detail:1,observedAt:'post-production-document',entryJobs:2,exitJobs:2,entryRetired:true,exitRetired:true,entryBefore:active(),exitBefore:outgoing(),beforeReopen:outgoing(),afterReopen:active()});
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split('\n')[0]});}}
const animations=(target,changes={})=>{const t={duration:100,endTime:100,...changes.timing},last=changes.last??{opacity:0};return {playState:'running',currentTime:10,...changes,effect:{target,getComputedTiming:()=>t,getKeyframes:()=>[{opacity:1},last]}};};
test('actual finite surface/pseudo opacity exits qualify while child and late decoys do not',()=>{const d={},child={},surface=animations(d),pseudo=animations(d),childJob=animations(child);const picked=selectMotionJobs([surface,pseudo,childJob],d,true);assert.equal(picked.length,2);assert(picked.includes(surface)&&picked.includes(pseudo));});
for(const [name,patch]of [['finished',{playState:'finished'}],['paused',{playState:'paused'}],['null time',{currentTime:null}],['past end',{currentTime:110}],['zero duration',{timing:{duration:0}}],['infinite duration',{timing:{duration:Infinity}}],['entrance opacity',{last:{opacity:1}}],['transform-only',{last:{transform:'none'}}]])test('exit selector rejects '+name,()=>{const d={};assert.equal(selectMotionJobs([animations(d,patch)],d,true).length,0);});
test('entrance selector retains a real transform job without pretending it is an opacity exit',()=>{const d={},a=animations(d,{last:{transform:'none'}});assert.equal(selectMotionJobs([a],d).length,1);assert.equal(selectMotionJobs([a],d,true).length,0);});
test('natural timing requires both actual running windows',()=>{const r={actions:[{kind:'before-close',...active()},{kind:'before-reopen',...outgoing()}]};assert.equal(naturalCoverage(r).status,'covered');});
test('actual macOS completed exit remains blocked and unaccepted',()=>{const r={actions:[{kind:'before-close',...active()},{kind:'after-close',at:5100.2,...outgoing()},{kind:'before-reopen',at:5263.6,...complete()}]};const c=naturalCoverage(r);assert.equal(c.status,'blocked');assert(c.openingInterrupted&&!c.exitInterrupted);});
test('late natural first-close or absent actions cannot claim rapid open interruption',()=>{for(const r of [{actions:[]},{actions:[{kind:'before-close',...active(),animations:[]},{kind:'before-reopen',...outgoing()}]}])assert.equal(naturalCoverage(r).status,'blocked');});
test('positive controlled state proves paused real intermediate exit and both ownership retirements',()=>assertControlled(positive()));
for(const [name,mutate]of [['still running entry',x=>x.entrySampledJobs[0].playState='running'],['pending exit pause',x=>x.exitSampledJobs[0].pending=true],['unsampled midpoint',x=>x.exitSampledJobs[0].currentTime=0],['missing actual time',x=>x.entrySampledJobs[0].currentTime=null],['missing selected job evidence',x=>x.entrySampledJobs.pop()],['different target',x=>x.exitSampledJobs[0].target='child'],['blocked window',x=>x.status='blocked'],['untrusted opening',x=>x.trusted=false],['keyboard masquerading as pointer',x=>x.detail=0],['target-listener observation',x=>x.observedAt='target'],['missing entry',x=>x.entryJobs=0],['missing exit',x=>x.exitJobs=0],['old entry survives',x=>x.entryRetired=false],['old exit survives',x=>x.exitRetired=false],['closed before reopen',x=>x.beforeReopen.open=false],['not outgoing',x=>x.beforeReopen.inert=false],['zero opacity',x=>x.beforeReopen.opacity=0],['no intermediate opacity',x=>x.beforeReopen.opacity=1],['reopen remained inert',x=>x.afterReopen.inert=true],['missing safe focus',x=>x.afterReopen.focus='BODY']])test('controlled rejects '+name,()=>{const r=positive();mutate(r);assert.throws(()=>assertControlled(r));});
test('incremental writer preserves completed profiles and uses a small progress index until final assembly',()=>{const writes=new Map(),run={width:320,height:780,theme:'dark',motion:'reduce',status:'running',routes:[{large:'x'.repeat(20000)}]},report={browser:'model',source:{pin:'exact'},runs:[run]},context={report,out:'out',join:path.join,writeFileSync:(file,data)=>writes.set(file,data)};vm.createContext(context);vm.runInContext(slice('const save=','const parse=')+'\nthis.save=save;',context);context.save();const first=writes.get(path.join('out','320-dark-reduce-case.json'));const index=JSON.parse(writes.get(path.join('out','results.json')));assert.equal(index.format,'incremental-profile-index');assert.equal(index.runs[0].routes,undefined);assert.equal(index.runs[0].caseFile,'320-dark-reduce-case.json');assert(JSON.parse(first).routes[0].large.length===20000);run.status='passed';context.save();const preserved=writes.get(path.join('out','320-dark-reduce-case.json'));report.runs.push({...run,width:390,status:'running',routes:[{actual:'next'}]});context.save();assert.equal(writes.get(path.join('out','320-dark-reduce-case.json')),preserved);assert(writes.get(path.join('out','results.json')).length<1000);context.save(true);const final=JSON.parse(writes.get(path.join('out','results.json')));assert.equal(final.format,undefined);assert.equal(final.runs[0].routes[0].large.length,20000);assert.equal(final.runs[1].routes[0].actual,'next');});
assert(source.includes('r.pointerExit=exit;save();assertPointerExit(exit)'),'Retain a missed pointer exit before rejecting its precondition');assert(source.includes("document.addEventListener('click',observe);"),'Natural and controlled opening observers belong after production delegation');assert(source.includes("elapsed:performance.now()-start"),'Relative clock must not overwrite absolute browser time');
const report={harnessSha256:crypto.createHash('sha256').update(source).digest('hex'),passed:results.filter(r=>r.pass).length,total:results.length,scope:'Actual helper/model controls; natural timing and native raster results remain separate',results};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
