// Opt-in source action pin: production helper and full-runtime lifecycle, not pixel acceptance.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),code=fs.readFileSync(input,'utf8');
const fixtureSource=fs.readFileSync(path.join(__dirname,'transitions-library-card-input-policy.test.cjs'),'utf8'),scope={require,__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(fixtureSource.slice(0,fixtureSource.indexOf('const alive='))+'\nthis.makeFixture=make;',scope);
function cssom(style){const priorities={};style.getPropertyValue=key=>style[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]??'';style.getPropertyPriority=key=>priorities[key]||'';style.setProperty=(key,value,priority='')=>{style[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=value;priorities[key]=priority;};return style;}
const rect=(x,y,w,h)=>({left:x,top:y,right:x+w,bottom:y+h,width:w,height:h});
function make(y=100,w=237,candidate=code){const f=scope.makeFixture(candidate),a=new f.env.E();f.source.append(a);cssom(a.style);cssom(f.control.style);f.control.offsetWidth=f.control.offsetHeight=44;const query=f.source.querySelector;f.source.querySelector=s=>s==='[data-st-close-anchor]'?a:query(s);let scroll=0;f.source.getBoundingClientRect=()=>rect(0,y-scroll,w,81);f.surface.getBoundingClientRect=()=>rect(0,-scroll,w,296);a.getBoundingClientRect=()=>rect(w-52,y+8-scroll,44,44);f.control.style.translate='3px 4px';f.env.context.CSS={supports:()=>true};f.control.getBoundingClientRect=()=>{if(f.control.style.position==='fixed'&&f.control.style.positionAnchor&&String(a.style.anchorName).includes(f.control.style.positionAnchor))return a.getBoundingClientRect();if(f.control.style.positionAnchor)return rect(6,6-scroll,44,44);const t=(f.control.style.translate||'').split(/\s+/).map(parseFloat);return rect(w-52+(t[0]||0),8-scroll+(t[1]||0),44,44)};return {...f,anchor:a,scroll:n=>scroll=n,reflow:n=>y=n,resize:n=>w=n};}
let passed=0;
for(const w of [237,307,420,326.65625])for(const y of [20,109,198]){const f=make(y,w);f.S.expand(f.source,f.detail,{keyboard:false});assert.deepEqual(f.control.getBoundingClientRect(),f.anchor.getBoundingClientRect());assert(!f.animations.some(a=>a.owner===f.control&&a.frames.some(k=>'translate'in k)),'A fixed Close must not carry a dummy translation animation');assert.equal(f.control.style.positionVisibility,'always','A hidden source cue must not auto-hide its anchored Close');assert.equal(f.source.style.visibility,'hidden');f.reflow(y+5);f.resize(w+10);assert.deepEqual(f.control.getBoundingClientRect(),f.anchor.getBoundingClientRect(),'CSS relation follows label reflow and width changes');f.scroll(40);assert.deepEqual(f.control.getBoundingClientRect(),f.anchor.getBoundingClientRect(),'Pin follows container scrolling');f.S.collapse(f.detail,{keyboard:false});assert.deepEqual(f.control.getBoundingClientRect(),f.anchor.getBoundingClientRect());f.S.expand(f.source,f.detail,{keyboard:false});assert.deepEqual(f.control.getBoundingClientRect(),f.anchor.getBoundingClientRect());f.S.collapse(f.detail,{keyboard:true});assert.equal(f.control.style.translate,'3px 4px','Cleanup restores authored positioning');assert.equal(f.detail.dataset.stOpen,'false');passed++;}
const keyboard=make();keyboard.S.expand(keyboard.source,keyboard.detail,{keyboard:true});assert.deepEqual(keyboard.control.getBoundingClientRect(),keyboard.anchor.getBoundingClientRect());assert.equal(keyboard.animations.filter(a=>!a.cancelled).length,0);keyboard.S.collapse(keyboard.detail,{keyboard:true});assert.equal(keyboard.control.style.translate,'3px 4px');passed++;
const outside=make();outside.anchor.getBoundingClientRect=()=>rect(500,100,44,44);outside.S.expand(outside.source,outside.detail,{keyboard:false});assert.equal(outside.animations.filter(a=>!a.cancelled).length,0,'Uncontained marked layouts must open instantly');assert.equal(outside.detail.dataset.stInstant,'');passed++;
const html=fs.readFileSync(path.join(path.dirname(input),'gallery.html'),'utf8');assert.equal((html.match(/class="cover-open" data-st-close-anchor aria-hidden="true"/g)||[]).length,3);assert(html.includes('.stage:has([data-st-close-anchor]) .ex-preview{padding-right:52px;margin-top:0}'));assert(html.includes('.ex-tracks li{height:auto;min-height:32px;'));assert(html.includes('calc(50% - 210px)'));assert(html.includes('Layouts that cannot preserve that point open and close instantly.'));assert(html.includes('.cover-card:active{transform:none}'));assert(html.includes('.cover-card:active .cover{transform:scale(.98)}'));passed++;
const fallback=make();fallback.env.context.CSS.supports=()=>false;fallback.S.expand(fallback.source,fallback.detail,{keyboard:false});assert(!fallback.control.dataset.stClosePinned);assert.equal(fallback.animations.filter(a=>!a.cancelled).length,0);assert.equal(fallback.detail.dataset.stInstant,'');fallback.S.collapse(fallback.detail,{keyboard:false});assert.equal(fallback.detail.dataset.stOpen,'false');assert(!fallback.detail.dataset.stClosing);passed++;
const priority=make();const saved={position:'relative',translate:'3px 4px','position-anchor':'--authored','position-visibility':'anchors-visible',top:'17px',right:'8px',bottom:'auto',left:'auto'};for(const [key,value] of Object.entries(saved))priority.control.style.setProperty(key,value,'important');priority.anchor.style.setProperty('anchor-name','--existing-cue','important');priority.control.dataset.stClosePinned='authored-note';priority.S.expand(priority.source,priority.detail,{keyboard:true});assert.equal(priority.control.style.getPropertyPriority('position-visibility'),'important');priority.S.collapse(priority.detail,{keyboard:true});for(const [key,value] of Object.entries(saved)){assert.equal(priority.control.style.getPropertyValue(key),value);assert.equal(priority.control.style.getPropertyPriority(key),'important');}assert.equal(priority.anchor.style.getPropertyValue('anchor-name'),'--existing-cue');assert.equal(priority.anchor.style.getPropertyPriority('anchor-name'),'important');assert.equal(priority.control.dataset.stClosePinned,'authored-note');passed++;
const absolute=code.replace("Object.entries({position: 'fixed', translate: 'none', 'position-anchor': s.closePin.name", "Object.entries({position: 'absolute', translate: 'none', 'position-anchor': s.closePin.name");assert.notEqual(absolute,code);const unresolved=make(100,237,absolute);unresolved.S.expand(unresolved.source,unresolved.detail,{keyboard:false});assert(!unresolved.control.dataset.stClosePinned,'Observed padding-origin resolution must reject old absolute positioning');assert.equal(unresolved.detail.dataset.stInstant,'');assert.equal(unresolved.animations.filter(a=>!a.cancelled).length,0);unresolved.S.collapse(unresolved.detail,{keyboard:false});assert.equal(unresolved.detail.dataset.stOpen,'false');passed++;
const noFallback=absolute.replace("  if (s.closePinFallback) { instant = true; detail.dataset.stInstant = ''; }",'');assert.notEqual(noFallback,absolute);const unsafe=make(100,237,noFallback);unsafe.S.expand(unsafe.source,unsafe.detail,{keyboard:false});assert(unsafe.animations.some(a=>!a.cancelled&&a.owner===unsafe.control&&a.frames.some(k=>'translate'in k)),'Removed safe path recreates moving fallback in the marked layout');passed++;
const unmarked=make();const originalQuery=unmarked.source.querySelector;unmarked.source.querySelector=q=>q==='[data-st-close-anchor]'?null:originalQuery(q);unmarked.S.expand(unmarked.source,unmarked.detail,{keyboard:false});assert(unmarked.animations.some(a=>!a.cancelled&&a.owner===unmarked.control&&a.frames.some(k=>'translate'in k)),'Generic unmarked Card retains its existing attached motion');assert(!unmarked.detail.hasAttribute('data-st-instant'));passed++;
const held=make(),placed=held.control.getBoundingClientRect;let press=false,shift=0;held.control.getBoundingClientRect=()=>{const r=placed();if(!press)return r;const w=r.width*.96,h=r.height*.96,left=r.left+(r.width-w)/2+shift,top=r.top+(r.height-h)/2;return {left,top,right:left+w,bottom:top+h,width:w,height:h};};held.S.expand(held.source,held.detail,{keyboard:false});press=true;held.S.collapse(held.detail,{keyboard:false});assert.equal(held.detail.dataset.stClosing,'true','Center-preserving native press must retain the normal exit');assert.equal(held.control.dataset.stClosePinned,'css');held.S.expand(held.source,held.detail,{keyboard:false});assert.equal(held.control.dataset.stClosePinned,'css');assert(!held.detail.hasAttribute('data-st-instant'));shift=4;held.S.expand(held.source,held.detail,{keyboard:false});assert.equal(held.control.dataset.stClosePinned,undefined,'A real position error must still reject');assert.equal(held.detail.dataset.stInstant,'');held.S.collapse(held.detail,{keyboard:false});assert.equal(held.detail.dataset.stClosing,undefined);passed++;
const wrongSize=make();wrongSize.control.offsetWidth=45;wrongSize.S.expand(wrongSize.source,wrongSize.detail,{keyboard:false});assert(!wrongSize.control.dataset.stClosePinned);assert.equal(wrongSize.detail.dataset.stInstant,'');passed++;
const oldPressGuard=code.replace("  if (getComputedStyle(control).positionVisibility !== 'always' || Math.abs((placed.left + placed.right) - (target.left + target.right)) > 1 || Math.abs((placed.top + placed.bottom) - (target.top + target.bottom)) > 1 || Math.abs(footprint.width - target.width) > .5 || Math.abs(footprint.height - target.height) > .5 || placed.left < target.left - .5 || placed.top < target.top - .5 || placed.right > target.right + .5 || placed.bottom > target.bottom + .5 || !placed.width || !placed.height) { restoreExpandClosePin(s); return false; }","  if (getComputedStyle(control).positionVisibility !== 'always' || Math.abs(placed.left - target.left) > .5 || Math.abs(placed.top - target.top) > .5 || Math.abs(placed.width - target.width) > .5 || Math.abs(placed.height - target.height) > .5) { restoreExpandClosePin(s); return false; }");assert.notEqual(oldPressGuard,code);const oldPressed=make(100,237,oldPressGuard),oldPlaced=oldPressed.control.getBoundingClientRect;let activePress=false;oldPressed.control.getBoundingClientRect=()=>{const r=oldPlaced();if(!activePress)return r;const w=r.width*.96,h=r.height*.96,left=r.left+(r.width-w)/2,top=r.top+(r.height-h)/2;return {left,top,right:left+w,bottom:top+h,width:w,height:h};};oldPressed.S.expand(oldPressed.source,oldPressed.detail,{keyboard:false});activePress=true;oldPressed.S.collapse(oldPressed.detail,{keyboard:false});assert.equal(oldPressed.detail.dataset.stClosing,undefined,'Old transformed-box guard converts a valid active press to instant fallback');assert.equal(oldPressed.detail.dataset.stOpen,'false');passed++;
console.log(`${passed}/${passed} fixed-anchor contracts pass;12 required-width/album geometry models preserve the point through scroll/reversal/cleanup`);
