// Full production runtime, controlled WAAPI lifecycle. Native pixels remain a separate gate.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),code=fs.readFileSync(input,'utf8');
const fixtureSource=fs.readFileSync(path.join(__dirname,'transitions-library-reduced-expand-reopen.test.cjs'),'utf8'),scope={require:name=>name==='fs'?{...fs,readFileSync:(file,...args)=>{const value=fs.readFileSync(file,...args);return String(file).endsWith('transitions-library-logic.test.cjs')?value.replace('body,addEventListener(){},','body,handlers:{},addEventListener(t,f){(this.handlers[t]??=[]).push(f);},'):value;}}:require(name),__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(fixtureSource.slice(0,fixtureSource.indexOf('(async()=>{'))+'\nthis.fixture=fixture;',scope);
const make=(source=code,nested=false,reduced=false)=>{const f=scope.fixture(source,false,nested,reduced),E=f.env.E,animate=E.prototype.animate;E.prototype.animate=function(...a){const job=animate.apply(this,a);job.effect={target:this,getKeyframes:()=>job.frames};return job;};E.prototype.getAnimations=function(){return f.animations.filter(a=>a.owner===this&&!a.cancelled)};for(const e of [f.control,f.content,f.sibling])e.closest=()=>({dataset:{stBlur:'8'}});f.env.context.DOMMatrix=class{constructor(){this.m42=0}};
 const sourceCover=new E(),detailCover=new E();sourceCover.dataset.stShared=detailCover.dataset.stShared='cover';f.source.append(sourceCover);f.surface.append(detailCover);f.source.querySelector=selector=>selector==='[data-st-shared="cover"]'?sourceCover:null;const queryAll=f.detail.querySelectorAll;f.detail.querySelectorAll=selector=>selector==='[data-st-shared]'?[detailCover]:selector==='*'?[...queryAll(selector),detailCover]:queryAll(selector);return f;};
const alive=f=>f.animations.filter(a=>!a.cancelled),flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};let passed=0;
(async()=>{
 for(const nested of [false,true]){
  const f=make(code,nested);f.S.expand(f.source,f.detail,{keyboard:true});assert.equal(alive(f).length,0,'Keyboard open must create no owned travel, fade or blur');assert.equal(f.detail.dataset.stInstant,'');assert.equal(f.detail.dataset.stOpen,'true');assert.equal(f.content.style.opacity,'.65','Authored opacity is preserved');assert.equal(f.env.getActive(),f.control);f.S.collapse(f.detail,{keyboard:true});assert.equal(f.detail.dataset.stOpen,'false');assert(!f.detail.dataset.stClosing);assert.equal(f.source.style.visibility,'');assert.equal(f.env.getActive(),f.source);assert.equal(alive(f).length,0);passed++;
 }
 for(const committed of [false,true]){
  const f=make();f.S.expand(f.source,f.detail,{keyboard:false});f.S.collapse(f.detail,{keyboard:false});const outgoing=alive(f);assert(outgoing.length>2);if(committed){outgoing.filter(a=>[f.content,f.control].includes(a.owner)&&a.frames.some(k=>'opacity'in k)).forEach(a=>a.finish());await flush();assert.equal(f.detail.dataset.stClosing,'true','Committed child fades must overlap a still-active shell exit');assert.equal(f.content.style.opacity,0);}
  f.S.expand(f.source,f.detail,{keyboard:true});assert.equal(alive(f).length,0);outgoing.forEach(a=>a.finish());await flush();assert.equal(f.detail.dataset.stOpen,'true');assert.equal(f.detail.inert,false);assert.equal(f.content.style.opacity,'.65');assert.equal(f.control.style.opacity,'.85');passed++;
 }
 const p=make();p.S.expand(p.source,p.detail,{keyboard:false});assert(alive(p).some(a=>a.owner===p.content&&a.frames.some(k=>'filter'in k)),'Pointer content choreography remains available');assert(!alive(p).some(a=>a.owner===p.control&&a.frames.some(k=>'filter'in k||'opacity'in k)),'Pointer Close never fades or blurs');assert(alive(p).some(a=>a.owner===p.control&&a.frames.some(k=>'translate'in k)),'Pointer Close remains attached to moving shell');passed++;
 const nested=make(code,true);nested.S.expand(nested.source,nested.detail,{keyboard:false});assert(!alive(nested).some(a=>a.owner===nested.content),'Nested Close ancestors cannot hide or move its accepted target');assert(alive(nested).some(a=>a.owner===nested.sibling),'Unrelated pointer sibling choreography survives');passed++;
 const redirect=make(),external=new redirect.env.E('button');redirect.control.focus=()=>{redirect.env.setActive(external)};redirect.S.expand(redirect.source,redirect.detail,{keyboard:true});assert.equal(redirect.env.getActive(),external);assert.equal(alive(redirect).length,0);passed++;
 const noKeyboard=code.replace('if (instant || reduced()) {','if (reduced()) {');assert.notEqual(noKeyboard,code);const bad=make(noKeyboard);bad.S.expand(bad.source,bad.detail,{keyboard:true});assert(alive(bad).some(a=>a.owner===bad.content&&a.frames.some(k=>'filter'in k||'transform'in k)),'Removed gate reproduces unreadable keyboard entrance');passed++;
 const noInstantClose=code.replace("  if (instant) { if (scrim) scrim.dataset.stOpen = 'false'; retireExpandReveals(sharedPairs(source, detail)); finish(); return; }",'');assert.notEqual(noInstantClose,code);const badClose=make(noInstantClose);badClose.S.expand(badClose.source,badClose.detail,{keyboard:true});badClose.S.collapse(badClose.detail,{keyboard:true});assert.equal(badClose.detail.dataset.stClosing,'true');assert(alive(badClose).length>0);passed++;
 const delayedClose=code.replace('  if (closeControl) revealFocusedExpandClose(closeControl, true);\n }\n function collapse',"  if (closeControl) play(closeControl, [{opacity: 0}, {opacity: 1}], {ms: 120, delay: 150, channel: 'o', fade: true});\n }\n function collapse");assert.notEqual(delayedClose,code);const badPointer=make(delayedClose);badPointer.S.expand(badPointer.source,badPointer.detail,{keyboard:false});assert(alive(badPointer).some(a=>a.owner===badPointer.control&&a.frames.some(k=>'filter'in k)),'Restoring delayed Close fade reproduces invisible/blurred pointer dismissal');passed++;
 const synthetic=(source,lastKeyboard,trusted=false,detail=0)=>{const f=make(source),doc=f.env.context.document;f.detail.id='test-detail';doc.body.append(f.detail);f.source.dataset.stTarget='test-detail';f.source.closest=selector=>selector==='[data-st-target],[popovertarget]'?f.source:null;doc.handlers[lastKeyboard?'keydown':'pointerdown'][0]({});const event={target:f.source,isTrusted:trusted,detail,preventDefault(){}};doc.handlers.click[0](event);return {f,doc,event};};
 for(const keyboard of [false,true]){const {f,doc,event}=synthetic(code,keyboard);assert.equal(f.detail.dataset.stInstant==='',keyboard);assert.equal(alive(f).length===0,keyboard);doc.handlers.click[0](event);assert.equal(f.detail.dataset.stClosing==='true',!keyboard);passed++;}
 for(const [last,detail,instant] of [[true,1,false],[false,0,true]]){const {f}=synthetic(code,last,true,detail);assert.equal(f.detail.dataset.stInstant==='',instant);assert.equal(alive(f).length===0,instant);passed++;}
 const inherited=make(),doc=inherited.env.context.document;doc.handlers.keydown[0]({});inherited.S.expand(inherited.source,inherited.detail,{keyboard:false});assert(alive(inherited).length>0,'Explicit pointer API policy still overrides native keyboard history');passed++;
 const stale=code.replaceAll('e.isTrusted ? e.detail === 0 : keyboardInput','e.isTrusted && e.detail === 0'),badSynthetic=synthetic(stale,true);assert(alive(badSynthetic.f).length>0,'Old untrusted classification reproduces motion from a keyboard-synthesized click');passed++;
 for(const reopen of [false,true]){const f=make();f.detail.tagName='DIALOG';f.detail.open=false;f.detail.close=()=>{f.detail.open=false};let handled=false;f.detail.showModal=()=>{f.detail.open=true;f.control.focus();if(!handled){handled=true;f.S.collapse(f.detail,{keyboard:true});if(reopen)f.S.expand(f.source,f.detail,{keyboard:true});}};f.S.expand(f.source,f.detail,{keyboard:true});assert.equal(f.detail.dataset.stOpen,String(reopen));assert.equal(f.source.style.visibility,reopen?'hidden':'');assert.equal(alive(f).length,0);passed++;}
 const redirectedNative=make(),nativeElsewhere=new redirectedNative.env.E('input');redirectedNative.detail.tagName='DIALOG';redirectedNative.detail.open=false;redirectedNative.detail.showModal=()=>{redirectedNative.detail.open=true;redirectedNative.env.setActive(nativeElsewhere)};redirectedNative.S.expand(redirectedNative.source,redirectedNative.detail,{keyboard:true});assert.equal(redirectedNative.env.getActive(),nativeElsewhere,'Native autofocus/host redirect is not stolen by a second explicit focus');passed++;
 const withoutNativeGuard=code.replace('  if (nativeFocus && (s.version !== v || !s.open)) return;','');assert.notEqual(withoutNativeGuard,code);const nativeBad=make(withoutNativeGuard);nativeBad.detail.tagName='DIALOG';nativeBad.detail.open=false;nativeBad.detail.close=()=>{nativeBad.detail.open=false};nativeBad.detail.showModal=()=>{nativeBad.detail.open=true;nativeBad.S.collapse(nativeBad.detail,{keyboard:true})};nativeBad.S.expand(nativeBad.source,nativeBad.detail,{keyboard:true});assert.equal(nativeBad.detail.dataset.stOpen,'false');assert.equal(nativeBad.source.style.visibility,'hidden','Without the native focus guard, the stale opening hides the restored source');passed++;
 const nativeReturn=source=>{const f=make(source);f.detail.tagName='DIALOG';f.detail.open=false;f.detail.showModal=()=>{f.detail.open=true;f.control.focus()};f.S.expand(f.source,f.detail,{keyboard:true});f.detail.close=()=>{f.detail.open=false;f.S.expand(f.source,f.detail,{keyboard:false})};f.S.collapse(f.detail,{keyboard:true});return f;};
 const nativeReturned=nativeReturn(code);assert.equal(nativeReturned.detail.dataset.stOpen,'true');assert(alive(nativeReturned).some(a=>a.owner===nativeReturned.content),'Native return-focus reopen must keep its newly owned choreography');passed++;
 const cleanup="   stopAll(surface); qa(detail, '*').forEach(stopAll); if (scrim) stopAll(scrim);\n",oldCleanup=code.replace(cleanup,'').replace("   if (s.version !== v || s.open) return;\n   if (titleFades.size",cleanup+"   if (s.version !== v || s.open) return;\n   if (titleFades.size");assert.notEqual(oldCleanup,code);const nativeCanceled=nativeReturn(oldCleanup);assert.equal(nativeCanceled.detail.dataset.stOpen,'true');assert(!alive(nativeCanceled).some(a=>a.owner===nativeCanceled.content),'Old cleanup after native close cancels the newer content owner');passed++;
 const css=fs.readFileSync(input.replace('.js','.css'),'utf8');assert(css.includes('[data-st="expand"][data-st-instant], [data-st="expand"][data-st-instant] * { transition-property: color, background-color, box-shadow, fill, stroke !important; }'),'Instant restoration must not start CSS opacity/geometry transitions');passed++;
 const html=fs.readFileSync(path.join(path.dirname(input),'gallery.html'),'utf8'),preview=/<ol class="ex-tracks" id="expand-tracks" aria-labelledby="expand-preview-label">([\s\S]*?)<\/ol>/.exec(html);assert(preview);assert.equal((preview[1].match(/<li>/g)||[]).length,3);assert(html.includes('id="expand-preview-label">3-track preview</div>'));for(const total of ['12 tracks','9 tracks','11 tracks'])assert(html.includes(`data-st-shared="meta">${total}</span>`));assert(html.includes('Keyboard changes are instant; reduced motion removes travel and blur.'));passed++;
 console.log(`${passed}/${passed} Card input-policy contracts pass, including six causal negative controls`);
})().catch(e=>{console.error(e);process.exitCode=1});
