// Separate native gate for marked-layout fallback and relocated fixed anchoring.
// Forced support/scope faults are explicit fixtures, not evidence of an older browser.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {cardReadableFindings} from './transitions-library-card-readable.mjs';
const arg=(n,d)=>{const i=process.argv.indexOf(n);return i<0?d:process.argv[i+1];};if(!arg('--playwright'))throw Error('Pass --playwright');
const {chromium}=await import(pathToFileURL(resolve(arg('--playwright'))).href),gallery=resolve(arg('--gallery',fileURLToPath(new URL('../skills/seenry/assets/components/transitions/gallery.html',import.meta.url)))),out=resolve(arg('--out','card-anchor-fallback-results'));mkdirSync(out,{recursive:true});
const spacing=':root:not(#seenry-text-spacing-test) *{line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}:root:not(#seenry-text-spacing-test) p{margin-block-end:2em!important}';
function capture(){
 const source=window.__cardAnchorSource,detail=document.querySelector('#expand-1'),surface=detail.querySelector('.expand-surface'),close=detail.querySelector('[data-st-close]'),paint=surface.querySelector('.st-expand-paint')||surface;
 const alpha=color=>{if(color==='transparent')return 0;const slash=/\/\s*([\d.]+)(%)?\s*\)/.exec(color);if(slash)return Number(slash[1])/(slash[2]?100:1);const rgba=/^rgba\([^)]*,\s*([\d.]+)\)/.exec(color);return rgba?Number(rgba[1]):1;};
 const bounds=e=>{if(e===document.documentElement)return {left:0,top:0,right:innerWidth,bottom:innerHeight};const r=e.getBoundingClientRect(),sx=e.offsetWidth?r.width/e.offsetWidth:1,sy=e.offsetHeight?r.height/e.offsetHeight:1,left=r.left+e.clientLeft*sx,top=r.top+e.clientTop*sy;return {left,top,right:left+e.clientWidth*sx,bottom:top+e.clientHeight*sy};};
 const state=e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect(),ancestors=[];let opacity=Number(c.opacity),display=!e.hidden&&c.display!=='none';for(let p=e.parentElement;p;p=p.parentElement){const s=getComputedStyle(p);opacity*=Number(s.opacity);display&&=!p.hidden&&s.display!=='none';ancestors.push({filter:s.filter,clipPath:s.clipPath,overflowX:s.overflowX,overflowY:s.overflowY,rect:p.getBoundingClientRect().toJSON(),clipRect:bounds(p)});}return {rect:r.toJSON(),opacity,effectiveDisplay:display,visibility:c.visibility,display:c.display,painted:display&&c.visibility==='visible'&&opacity>.01&&r.width>0&&r.height>0,colorAlpha:alpha(c.color),backgroundAlpha:alpha(c.backgroundColor),background:c.backgroundColor,filter:c.filter,clipPath:c.clipPath,transform:c.transform,translate:c.translate,overflowX:c.overflowX,overflowY:c.overflowY,clipRect:bounds(e),ancestorFilters:ancestors.map(a=>({filter:a.filter})),paintAncestors:ancestors,position:c.position,positionVisibility:c.positionVisibility,active:e.matches(':active'),layoutWidth:e.offsetWidth,layoutHeight:e.offsetHeight};};
 const text=e=>{const range=document.createRange();range.selectNodeContents(e);return {...state(e),text:e.textContent.trim(),glyphs:[...range.getClientRects()].filter(r=>r.width>0&&r.height>0).map(r=>r.toJSON())};};
 const c=state(close),hit=document.elementFromPoint(c.rect.left+c.rect.width/2,c.rect.top+c.rect.height/2);c.ownsCenter=hit===close||close.contains(hit);
 return {open:detail.dataset.stOpen,closing:detail.dataset.stClosing||null,instant:detail.hasAttribute('data-st-instant'),sourceHidden:getComputedStyle(source).visibility==='hidden',sourceGroupInert:source.closest('[data-st-expand-sources]').inert,focusedClose:document.activeElement===close,focusVisible:close.matches(':focus-visible'),mode:close.dataset.stClosePinned||null,ghostCount:surface.querySelectorAll('[data-st-ghost]').length,sourceFocused:document.activeElement===source,source:state(source),anchor:source.querySelector('[data-st-close-anchor]')?.getBoundingClientRect().toJSON()||null,close:c,surface:state(surface),paint:state(paint),shell:surface.getBoundingClientRect().toJSON(),viewport:{width:innerWidth,height:innerHeight},blur:document.documentElement.hasAttribute('data-st-blur'),title:text(detail.querySelector('[data-st-shared="title"]')),keyboardText:{cue:text(detail.querySelector('.ex-preview-label')),tracks:[...detail.querySelectorAll('.ex-tracks li')].map(e=>({name:text(e.children[1]),duration:text(e.children[2])}))},animations:[surface,...surface.querySelectorAll('*')].flatMap(e=>e.getAnimations().filter(a=>a.effect?.target===e).map(a=>({type:a.constructor.name,pseudo:a.effect.pseudoElement||null,property:a.transitionProperty||null,playState:a.playState,properties:[...new Set(a.effect.getKeyframes().flatMap(k=>Object.keys(k)))].filter(k=>['opacity','transform','translate','scale','rotate','filter','clipPath'].includes(k))})))};
}
const inside=(a,b)=>a.left>=b.left-.25&&a.top>=b.top-.25&&a.right<=b.right+.25&&a.bottom<=b.bottom+.25;
function readable(row,{pinned=false,title}){assert.equal(row.open,'true');assert.equal(row.instant,true);assert(row.sourceHidden&&row.sourceGroupInert&&row.focusedClose&&row.blur);assert.equal(row.title.text,title);assert(row.title.painted&&row.title.opacity>=.99&&row.title.glyphs.length>0);assert.equal(row.ghostCount,0);for(const g of row.title.glyphs)assert(inside(g,row.shell),'Instant title glyphs must fit the shell');assert.deepEqual(cardReadableFindings(row),[]);assert(row.paint.painted&&row.paint.opacity>=.99&&row.paint.backgroundAlpha>=.99,'Owned backing must be opaque');assert(row.close.painted&&row.close.opacity>=.99&&row.close.ownsCenter&&row.close.filter==='none','Close must be painted, sharp and operable');assert(inside(row.close.rect,row.shell)&&inside(row.close.rect,{left:0,top:0,right:row.viewport.width,bottom:row.viewport.height}));assert.equal(row.animations.filter(a=>!a.pseudo&&a.properties.length).length,0,'Instant path must leave no meaningful Card opacity, geometry or blur job');if(pinned){assert.equal(row.mode,'css');assert.equal(row.close.position,'fixed');assert.equal(row.close.positionVisibility,'always');for(const k of ['left','top','right','bottom'])assert(Math.abs(row.close.rect[k]-row.anchor[k])<=.5,'Relocated Close must resolve to the live source cue');}else assert.equal(row.mode,null,'Safe fallback must never claim fixed placement');}
const profiles=[...['unsupported','unresolved'].flatMap(mode=>[0,1,2].map(index=>({mode,index,width:320,relocated:false,spaced:index===0}))),{mode:'supported',index:2,width:320,relocated:true,spaced:true},{mode:'supported',index:0,width:390,relocated:true,spaced:false}];
const sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),browser=await chromium.launch({headless:true,...(process.env.SEENRY_CHROME_PATH?{executablePath:process.env.SEENRY_CHROME_PATH}:{})}),report={browser:browser.version(),source:Object.fromEntries(['gallery.html','gallery.js','gallery-menu.js','seenry-transitions.js','seenry-transitions.css'].map(n=>[n,sha(join(dirname(gallery),n))])),scope:'Forced unsupported CSS.supports and unresolved anchor-scope fixtures use native layout, trusted pointer/keyboard input and actual first-frame paint. Supported relocated previews test fixed resolution, open resize and spacing. Not an old-browser claim or motion score.',runs:[]};
try{for(const profile of profiles){const run={...profile,status:'running',errors:[]},context=await browser.newContext({viewport:{width:profile.width,height:1000},colorScheme:'light',reducedMotion:'no-preference',serviceWorkers:'block'}),page=await context.newPage();report.runs.push(run);page.on('pageerror',e=>run.errors.push(e.message));await page.route(/^https?:/,r=>r.abort());
 try{if(profile.mode==='unsupported')await page.addInitScript(()=>{const original=CSS.supports.bind(CSS);window.__forcedAnchorSupport=[];CSS.supports=(...args)=>{const forced=args[0]==='position-anchor',native=original(...args),result=forced?false:native;if(forced)window.__forcedAnchorSupport.push({args,native,result});return result;};});await page.goto(pathToFileURL(gallery).href);await page.evaluate(()=>document.fonts.ready);if(!await page.locator('#blur-toggle').isChecked())await page.locator('label.blur-switch').click();assert(await page.evaluate(()=>document.documentElement.hasAttribute('data-st-blur')));if(profile.spaced)await page.addStyleTag({content:spacing});if(profile.mode==='unresolved'){run.nativeSupport=await page.evaluate(()=>({scope:CSS.supports('anchor-scope','all'),anchor:CSS.supports('position-anchor','--test'),inset:CSS.supports('top','anchor(top)'),visibility:CSS.supports('position-visibility','always')}));assert(Object.values(run.nativeSupport).every(Boolean),'Unresolved fixture requires native syntax support');await page.addStyleTag({content:'[data-st-expand-sources]{anchor-scope:all!important}'});}const card=page.locator('[data-key="expand"]');if(profile.relocated){await card.locator('.title-link').click();await page.locator('#library-detail').waitFor({state:'visible'});await page.waitForFunction(()=>{const d=document.querySelector('#library-detail');return d.open&&d.getAnimations({subtree:true}).every(a=>a.playState!=='running'||!Number.isFinite(a.effect.getComputedTiming().endTime));},{},{timeout:5000});}const host=profile.relocated?page.locator('#detail-preview'):card,source=host.locator('.cover-card').nth(profile.index);await source.scrollIntoViewIfNeeded();await page.waitForTimeout(150);run.title=(await source.locator('[data-st-shared="title"]').textContent()).trim();if(profile.mode==='unsupported'&&profile.index===1){run.authoredBefore=await host.locator('.expand-surface').evaluate(e=>{const properties={'background-color':'rgb(255, 255, 255)','background-image':'none','overflow-x':'visible','overflow-y':'clip','transition-property':'all, color','transition-duration':'100ms, 240ms','transition-delay':'0ms, 25ms'};for(const [key,value]of Object.entries(properties))e.style.setProperty(key,value,['background-color','overflow-x','transition-duration'].includes(key)?'important':'');return Object.fromEntries(Object.keys(properties).map(key=>[key,{value:e.style.getPropertyValue(key),priority:e.style.getPropertyPriority(key)}]));});}await source.evaluate(e=>window.__cardAnchorSource=e);await page.evaluate(capture=>{window.__captureCardAnchor=eval('('+capture+')');document.addEventListener('click',e=>{if(!window.__cardAnchorSource.contains(e.target))return;window.__cardAnchorAccepted={trusted:e.isTrusted,detail:e.detail,...window.__captureCardAnchor()};requestAnimationFrame(()=>window.__cardAnchorFirstRAF=window.__captureCardAnchor());});},capture.toString());
  if(profile.relocated){await source.focus();await page.keyboard.press('Enter');}else await source.locator('[data-st-close-anchor]').click();await page.waitForFunction(()=>window.__cardAnchorFirstRAF);run.initial=await page.evaluate(()=>window.__cardAnchorAccepted);run.firstRAF=await page.evaluate(()=>window.__cardAnchorFirstRAF);assert(run.initial.trusted);assert.equal(run.initial.detail,profile.relocated?0:1);readable(run.initial,{pinned:profile.relocated,title:run.title});readable(run.firstRAF,{pinned:profile.relocated,title:run.title});run.supportCalls=await page.evaluate(()=>window.__forcedAnchorSupport||null);if(profile.mode==='unsupported')assert(run.supportCalls.some(x=>x.result===false));if(profile.mode==='unresolved')run.scope=await source.evaluate(e=>getComputedStyle(e.closest('[data-st-expand-sources]')).anchorScope);if(profile.mode==='unresolved')assert.equal(run.scope,'all');
  run.reflow=[];if(profile.relocated){for(const width of [profile.width===320?390:320,profile.width]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const row=await page.evaluate(()=>window.__captureCardAnchor());readable(row,{pinned:true,title:run.title});run.reflow.push({width,...row});}const style=await page.addStyleTag({content:spacing});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const row=await page.evaluate(()=>window.__captureCardAnchor());readable(row,{pinned:true,title:run.title});run.reflow.push({spacing:true,...row});await style.evaluate(e=>e.remove());}
  run.frame=`${profile.mode}-${profile.width}-${profile.index}.png`;await host.screenshot({path:join(out,run.frame),animations:'allow'});const close=host.locator('[data-st-close]').first();await close.evaluate(e=>{const observe=event=>{if(event.target!==e&&!e.contains(event.target))return;document.removeEventListener('click',observe);window.__fallbackClose={observedAt:'document-bubble',currentTargetIsDocument:event.currentTarget===document,trusted:event.isTrusted,targetIsClose:event.target===e||e.contains(event.target),...window.__captureCardAnchor()};};document.addEventListener('click',observe);});await close.click();run.closed=await page.evaluate(()=>window.__fallbackClose);assert(run.closed.trusted&&run.closed.targetIsClose&&run.closed.currentTargetIsDocument);assert.equal(run.closed.observedAt,'document-bubble');if(!profile.relocated){assert.equal(run.closed.open,'false');assert.equal(run.closed.closing,null);assert(run.closed.sourceFocused&&!run.closed.sourceGroupInert);}else{await page.waitForFunction(()=>document.querySelector('#expand-1').dataset.stOpen==='false'&&!document.querySelector('#expand-1').dataset.stClosing);assert(await source.evaluate(e=>document.activeElement===e));}if(run.authoredBefore){run.authoredAfter=await host.locator('.expand-surface').evaluate((e,keys)=>Object.fromEntries(keys.map(key=>[key,{value:e.style.getPropertyValue(key),priority:e.style.getPropertyPriority(key)}])),Object.keys(run.authoredBefore));assert.deepEqual(run.authoredAfter,run.authoredBefore,'Paint transfer must restore mixed authored longhands and priorities');assert.equal(run.closed.paint.backgroundAlpha,1,'Immediate cleanup must commit the restored backing');}
  if(profile.relocated){
   assert.equal(run.closed.closing,'true','Trusted pointer release must not misclassify press feedback as an unresolved anchor');assert.equal(run.closed.mode,'css');
   await source.locator('[data-st-close-anchor]').click();await page.waitForFunction(()=>{const d=document.querySelector('#expand-1');return d.dataset.stOpen==='true'&&d.querySelector('.st-expand-paint')?.getAnimations().every(a=>a.playState!=='running');});
   run.beforeHeldClose=await page.evaluate(()=>window.__captureCardAnchor());assert.equal(run.beforeHeldClose.mode,'css');assert.equal(run.beforeHeldClose.instant,false);
   await close.evaluate(e=>{e.addEventListener('pointerdown',event=>window.__heldCloseDown={trusted:event.isTrusted,targetIsClose:event.target===e||e.contains(event.target),at:performance.now()},{once:true});const observe=event=>{if(event.target!==e&&!e.contains(event.target))return;document.removeEventListener('click',observe);window.__heldCloseRelease={observedAt:'document-bubble',trusted:event.isTrusted,targetIsClose:event.target===e||e.contains(event.target),...window.__captureCardAnchor()};};document.addEventListener('click',observe);});
   const c=run.beforeHeldClose.close.rect;await page.mouse.move((c.left+c.right)/2,(c.top+c.bottom)/2);await page.mouse.down();
   try{await page.waitForFunction(()=>{const e=document.querySelector('#expand-1 [data-st-close]'),m=new DOMMatrixReadOnly(getComputedStyle(e).transform);return e.matches(':active')&&Math.abs(m.m11-.96)<.001&&Math.abs(m.m22-.96)<.001&&!e.getAnimations().some(a=>a.transitionProperty==='transform'&&a.playState==='running');},{},{timeout:1500});run.heldClose=await page.evaluate(()=>({input:window.__heldCloseDown,...window.__captureCardAnchor()}));assert(run.heldClose.input.trusted&&run.heldClose.input.targetIsClose&&run.heldClose.close.active);assert.equal(run.heldClose.mode,'css');assert.equal(run.heldClose.close.layoutWidth,44);assert.equal(run.heldClose.close.layoutHeight,44);assert(run.heldClose.close.rect.width<44&&run.heldClose.close.rect.width>42,'Native active feedback must actually scale the button');assert(inside(run.heldClose.close.rect,run.heldClose.anchor));}finally{await page.mouse.up();}
   run.heldRelease=await page.evaluate(()=>window.__heldCloseRelease);assert(run.heldRelease.trusted&&run.heldRelease.targetIsClose);assert.equal(run.heldRelease.observedAt,'document-bubble');assert.equal(run.heldRelease.closing,'true');assert.equal(run.heldRelease.instant,false);assert.equal(run.heldRelease.mode,'css');assert(run.heldRelease.animations.some(a=>a.type==='Animation'&&a.properties.includes('clipPath')&&a.playState==='running'),'Valid press release must retain a real closing shell motion');await page.waitForFunction(()=>document.querySelector('#expand-1').dataset.stOpen==='false'&&!document.querySelector('#expand-1').dataset.stClosing);assert(await source.evaluate(e=>document.activeElement===e));
  }
  assert.equal(run.errors.length,0);run.status='passed';
 }catch(e){run.status='failed';run.error=e.stack||e.message;run.current=await page.evaluate(()=>window.__captureCardAnchor?.()).catch(()=>null);await page.screenshot({path:join(out,`${profile.mode}-${profile.width}-${profile.index}-FAILED.png`)}).catch(()=>{});}finally{writeFileSync(join(out,`${profile.mode}-${profile.width}-${profile.index}-case.json`),JSON.stringify(run,null,2)+'\n');writeFileSync(join(out,'results.json'),JSON.stringify(report,null,2)+'\n');await context.close();}
}}finally{await browser.close();writeFileSync(join(out,'results.json'),JSON.stringify(report,null,2)+'\n');}
console.log(`${report.runs.filter(r=>r.status==='passed').length}/${profiles.length} marked fallback/relocated anchor native cases passed`);if(report.runs.some(r=>r.status!=='passed'))process.exitCode=1;
