// Deterministic geometry/state checks, not browser/pixel or timing validation.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.argv[2] || path.resolve(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js'),'utf8');
const slice=source.slice(source.indexOf(' const box = r =>'),source.indexOf(' function expandPaint('));
const results=[],pending=[]; const record=(name,fn)=>{fn();results.push({name,pass:true});};
const mix=(a,b,p)=>Object.fromEntries(Object.keys(a).map(k=>[k,a[k]+(b[k]-a[k])*p]));
function transform(s){const m=/translate\(([-\d.e]+)px, ([-\d.e]+)px\) scale\(([-\d.e]+), ([-\d.e]+)\)/.exec(s);assert(m,`finite transform: ${s}`);return m.slice(1).map(Number)}
function frameAt(frames,p){frames=frames.map((f,i)=>({...f,offset:f.offset??i/(frames.length-1)}));const i=frames.findIndex(f=>f.offset>=p),a=frames[Math.max(0,i-1)],b=frames[i<0?frames.length-1:i],q=a===b?0:(p-a.offset)/(b.offset-a.offset);const x=transform(a.transform),y=transform(b.transform);return x.map((v,j)=>v+(y[j]-v)*q)}
class Element{
 constructor(rect,text=false){this.rect={...rect};this.style={};this.motion=null;this.progress=0;this.isConnected=true;this.text=text;this.parentElement=null;this.dataset={};}
 getBoundingClientRect(){let {x,y,w,h}=this.rect;if(this.motion){const [dx,dy,sx,sy]=frameAt(this.motion,this.progress);x+=dx;y+=dy;w*=sx;h*=sy;}return {left:x,top:y,width:w,height:h,right:x+w,bottom:y+h};}
 hasAttribute(k){return this.text&&k==='data-st-shared-text';}contains(){return true;}setAttribute(k,v){this[k]=v;}remove(){this.isConnected=false;}
}
let surface;
const scope={clamp:(x,a,b)=>Math.min(b,Math.max(a,x)),q:()=>surface,stop:e=>e.motion=null,stopAll:e=>e.motion=null,getComputedStyle:e=>({position:'static',clipPath:e.style.clipPath||'none',whiteSpace:e.wrap||'nowrap',wordSpacing:e.wordSpacing||'normal',overflowWrap:e.overflowWrap||'normal'}),ghost:(e,host)=>{const g=new Element(e.rect,e.text);g.parentElement=host;return g},parseInset:v=>{const m=/inset\(([^)]*)\)/.exec(v||'');return m?m[1].split(' ').map(parseFloat):null},play:(e,frames,opts)=>{e.motion=frames;e.progress=0;e.options=opts;return new Promise(resolve=>pending.push(resolve))}};
vm.createContext(scope);vm.runInContext(slice,scope);
const asBox=e=>{const r=e.getBoundingClientRect();return{x:r.left,y:r.top,w:r.width,h:r.height}};
const desktop={sf:{x:110,y:62,w:104,h:154},st:{x:62,y:38,w:234,h:200},af:{x:116,y:68,w:92,h:92},at:{x:74,y:50,w:88,h:88},f:{x:116,y:168,w:84,h:20},t:{x:174,y:54,w:84,h:20}};
const mobile={sf:{x:24,y:108,w:256,h:60},st:{x:30,y:26,w:244,h:220},af:{x:24,y:108,w:60,h:60},at:{x:42,y:38,w:88,h:88},f:{x:96,y:116,w:84,h:20},t:{x:142,y:42,w:84,h:20}};
function fixture(g=desktop){surface=new Element(g.st);const src=new Element(g.sf),paint=new Element(g.st),a=new Element(g.af),d=new Element(g.at),at=new Element(g.f,true),dt=new Element(g.t,true);d.parentElement=dt.parentElement=surface;const state={source:src,paint,version:1};return{g,src,paint,a,d,at,dt,state,pairs:[[a,d],[at,dt]],surface};}
function shellAt(f,r){const b=f.g.st;f.paint.style.clipPath=`inset(${r.y-b.y}px ${b.x+b.w-r.x-r.w}px ${b.y+b.h-r.y-r.h}px ${r.x-b.x}px)`;}
function run(f,toSource){surface=f.surface;const fromShell=f.currentShell||f.g.sf;shellAt(f,fromShell);const job=scope.travel(f.state,{},f.pairs,toSource,f.state.version);const title=f.state.travelers.get(f.dt);return{f,fromShell,toShell:toSource?f.g.sf:f.g.st,title,job};}
function check(run){const {f,title,fromShell,toShell}=run;const first=asBox(title);for(const p of [...Array.from({length:1001},(_,i)=>i/1000),...title.motion.map(f=>f.offset)]){f.d.progress=title.progress=p;const a=asBox(f.d),t=asBox(title),s=mix(fromShell,toShell,p),eps=.001;assert([a,t,s].every(r=>Object.values(r).every(Number.isFinite)));assert(t.x+t.w<=a.x+eps||t.x>=a.x+a.w-eps||t.y+t.h<=a.y+eps||t.y>=a.y+a.h-eps,`title/image overlap at p=${p}`);assert(t.x>=s.x-eps&&t.y>=s.y-eps&&t.x+t.w<=s.x+s.w+eps&&t.y+t.h<=s.y+s.h+eps,`title outside shell at p=${p}`);assert.equal(t.w,f.g.t.w);assert.equal(t.h,f.g.t.h);}
 const offsets=title.motion.map(x=>x.offset);assert.equal(offsets[0],0);assert.equal(offsets.at(-1),1);assert(offsets.every((p,i)=>!i||p>offsets[i-1]));return first;}
function setProgress(r,p){r.f.d.progress=r.title.progress=p;r.f.currentShell=mix(r.fromShell,r.toShell,p);}
record('Rounded corner has continuous analytic tangents at both joins',()=>{const g=desktop,r=scope.titleRoute(g.f,g.t,g.af,g.at,g.sf,g.st,g.t);assert(r.bend>0);const h=1e-7;for(const p of [r.pivot-r.bend,r.pivot+r.bend]){const a=r.point(p-h),b=r.point(p),c=r.point(p+h);for(const k of ['x','y'])assert(Math.abs((b[k]-a[k])/h-(c[k]-b[k])/h)<.01,`tangent jump on ${k}`);}});
record('27 width and source-position combinations preserve readable geometry',()=>{for(const x of [24,110,240])for(const cover of [60,88,110])for(const width of [60,84,108]){const g={sf:{x:x-6,y:62,w:Math.max(cover,width)+12,h:cover+62},st:{x:62,y:38,w:140+width,h:220},af:{x,y:68,w:cover,h:cover},at:{x:74,y:50,w:88,h:88},f:{x,y:76+cover,w:width,h:20},t:{x:174,y:54,w:width,h:20}};check(run(fixture(g),false));}});
const tight={sf:{x:0,y:0,w:100,h:160},st:{x:0,y:0,w:180,h:100},af:{x:0,y:0,w:100,h:100},at:{x:0,y:0,w:100,h:100},f:{x:0,y:108,w:50,h:20},t:{x:108,y:0,w:50,h:20}};
record('Shrinking-height fixture retries a smaller clearance instead of an unsafe straight path',()=>{const g=tight,r=scope.titleRoute(g.f,g.t,g.af,g.at,g.sf,g.st,g.t);assert.equal(r.kind,'corner');assert(r.gap<8);check(run(fixture(g),false));});
record('A zero-clearance-only corner remains routable',()=>{const g={...tight,st:{...tight.st,w:175}},r=scope.titleRoute(g.f,g.t,g.af,g.at,g.sf,g.st,g.t);assert.equal(r.kind,'corner');assert.equal(r.gap,0);check(run(fixture(g),false));});
record('Exact late pivot remains inside its real feasible interval without .999 rounding',()=>{const g={...tight,sf:{x:0,y:0,w:100,h:130},st:{x:0,y:0,w:158.03,h:130}},r=scope.titleRoute(g.f,g.t,g.af,g.at,g.sf,g.st,g.t);assert.equal(r.kind,'corner');assert(r.pivot>.999);const c=r.point(r.pivot),shell=mix(g.sf,g.st,r.pivot);assert(c.x+g.t.w<=shell.x+shell.w+1e-9);const f=fixture(g),open=run(f,false);check(open);setProgress(open,1);f.state.version++;check(run(f,true));});
const impossible={...tight,sf:{x:0,y:0,w:100,h:130},st:{x:0,y:0,w:160,h:100}};
const opposite={...tight,sf:{x:-60,y:-10,w:160,h:120},st:{x:-10,y:-10,w:170,h:120},f:{x:-58,y:0,w:50,h:20}};
for(const [label,g] of [['infeasible corner',impossible],['opposite sides',opposite]])record(`${label} keeps the whole title hidden through retargets instead of crossing the cover`,()=>{assert.equal(scope.titleRoute(g.f,g.t,g.af,g.at,g.sf,g.st,g.t).kind,'fade');const f=fixture(g),open=run(f,false);assert.equal(open.title.style.visibility,'hidden');assert.equal(open.title.motion,null);assert(f.state.titleFades.has(f.dt));setProgress(open,.4);f.state.version++;const close=run(f,true);assert.equal(close.title.style.visibility,'hidden');assert.equal(close.title.motion,null);setProgress(close,.3);f.state.version++;const reopen=run(f,false);assert.equal(reopen.title.style.visibility,'hidden');assert.equal(reopen.title.motion,null);});
record('Safe shared-edge routing is explicitly different from unavailable routing',()=>{const g=mobile;assert.equal(scope.titleRoute(g.f,g.t,g.af,g.at,g.sf,g.st,g.t).kind,'direct');});
record('Desktop title clears image and stays inside shell across 1001 interpolated positions',()=>{const f=fixture();check(run(f,false));});
record('Side-aligned mobile title uses a direct, unscaled path inside the shell',()=>{const f=fixture(mobile),r=run(f,false);assert.equal(r.title.motion.length,33);check(r);});
for(const p of [.08,.28,.5,.72,.92])record(`Reverse at progress ${p}, then reopen at .25 and .75 without jumps or cover collisions`,()=>{
 for(const q of [.25,.75]){const f=fixture(),open=run(f,false);setProgress(open,p);const before=asBox(open.title);f.state.version++;const close=run(f,true);const start=asBox(close.title);assert(Math.abs(start.x-before.x)<.00001&&Math.abs(start.y-before.y)<.00001);check(close);setProgress(close,q);const again=asBox(close.title);f.state.version++;const reopen=run(f,false),restart=asBox(reopen.title);assert(Math.abs(restart.x-again.x)<.00001&&Math.abs(restart.y-again.y)<.00001);check(reopen);}
});
record('Wrapped title paint copies preserve line-break and spacing metrics without scaling',()=>{const g={...mobile,t:{...mobile.t,w:76,h:48}},f=fixture(g);f.dt.wrap='normal';f.dt.wordSpacing='2.56px';f.dt.overflowWrap='anywhere';const r=run(f,false);assert.equal(r.title.style.whiteSpace,'normal');assert.equal(r.title.style.wordSpacing,'2.56px');assert.equal(r.title.style.overflowWrap,'anywhere');check(r);});
record('Ghost home is remeasured after a containing-block shift',()=>{const f=fixture(),r=run(f,false);setProgress(r,.5);r.title.rect.x+=11;r.title.rect.y+=7;const before=asBox(r.title);f.state.version++;const c=run(f,true),after=asBox(c.title);assert.equal(after.x,before.x);assert.equal(after.y,before.y);});
record('Details ride the shell: clipped by its spring and arriving while it is still moving',()=>{const region=source.slice(source.indexOf(' function expand(source'),source.indexOf(' function collapse(detail'));assert(/play\(c, \[\{clipPath:[^\n]*spring: 'expand', channel: 'clip'/.test(region));assert(/play\(c, \[\{transform: `translateY\(\$\{pull\}px\)`\}, \{transform: 'none'\}\], \{spring: 'expand'/.test(region));const d=/\{ms: (\d+), curve: 'F', delay: (\d+), channel: 'o', current: wasClosing, fade: true\}/.exec(region);assert(d&&+d[1]+ +d[2]<233,'details settle before the shell finishes its visible travel');});
const expand=source.slice(source.indexOf(' function expand(source'),source.indexOf(' function collapse(detail'));
record('Reduced-motion expand skips travel and restores opaque owned channels immediately',()=>{const g=desktop,f=fixture(),seen=[];const detail={dataset:{},tagName:'DIV',getBoundingClientRect:()=>f.surface.getBoundingClientRect()},state={version:0};let travels=0;const ctx={keyboardInput:false,holdExpandSources:()=>{},releaseExpandSources:()=>{},retireExpandReveals:()=>{},pinExpandClose:()=>false,restoreExpandClosePin:()=>{},layerState:()=>state,q:(_e,s)=>s.includes('surface')?f.surface:null,qa:()=>[],active:new Set(),sharedPairs:()=>f.pairs,getComputedStyle:()=>({borderRadius:'12px',borderTopLeftRadius:'12px'}),expandPaint:()=>f.paint,reduced:()=>true,play:(el,frames,opts)=>{seen.push({frames,opts});return Promise.resolve(true)},stop:(el,channel)=>{seen.push({el,channel})},travel:()=>{travels++;return Promise.resolve(true)},focusFirst:()=>null};vm.createContext(ctx);vm.runInContext(expand,ctx);ctx.expand(f.src,detail);assert.equal(travels,0);assert(seen.some(x=>x.el===f.surface&&x.channel==='o'));assert(seen.some(x=>x.el===f.paint&&x.channel==='clip'));assert(seen.every(x=>x.channel));assert.equal(detail.dataset.stOpen,'true');assert.equal(detail.inert,false);});
record('Reduced-motion reopen retires an existing hidden fallback title',()=>{const f=fixture(impossible),g=new Element(f.g.t,true),state={version:1,closing:true,travelers:new Map([[f.dt,g]]),titleFades:new Set([f.dt])},detail={dataset:{},tagName:'DIV'};const ctx={keyboardInput:false,holdExpandSources:()=>{},releaseExpandSources:()=>{},retireExpandReveals:()=>{},pinExpandClose:()=>false,restoreExpandClosePin:()=>{},layerState:()=>state,q:(_e,s)=>s.includes('surface')?f.surface:null,qa:()=>[],active:new Set(),sharedPairs:()=>f.pairs,getComputedStyle:()=>({borderRadius:'12px',borderTopLeftRadius:'12px'}),expandPaint:()=>f.paint,reduced:()=>true,play:()=>Promise.resolve(true),stop:scope.stop,stopAll:scope.stopAll,focusFirst:()=>null};vm.createContext(ctx);vm.runInContext(expand,ctx);ctx.expand(f.src,detail);assert.equal(state.travelers.size,0);assert.equal(state.titleFades.size,0);assert.equal(g.isConnected,false);assert.equal(f.dt.style.visibility,'');assert.equal(detail.inert,false);});
(async()=>{
 const flush=async()=>{pending.splice(0).forEach(resolve=>resolve(true));for(let i=0;i<8;i++)await Promise.resolve();};
 await flush();
 for(const g of [impossible,opposite]){
  const f=fixture(g),fades=[],detail={dataset:{},tagName:'DIV',contains:()=>false},active=new Set();shellAt(f,g.sf);
  const ctx={keyboardInput:false,holdExpandSources:()=>{},releaseExpandSources:()=>{},retireExpandReveals:()=>{},pinExpandClose:()=>false,restoreExpandClosePin:()=>{},layerState:()=>f.state,q:(_el,sel)=>sel.includes('surface')?f.surface:null,qa:()=>[],active,sharedPairs:()=>f.pairs,getComputedStyle:e=>({borderRadius:'12px',borderTopLeftRadius:'12px',clipPath:e.style.clipPath||'none'}),expandPaint:()=>f.paint,reduced:()=>false,play:scope.play,travel:scope.travel,stopAll:scope.stopAll,focusFirst:()=>null,doc:{activeElement:null},parseInset:scope.parseInset,cardClip:()=>'',fadeIn:(el,opts)=>{fades.push({el,opts});return Promise.resolve(true)}};
  vm.createContext(ctx);vm.runInContext(expand+source.slice(source.indexOf(' function collapse(detail'),source.indexOf(' /* ---------- Page:',source.indexOf(' function collapse(detail'))),ctx);
  ctx.expand(f.src,detail);assert.equal(f.state.travelers.get(f.dt).style.visibility,'hidden');assert.equal(fades.length,0);await flush();
  assert.equal(fades.length,1);assert.equal(fades[0].el,f.dt);assert.equal(fades[0].opts.ms,80);assert.equal(fades[0].opts.blur,false);assert.equal(f.state.travelers.size,0);assert.equal(f.state.titleFades.size,0);assert.equal(f.dt.style.visibility,'');
  // Model normal WAAPI completion releasing the image transform before the closing action.
  f.d.motion=null;f.paint.style.clipPath='inset(0px 0px 0px 0px)';ctx.collapse(detail);assert.equal(f.state.travelers.get(f.dt).style.visibility,'hidden');await flush();
  assert.equal(fades.length,2);assert.equal(fades[1].el,f.at);assert.equal(fades[1].opts.ms,80);assert.equal(f.state.travelers.size,0);assert.equal(f.state.titleFades.size,0);assert.equal(f.src.style.visibility,'');assert.equal(detail.dataset.stOpen,'false');
 }
 results.push({name:'Fallback title fades only after image arrival on both open and close, with complete cleanup',pass:true});
 const f=fixture(),r=run(f,false);f.state.version++;pending.splice(0).forEach(resolve=>resolve(true));assert.equal(await r.job,false);results.push({name:'Stale traveler completion cannot authorize old cleanup',pass:true});const out=path.join(__dirname,'title-motion-results.json');fs.writeFileSync(out,JSON.stringify({sourceSha256:require('crypto').createHash('sha256').update(source).digest('hex'),scope:'Deterministic geometry and state only; fresh browser capture required',cases:results},null,2)+'\n');console.log(`${results.length}/${results.length} title motion regressions passed; browser retest pending`);})().catch(e=>{console.error(e);process.exitCode=1});
