// Isolated logic contracts against the exact source. This is not browser/pixel QA.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const SOURCE=process.argv[2] || require('path').resolve(__dirname, '../skills/seenry/assets/components/transitions/seenry-transitions.js');
let completed=false;process.on('beforeExit',()=>{if(!completed){console.error('Transition regression harness did not complete');process.exitCode=1}});
let reduce=false, active=null, timers=[], animations=[], copied=false;
function cssStyle(){const values={},priorities={};Object.defineProperties(values,{getPropertyValue:{value:key=>values[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]??''},getPropertyPriority:{value:key=>priorities[key]||''},setProperty:{value:(key,value,priority='')=>{values[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=value;priorities[key]=priority;}}});return values;}
class E {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.dataset={};this.style=cssStyle();this.attrs={};this.handlers={};this.children=[];this.classList={add(){},remove(){},contains(){return false}};this.queries={};this.textContent='';this.isConnected=true;this.clientLeft=this.clientTop=this.scrollLeft=this.scrollTop=0;this.offsetHeight=200;}
 setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k]??null;}hasAttribute(k){return k in this.attrs;}removeAttribute(k){delete this.attrs[k];}
 addEventListener(t,f){(this.handlers[t]??=[]).push(f);}dispatchEvent(e){if(!e.target)e.target=this;for(const f of this.handlers[e.type]??[])f(e);if(e.bubbles&&this.parentElement)this.parentElement.dispatchEvent(e);}
 querySelector(s){return this.queries[s]??(s==='.st-shine'?this.children.find(n=>n.className==='st-shine'):null)??null;}querySelectorAll(){return [];}matches(s){return s==='[data-st]'&&!!this.dataset.st;}closest(){return null;}
 append(...x){this.children.push(...x);for(const n of x){n.parentElement=this;if(n.id)byId[n.id]=n;}}focus(){active=this;}select(){}remove(){this.isConnected=false;if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(n=>n!==this);}getBoundingClientRect(){return {left:0,top:0,width:200,height:44};}contains(n){return this===n;}
 animate(frames,options){let yes,no;let a={frames,options,cancelled:0,finished:new Promise((r,j)=>{yes=r;no=j}),finish(){yes()},cancel(){this.cancelled++;no(new Error('cancelled'));},commitStyles:()=>Object.assign(this.style,frames.at(-1))}; animations.push(a);return a;}
}
let byId={};const body=new E(),document={readyState:'loading',documentElement:new E(),body,addEventListener(){},getElementById:k=>byId[k],querySelector(){return null;},createElement:t=>new E(t),execCommand(){return false;},get activeElement(){return active;}};
const context={document,window:{},navigator:{clipboard:{writeText:async()=>{throw new Error('clipboard denied')}}},matchMedia:()=>({get matches(){return reduce;},addEventListener(){}}),IntersectionObserver:class{observe(){}unobserve(){}},MutationObserver:class{observe(){}},addEventListener(){},setTimeout:(f,ms)=>{timers.push({f,ms});return timers.length;},clearTimeout(){},getComputedStyle:e=>({...e.style,...e.rendered}),Event:class{constructor(t,o={}){this.type=t;Object.assign(this,o);}},CustomEvent:class{constructor(t,o={}){this.type=t;Object.assign(this,o);}},requestAnimationFrame(){}};
vm.createContext(context);vm.runInContext(fs.readFileSync(SOURCE,'utf8'),context,{filename:SOURCE});const S=context.window.SeenryTransitions;
const results=[];const record=(name,pass,observed)=>results.push({name,pass,observed:JSON.parse(JSON.stringify(observed))});
(async()=>{
let e=new E(); e.style.opacity='1';let p1=S.play(e,[{opacity:1},{opacity:0}],{ms:120});let a1=animations.at(-1);e.rendered={opacity:'.42'};let p2=S.play(e,[{opacity:1}],{ms:120});let a2=animations.at(-1);record('WAAPI reversal uses mocked rendered value',a2.frames[0].opacity==='.42'&&a1.cancelled===1,{start:a2.frames[0],cancelled:a1.cancelled});a2.finish();await p1;await p2;record('WAAPI completion cancels animation',a2.cancelled===1,{cancelled:a2.cancelled});
reduce=true;let before=animations.length;await S.play(new E(),[{transform:'translateX(100px)'},{transform:'none'}],{spring:'smooth'});record('Reduced-motion suppresses travel animation',animations.length===before,{animationsCreated:animations.length-before});let p3=S.play(new E(),[{opacity:0,transform:'scale(.5)'},{opacity:1,transform:'none'}],{ms:240,delay:80,fade:true});let a3=animations.at(-1);record('Reduced-motion fade strips transform and caps at100ms',a3.options.duration===100&&a3.options.delay===0&&a3.frames.every(f=>!('transform' in f)),{frames:a3.frames,options:a3.options});a3.finish();await p3;reduce=false;
// Main4.7.2's optional blur must not be reintroduced after reduced-motion filtering.
let blurEl=new E(),blurHost={dataset:{stBlur:'4'}};blurEl.closest=()=>blurHost;
let blurStart=animations.length;let blurJob=S.play(blurEl,[{opacity:0},{opacity:1}],{ms:180,fade:true,current:false});const blurAnims=animations.slice(blurStart);let blurAnim=blurAnims.find(a=>a.frames.some(f=>'opacity' in f))||animations.at(-1);
// v5: blur runs on its own, longer clock beside the fade, so it reads as a focus pull rather than vanishing with the opacity.
record('Opt-in normal-motion fade still receives blur',blurAnims.some(a=>a.frames.some(f=>'filter' in f)),{animations:blurAnims.map(a=>a.frames)});blurAnims.forEach(a=>a.finish());await blurJob;
reduce=true;let reducedBlurJob=S.play(blurEl,[{opacity:0,transform:'translateY(3px)'},{opacity:1,transform:'none'}],{ms:180,fade:true,current:false});let reducedBlurAnim=animations.at(-1);
record('Opt-in blur cannot bypass reduced-motion fade rules',reducedBlurAnim.frames.every(f=>!('filter' in f)&&!('transform' in f))&&reducedBlurAnim.options.duration<=100,{frames:reducedBlurAnim.frames,duration:reducedBlurAnim.options.duration});reducedBlurAnim.finish();await reducedBlurJob;reduce=false;
let b=new E('button');b.dataset.stCopy='example';let copyResult=await S.copy(b);await Promise.resolve();for(const t of timers.filter(t=>t.ms===30))t.f();record('Copy failure must not announce success',b.dataset.stOn!=='true'&&byId['st-live']?.textContent!=='Copied',{asyncClipboard:'rejects',fallbackExecCommand:false,buttonOn:b.dataset.stOn,live:byId['st-live']?.textContent,copyResult});
let input=new E('input'),btn=new E('button'),field=new E();field.dataset.st='clear';field.queries.input=input;field.queries.button=btn;input.value='Mara Alves';S.init(field);before=animations.length;btn.dispatchEvent({type:'click'});record('Input clear animates outgoing text per documented contract',animations.length>before,{valueImmediately:input.value,focused:active===input,animationsCreated:animations.length-before,buttonState:field.dataset.stHasText});
let detail=new E('dialog');detail.dataset.st='drawer';S.init(detail);detail.dataset.st='sheet';S.init(detail);record('Changing detail kind to sheet binds drag handlers',!!detail.handlers.pointerdown,{handlers:Object.keys(detail.handlers),explanation:'gallery initializes drawer once, later changes data-st to sheet and calls init again'});
let morph=new E('button'),path=new E('path');morph.dataset.st='icon-morph';morph.queries['path[data-st-on]']=path;path.dataset.stOn='M1 1 L2 2';path.dataset.stOff='M0 0 L1 1';S.icon(morph,true);record('Gallery Icon swap API updates morph path',!!path.style.d,{stOn:morph.dataset.stOn,d:path.style.d??null,detailAPI:'SeenryTransitions.icon(button, true)'});

// The displayed field state follows the animation; repeated typing supersedes stale completions.
let clearAnim=animations.at(-1);record('Clear control retains shown state until outgoing ink ends',field.dataset.stHasText==='true'&&input.value===''&&active===input,{hasText:field.dataset.stHasText,opacityFrames:clearAnim.frames});
input.value='New text';input.dispatchEvent({type:'input'});await Promise.resolve();await Promise.resolve();record('Typing interrupts clear without stale hidden button',field.dataset.stHasText==='true'&&!btn.disabled&&field.children.length===0,{hasText:field.dataset.stHasText,disabled:btn.disabled,ghosts:field.children.length});
btn.dispatchEvent({type:'click'});let finalClear=animations.at(-1);finalClear.finish();await Promise.resolve();await Promise.resolve();record('Clear completion removes ghost and hides button',field.dataset.stHasText==='false'&&field.children.length===0,{hasText:field.dataset.stHasText,ghosts:field.children.length});
reduce=true;input.value='Reduced';input.dispatchEvent({type:'input'});btn.dispatchEvent({type:'click'});let reducedClear=animations.at(-1);record('Reduced clear preserves semantics with only short opacity fade',input.value===''&&active===input&&reducedClear.options.duration<=100&&reducedClear.frames.every(f=>Object.keys(f).every(k=>k==='opacity')),{frames:reducedClear.frames,duration:reducedClear.options.duration});reducedClear.finish();await Promise.resolve();await Promise.resolve();reduce=false;
S.init(detail);record('Repeated sheet init does not duplicate drag listeners',detail.handlers.pointerdown?.length===1,{pointerdownHandlers:detail.handlers.pointerdown?.length});
// Run the exact gallery close listener under a bubbling event fixture.
const gallery=fs.readFileSync(SOURCE.replace('seenry-transitions.js','gallery.js'),'utf8');
const listenerStart=gallery.indexOf(" detail.addEventListener('st:close'"),listenerEnd=gallery.indexOf('\n for (const card of cards) {',listenerStart);
assert(listenerStart>=0&&listenerEnd>listenerStart,'Gallery close-listener source boundary missing');
const listener=gallery.slice(listenerStart,listenerEnd);let d=new E('dialog'),inner=new E();d.append(inner);let restoreCount=0,hashes=[];
const fixture={detail:d,restoreStage(){restoreCount++},detailCard:null,stageHome:null,setHash:h=>hashes.push(h),category:'All'};vm.createContext(fixture);vm.runInContext(listener,fixture);inner.dispatchEvent({type:'st:close',bubbles:true});record('Nested close preserves detail preview and URL',restoreCount===0&&hashes.length===0,{restoreCount,hashes});d.dispatchEvent({type:'st:close',bubbles:true});record('Closing detail itself restores preview once',restoreCount===1&&hashes.length===1,{restoreCount,hashes});
// Clipboard success and latest-input-wins use controlled async results.
context.navigator.clipboard.writeText=async()=>{};let successButton=new E('button');await S.copy(successButton,'ok');record('Clipboard success reports success after fulfillment',successButton.dataset.stOn==='true'&&successButton.dataset.stCopyStatus==='success',{on:successButton.dataset.stOn,status:successButton.dataset.stCopyStatus});
let pending=[];context.navigator.clipboard.writeText=()=>new Promise((resolve,reject)=>pending.push({resolve,reject}));let concurrent=new E('button');let first=S.copy(concurrent,'old'),second=S.copy(concurrent,'new');pending[1].reject(new Error('denied'));await second;pending[0].resolve();await first;record('Late old clipboard result cannot replace newest failure',concurrent.dataset.stOn==='false'&&concurrent.dataset.stCopyStatus==='error',{on:concurrent.dataset.stOn,status:concurrent.dataset.stCopyStatus});

// An old rejected promise must not fallback-write over a newer successful copy.
let clipboard='';pending=[];let fallbackWrites=0;
context.navigator.clipboard.writeText=value=>new Promise((resolve,reject)=>pending.push({resolve:()=>{clipboard=value;resolve()},reject}));
context.document.execCommand=()=>{fallbackWrites++;clipboard=body.children.findLast(x=>x.tagName==='TEXTAREA')?.value;return true};
let staleCopyButton=new E('button'),oldWrite=S.copy(staleCopyButton,'old'),newWrite=S.copy(staleCopyButton,'new');
pending[1].resolve();await newWrite;pending[0].reject(new Error('late failure'));await oldWrite;
record('Stale clipboard rejection cannot fallback-write old content',clipboard==='new'&&fallbackWrites===0&&staleCopyButton.dataset.stCopyStatus==='success',{clipboard,fallbackWrites,status:staleCopyButton.dataset.stCopyStatus});
context.document.execCommand=()=>false;

// Pointer events bubble through nested sheets; only the nearest sheet may capture.
context.DOMMatrixReadOnly=class{constructor(){this.m42=0}};
let captures=[],outer=new E(),innerSheet=new E(),outerTrigger=new E('button'),innerTrigger=new E('button');outer.dataset.st='sheet';innerSheet.dataset.st='sheet';outer.setAttribute('data-st-drag-handle-only','');outer.append(innerSheet);outer.setPointerCapture=()=>captures.push('outer');innerSheet.setPointerCapture=()=>captures.push('inner');
S.init(outer);S.init(innerSheet);S.open(outer,outerTrigger,{focus:false});S.open(innerSheet,innerTrigger,{focus:false});
let handle=new E();handle.closest=s=>s==='[data-st="sheet"]'?innerSheet:s==='[data-st-drag-handle]'?handle:null;innerSheet.append(handle);
const pointer=(type,y,time)=>({type,target:handle,bubbles:true,isPrimary:true,button:0,pointerId:7,clientY:y,timeStamp:time});
handle.dispatchEvent(pointer('pointerdown',0,0));handle.dispatchEvent(pointer('pointermove',80,80));handle.dispatchEvent(pointer('pointermove',160,120));handle.dispatchEvent(pointer('pointerup',180,140));
record('Nested sheet owns drag without outer capture or dismissal',JSON.stringify(captures)==='["inner"]'&&outerTrigger.attrs['aria-expanded']==='true'&&innerTrigger.attrs['aria-expanded']==='false',{captures,outerExpanded:outerTrigger.attrs['aria-expanded'],innerExpanded:innerTrigger.attrs['aria-expanded']});
captures=[];let bodyContent=new E();bodyContent.closest=s=>s==='[data-st="sheet"]'?outer:null;outer.append(bodyContent);bodyContent.dispatchEvent({...pointer('pointerdown',0,0),target:bodyContent});bodyContent.dispatchEvent({...pointer('pointermove',80,80),target:bodyContent});
record('Scrollable outer detail ignores non-handle drag input',captures.length===0,{captures});
let ownHandle=new E();ownHandle.closest=s=>s==='[data-st="sheet"]'?outer:s==='[data-st-drag-handle]'?ownHandle:null;outer.append(ownHandle);ownHandle.dispatchEvent({...pointer('pointerdown',0,0),target:ownHandle});ownHandle.dispatchEvent({...pointer('pointermove',20,80),target:ownHandle});
record('Dedicated outer handle still starts its own drag',JSON.stringify(captures)==='["outer"]',{captures});

input.type='password';input.value='do-not-show';input.dispatchEvent({type:'input'});btn.dispatchEvent({type:'click'});record('Clear overlay never exposes password text',field.children.at(-1)?.textContent==='•••••••••••',{masked:field.children.at(-1)?.textContent==='•••••••••••'});animations.at(-1).finish();await Promise.resolve();await Promise.resolve();input.type='text';
// State-machine assertions use controlled animation completions, not physical browser timing.
let sheet=new E(),trigger=new E('button');sheet.dataset.st='sheet';S.open(sheet,trigger,{focus:false});S.close(sheet);record('Closing layer becomes inert immediately',sheet.inert===true&&trigger.attrs['aria-expanded']==='false',{inert:sheet.inert,expanded:trigger.attrs['aria-expanded']});let oldExit=animations.at(-1);S.open(sheet,trigger,{focus:false});oldExit.finish();await Promise.resolve();await Promise.resolve();record('Old exit cannot hide layer after reopen',sheet.dataset.stOpen==='true'&&sheet.inert===false&&trigger.attrs['aria-expanded']==='true',{open:sheet.dataset.stOpen,inert:sheet.inert,expanded:trigger.attrs['aria-expanded']});
const html=fs.readFileSync(SOURCE.replace('seenry-transitions.js','gallery.html'),'utf8');const touchRule=html.slice(html.lastIndexOf('/* Touch geometry'));
record('Phone/coarse pointer overrides retain explicit44px targets',/@media \(max-width:700px\), \(pointer:coarse\)/.test(touchRule)&&/\.stage \.replay, \.snippet-copy, \.title-link \{ min-height:44px; \}/.test(touchRule),{note:'Static CSS cascade assertion; rendered bounding boxes still unverified'});

let shimmer=new E();shimmer.textContent='Reviewing your draft';let shimmerJob=S.shimmer(shimmer),sweep=animations.at(-1);record('Shimmer API creates one visible finite2.4s sweep',sweep.options.duration===2400&&!sweep.options.iterations&&sweep.frames.some(f=>f.opacity===1)&&sweep.frames.at(-1).opacity===0,{duration:sweep.options.duration,iterations:sweep.options.iterations??1,lastOpacity:sweep.frames.at(-1).opacity});sweep.finish();await shimmerJob;record('Shimmer completion releases animation and has no working loop',sweep.cancelled===1&&shimmer.dataset.stWorking!=='true',{cancelled:sweep.cancelled,working:shimmer.dataset.stWorking??null});
reduce=true;before=animations.length;await S.shimmer(shimmer);record('Reduced-motion shimmer creates no decorative animation',animations.length===before,{animationsCreated:animations.length-before});reduce=false;
const kitCss=fs.readFileSync(SOURCE.replace('.js','.css'),'utf8');record('Progress CSS rotates loading only, not terminal states',kitCss.includes('[data-st-progress="loading"] .st-progress-ring{animation:st-spin')&&!kitCss.includes('[data-st-progress] .st-progress-ring{animation:'),{note:'Static selector regression; actual browser animation enumeration still pending'});
record('Gallery thinking states run a finite sequence that settles unshimmered',gallery.includes("replay.shimmer = () =>")&&gallery.includes("else if(key==='shimmer') window.galleryReplay?.shimmer?.()")&&gallery.includes("t.dataset.stDone = 'true'")&&!gallery.includes("$('shimmer-text').dataset.stWorking = 'true'"),{note:'Both gallery entry points run the same finite sequence'});
record('Offscreen gallery shimmer cancels its finite sweep',gallery.includes("if(key==='shimmer')target.querySelector('.st-shine')?.getAnimations().forEach(a=>a.cancel())"),{note:'Static offscreen observer contract'});
record('New main header and install controls retain coarse-pointer44px height',html.includes('.theme [role=tab], .blur-switch, .install-copy { min-height:44px; }'),{note:'Static cascade constraint; browser target measurements pending'});
record('Copied preview HTML discloses missing standalone dependencies',gallery.includes('Preview markup, not a standalone component.')&&gallery.includes('Preview HTML (not standalone)')&&html.includes('Gallery styling, image assets and demo actions may also be needed.'),{note:'Copy payload, detail title and visible footer explain scope'});
completed=true;console.log(JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;})();
