// Execute the browser harness's actual CSS support and bounded traversal helpers.
// Event ordering and DOM focus are modeled; these checks do not replace native CI.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const filename=path.join(__dirname,'transitions-library-dialog.browser.mjs'),source=fs.readFileSync(filename,'utf8');
const extract=(start,end)=>{const a=source.indexOf(start),b=source.indexOf(end,a);assert(a>=0&&b>a);return source.slice(a,b);};
const helpers=extract('function backdropState(style){','function inspect(){')+extract('function assertFocusStep(step){','\ntry{')+'\nthis.helpers={backdropState,assertBackdrop,assertFocusStep,traverseFocus};';
function fixture({prefix=false,standard=true,getter=false,standardValue='none',prefixValue=prefix?'none':''}={}){
 const dialog={open:true,inert:false,matches:()=>true},cancel={tagName:'BUTTON',id:'',textContent:'Cancel'},confirm={tagName:'BUTTON',id:'',textContent:'Delete project'},body={tagName:'BODY',id:'',textContent:'Page content'},other={tagName:'BUTTON',id:'background',textContent:'Delete project'};
 dialog.contains=e=>[dialog,cancel,confirm].includes(e);dialog.querySelector=q=>q==='[autofocus]'?cancel:confirm;
 const document={body,activeElement:cancel,querySelector:()=>dialog};
 const context={assert,document,CSS:{supports:p=>p==='backdrop-filter'?standard:p==='-webkit-backdrop-filter'?prefix:false}};
 vm.createContext(context);vm.runInContext(helpers,context);
 const style={backgroundColor:'rgba(0,0,0,.3)',filter:'none',position:'fixed',inset:'0px',getPropertyValue:p=>p==='backdrop-filter'?standardValue:prefixValue};if(getter)style.webkitBackdropFilter=prefixValue;
 return {...context.helpers,dialog,cancel,confirm,body,other,document,style,page(sequence){let i=0;const keys=[];return {keys,keyboard:{press:async key=>{keys.push(key);document.activeElement=sequence[Math.min(i++,sequence.length-1)];}},evaluate:async fn=>vm.runInContext('('+fn.toString()+')()',context)};}};
}
const results=[];async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message.split('\n')[0]});}}
(async()=>{
 await test('unsupported prefixed getter/property serializes empty with explicit support and accepts standard none',()=>{const f=fixture(),s=f.backdropState(f.style);assert.equal(s.webkitGetterSupported,false);assert.equal(s.webkitSupported,false);assert.equal(s.webkitBackdropFilter,'');assert.equal(s.standardSupported,true);assert.equal(JSON.parse(JSON.stringify(s)).webkitBackdropFilter,'');f.assertBackdrop(s,'reduce');});
 await test('supported prefix is measured via CSS property without requiring the camelCase getter',()=>{const f=fixture({prefix:true}),s=f.backdropState(f.style);assert.equal(s.webkitGetterSupported,false);assert.equal(s.webkitSupported,true);assert.equal(s.webkitBackdropFilter,'none');f.assertBackdrop(s,'reduce');});
 await test('normal standard and supported prefix blur are accepted independently',()=>{for(const options of [{standardValue:'blur(6px)'},{standard:false,prefix:true,standardValue:'',prefixValue:'blur(6px)',getter:true}]){const f=fixture(options);f.assertBackdrop(f.backdropState(f.style),'no-preference');}});
 for(const [name,options] of [['standard blur',{standardValue:'blur(6px)'}],['supported prefix blur',{prefix:true,prefixValue:'blur(6px)'}],['unadvertised measured prefix blur',{prefixValue:'blur(6px)'}],['missing supported standard',{standardValue:''}],['missing supported prefix',{prefix:true,prefixValue:''}],['neither supported',{standard:false}]])await test('reduced rejects '+name,()=>{const f=fixture(options);assert.throws(()=>f.assertBackdrop(f.backdropState(f.style),'reduce'));});
 await test('normal rejects missing actual backdrop blur',()=>{const f=fixture();assert.throws(()=>f.assertBackdrop(f.backdropState(f.style),'no-preference'));});
 await test('exact observed forward native boundary sequence reaches both actual controls',async()=>{const f=fixture(),page=f.page([f.confirm,f.body,f.cancel]),a=[],b=[];await f.traverseFocus(page,'Tab','Delete',a);await f.traverseFocus(page,'Tab','Cancel',b);assert.equal(a.length,1);assert.equal(b.length,2);assert(b[0].documentBoundary);assert.equal(b[1].control,'Cancel');});
 await test('reverse native document boundary can precede actual Delete without accepting background',async()=>{const f=fixture(),page=f.page([f.body,f.confirm]),a=[];await f.traverseFocus(page,'Shift+Tab','Delete',a);assert.equal(a.length,2);assert(a[0].documentBoundary);assert.equal(a[1].control,'Delete');});
 await test('direct reverse wrap is accepted without mandating a boundary',async()=>{const f=fixture(),a=[];await f.traverseFocus(f.page([f.confirm]),'Shift+Tab','Delete',a);assert.equal(a.length,1);});
 await test('actual DOM identities reject same-text background action and preserve the failed step',async()=>{const f=fixture(),a=[];let saves=0;await assert.rejects(f.traverseFocus(f.page([f.other]),'Shift+Tab','Delete',a,()=>saves++),/actionable background/);assert.equal(a.length,1);assert.equal(saves,1);assert.equal(a[0].control,null);});
 await test('bounded traversal cannot pass repeated document boundaries without the target',async()=>{const f=fixture(),a=[],page=f.page([f.body]);await assert.rejects(f.traverseFocus(page,'Shift+Tab','Delete',a),/within four steps/);assert.equal(page.keys.length,4);assert.equal(a.length,4);});
 await test('bounded traversal cannot mistake repeated Cancel for Delete',async()=>{const f=fixture(),a=[];await assert.rejects(f.traverseFocus(f.page([f.cancel]),'Shift+Tab','Delete',a),/within four steps/);assert.equal(a.length,4);});
 await test('closed or inert modal cannot pass focus containment',async()=>{for(const mode of ['open','inert']){const f=fixture();f.dialog[mode]=mode==='inert';await assert.rejects(f.traverseFocus(f.page([f.confirm]),'Tab','Delete',[]),/active native modal/);}});
 await test('missing prefix metadata fails closed rather than coercing undefined to empty',()=>{const f=fixture(),s=f.backdropState(f.style);delete s.webkitBackdropFilter;assert.throws(()=>f.assertBackdrop(s,'reduce'));});
 assert(source.includes('r.inputs.push({input,png,first});save();assertPaint(first'), 'First snapshot must be retained before the paint assertion');
 const report={harnessSha256:crypto.createHash('sha256').update(source).digest('hex'),scope:'Actual helper execution with modeled native-focus/CSSOM data; source-pinned failed CI artifacts retained separately',passed:results.filter(x=>x.pass).length,total:results.length,results};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})();
