// Actual harness observer/validator and complete runtime under an explicit modeled
// target-listener microtask checkpoint. Trust flags here are synthetic, not native evidence.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const runtime=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),browser=fs.readFileSync(path.join(__dirname,'transitions-library-close-attachment.browser.mjs'),'utf8'),fixtureSource=fs.readFileSync(path.join(__dirname,'transitions-library-card-input-policy.test.cjs'),'utf8');
const scope={require,__dirname,process:{argv:['node','test',runtime]},console};vm.runInNewContext(fixtureSource.slice(0,fixtureSource.indexOf('const alive='))+'\nthis.makeFixture=make;',scope);
const start=browser.indexOf('// Keyboard accepted-state observer:'),end=browser.indexOf('// End keyboard accepted-state observer.',start);assert(start>=0&&end>start);const observer=browser.slice(start,end);
function make(old=false){const f=scope.makeFixture(),doc=f.env.context.document;f.detail.id='observer-detail';doc.body.append(f.source,f.detail);f.source.dataset.stTarget='observer-detail';f.source.closest=s=>s==='[data-st-target],[popovertarget]'?f.source:null;doc.removeEventListener=(type,fn)=>{doc.handlers[type]=doc.handlers[type].filter(f=>f!==fn)};const rafs=[],window={__closeFrame:()=>({open:f.detail.dataset.stOpen||'false',instant:f.detail.dataset.stInstant==='',visibleSource:f.source.style.visibility!=='hidden'})};let now=0;const context={source:f.source,window,document:doc,performance:{now:()=>++now},requestAnimationFrame:fn=>rafs.push(fn),queueMicrotask,assert};const code=old?observer.replace("document.addEventListener('click',observe);","source.addEventListener('click',event=>queueMicrotask(()=>observe(event))); "):observer;vm.runInNewContext(code+'\nobserveKeyboardOpen(source);this.validate=assertKeyboardObservation;',context);return {...f,doc,window,rafs,validate:context.validate};}
(async()=>{let n=0;for(const descendant of [false,true]){const f=make(),other=new f.env.E('button'),listeners=f.doc.handlers.click.length;for(const fn of [...f.doc.handlers.click])fn({target:other,currentTarget:f.doc,isTrusted:true,detail:1,preventDefault(){}});assert.equal(f.doc.handlers.click.length,listeners);assert.equal(f.window.__keyboardCloseInitial,null);let target=f.source;if(descendant){target=new f.env.E('span');f.source.append(target);target.closest=s=>f.source.closest(s);}const e={target,currentTarget:f.source,isTrusted:true,detail:0,preventDefault(){}};for(const fn of f.source.handlers.click)fn(e);await Promise.resolve();assert.equal(f.window.__keyboardClosePreHandler.open,'false');assert.equal(f.window.__keyboardCloseInitial,null,'Target callback microtask cannot claim the accepted state');e.currentTarget=f.doc;for(const fn of [...f.doc.handlers.click])fn(e);f.validate(f.window.__keyboardCloseInitial,f.window.__keyboardCloseEvent);assert.equal(f.doc.handlers.click.length,listeners-1);assert.equal(f.rafs.length,1,'First RAF remains independently scheduled');for(const mutate of [x=>x.initial.observedAt='target',x=>x.initial.currentTargetIsDocument=false,x=>x.event.trusted=false,x=>x.event.detail=1,x=>x.initial.instant=false]){const x=structuredClone({initial:f.window.__keyboardCloseInitial,event:f.window.__keyboardCloseEvent});mutate(x);assert.throws(()=>f.validate(x.initial,x.event));}n++;}
const old=make(true),e={target:old.source,currentTarget:old.source,isTrusted:true,detail:0,preventDefault(){}};for(const fn of old.source.handlers.click)fn(e);await Promise.resolve();assert.equal(old.window.__keyboardCloseInitial.open,'false');assert.throws(()=>old.validate(old.window.__keyboardCloseInitial,old.window.__keyboardCloseEvent),'Old target-microtask observer must fail before the production document handler');n++;console.log(`${n}/${n} Card observer event-order contracts pass; actual target-microtask mutation reproduces premature observation`);
})().catch(e=>{console.error(e);process.exitCode=1});
