// Complete runtime plus narrowly modeled CSS opacity restoration. This is causal,
// not browser paint evidence: the native early-frame guard must also pass.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),code=fs.readFileSync(input,'utf8'),css=fs.readFileSync(input.replace('.js','.css'),'utf8');
const fixtureSource=fs.readFileSync(path.join(__dirname,'transitions-library-card-input-policy.test.cjs'),'utf8'),scope={require,__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(fixtureSource.slice(0,fixtureSource.indexOf('const alive='))+'\nthis.makeFixture=make;',scope);
const guard='[data-st="expand"] [data-st-close] { transition-property: color, background-color, box-shadow, transform !important; }';assert(css.includes(guard));
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};
async function run(style){const f=scope.makeFixture();let now=0,tween=null;const raw=f.control.style;f.control.style=new Proxy(raw,{set(target,key,value){const before=target[key];target[key]=value;if(key==='opacity'&&before!==''&&Number(before)===0&&value!==before&&!style.includes(guard))tween={start:now,to:value===''?1:Number(value)};return true;}});const computed=f.env.context.getComputedStyle;f.env.context.getComputedStyle=e=>{const c=computed(e);if(e===f.control&&tween)c.opacity=String(tween.to*Math.min(1,(now-tween.start)/100));return c;};f.S.expand(f.source,f.detail,{keyboard:false});f.S.collapse(f.detail,{keyboard:false});const exit=f.animations.findLast(a=>a.owner===f.control&&a.frames.some(k=>'opacity'in k));assert(exit);now=80;exit.finish();await flush();assert.equal(f.detail.dataset.stClosing,'true','Child opacity commitment must overlap a live shell exit');assert.equal(f.control.style.opacity,0);f.S.expand(f.source,f.detail,{keyboard:false});const frames=[];for(const elapsed of [0,16,33,100]){now=80+elapsed;frames.push(Number(f.env.context.getComputedStyle(f.control).opacity));}return frames;}
(async()=>{const good=await run(css);assert.deepEqual(good,[.85,.85,.85,.85]);const bad=await run(css.replace(guard,''));assert.equal(bad[0],0);assert(bad[1]>0&&bad[1]<.85);assert.equal(bad.at(-1),.85);console.log('2/2 committed pointer-Close CSS restoration contracts pass; removed exception reproduces a fresh hidden/attenuated dismissal');})().catch(e=>{console.error(e);process.exitCode=1});
