// Complete production runtime plus the pending native visibility transition observed
// in Chrome153 at063592c. This is a causal lifecycle model, not rendered acceptance.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),code=fs.readFileSync(input,'utf8');
const fixture=fs.readFileSync(path.join(__dirname,'transitions-library-fixed-close-anchor.test.cjs'),'utf8'),scope={require,__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(fixture.slice(0,fixture.indexOf('let passed='))+'\nthis.makeFixture=make;',scope);
const keys=['transition-property','transition-duration','transition-delay'];
const saved=e=>Object.fromEntries(keys.map(k=>[k,{value:e.style.getPropertyValue(k),priority:e.style.getPropertyPriority(k)}]));
function make(candidate=code,{supported=true,native=false,priority='important'}={}){
 const f=scope.makeFixture(100,237,candidate),old=f.env.context.getComputedStyle,jobs=[],memo=new Map();let focusCalls=0;
 f.env.context.CSS.supports=()=>supported;f.env.setActive(f.source);
 for(const [key,value]of Object.entries({'transition-property':'all, color','transition-duration':'100ms, 240ms','transition-delay':'0ms, 25ms'}))f.surface.style.setProperty(key,value,key==='transition-delay'?'':priority);
 const original=saved(f.surface),raw=f.surface.getAnimations;
 const other={effect:{target:f.surface},transitionProperty:'color',cancelled:0,cancel(){this.cancelled++}};
 const pseudo={effect:{target:f.surface,pseudoElement:'::before'},transitionProperty:'visibility',cancelled:0,cancel(){this.cancelled++}};
 const deliberate={effect:{target:f.surface},cancelled:0,cancel(){this.cancelled++}};jobs.push(other,pseudo,deliberate);
 f.surface.getAnimations=()=>[...raw.call(f.surface),...jobs.filter(j=>!j.cancelled)];
 const split=(v,d)=>String(v||d).split(',').map(x=>x.trim()),ms=x=>parseFloat(x)*(String(x).endsWith('ms')?1:1000);
 function computed(el){const cs=old(el);if(el===f.control)return {...cs,visibility:computed(f.surface).visibility};if(el!==f.surface)return {...cs,visibility:el.style.visibility||'visible'};
  const target=el.style.visibility==='hidden'?'hidden':(f.detail.dataset.stOpen==='true'||f.detail.dataset.stClosing==='true')?'visible':'hidden';
  let row=memo.get(el);if(!row){row={target:'hidden',value:'hidden',job:null};memo.set(el,row);}
  if(target!==row.target){let duration=0,delay=0;const props=split(cs.transitionProperty,'none'),ds=split(cs.transitionDuration,'0s'),ls=split(cs.transitionDelay,'0s');props.forEach((p,i)=>{if(p==='all'||p==='visibility'){duration=ms(ds[i%ds.length]);delay=ms(ls[i%ls.length]);}});const from=row.job&&!row.job.cancelled?row.job.from:row.value;row.target=target;
   if(duration||delay){const job={effect:{target:el},transitionProperty:'visibility',from,to:target,cancelled:0,cancel(){this.cancelled++;row.value=row.target;}};row.job=job;jobs.push(job);}else{if(row.job)row.job.cancelled++;row.job=null;row.value=target;}
  }
  return {...cs,visibility:row.job&&!row.job.cancelled?row.job.from:row.value};
 }
 f.env.context.getComputedStyle=computed;f.control.focus=()=>{focusCalls++;if(computed(f.control).visibility==='visible'){f.env.setActive(f.control);f.control.dispatchEvent({type:'focus'});}};
 if(native){f.detail.tagName='DIALOG';f.detail.open=false;f.detail.showModal=()=>{f.detail.open=true;f.control.focus();};f.detail.close=()=>{f.detail.open=false;};}
 return {...f,jobs,other,pseudo,deliberate,original,computed,focusCalls:()=>focusCalls};
}
const observed=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/transitions/native-card-focus-visibility-observed.json')));
assert.equal(observed.cases[0].focusedCloseAfterNative,false);assert.equal(observed.cases[0].surfaceVisibility,'hidden');assert(observed.cases[0].visibilityTransitions.some(a=>a.pending&&a.currentTime===0&&a.keyframes[0].visibility==='hidden'&&a.keyframes[1].visibility==='visible'));assert(observed.cases.slice(1).every(r=>r.focusedCloseAfterNative&&r.documentBubbleFocusedClose&&r.firstRAFFocusedClose));
let passed=0;
for(const supported of [true,false])for(const native of [false,true])for(const priority of ['', 'important']){
 const f=make(code,{supported,native,priority});f.S.expand(f.source,f.detail,{keyboard:false});assert.equal(f.env.getActive(),f.control);assert.equal(f.focusCalls(),1);assert.equal(f.computed(f.control).visibility,'visible');assert.deepEqual(saved(f.surface),f.original);assert.equal(f.control.dataset.stClosePinned,supported?'css':undefined);assert.equal(f.other.cancelled,0);assert.equal(f.pseudo.cancelled,0);assert.equal(f.deliberate.cancelled,0);
 f.S.collapse(f.detail,{keyboard:true});assert.equal(f.detail.dataset.stOpen,'false');assert.equal(f.computed(f.control).visibility,'hidden');assert.deepEqual(saved(f.surface),f.original);assert.equal(f.env.getActive(),f.source);passed++;
}
const start=code.indexOf(' function transferExpandVisibility('),end=code.indexOf(' function expand(source',start);assert(start>0&&end>start);const omitted=code.slice(0,start)+' function transferExpandVisibility(detail, update) { return update(); }\n'+code.slice(end);
for(const supported of [true,false]){const bad=make(omitted,{supported});bad.S.expand(bad.source,bad.detail,{keyboard:false});assert.equal(bad.focusCalls(),1);assert.equal(bad.env.getActive(),bad.source,'Removed semantic handoff retains source focus');assert(bad.jobs.some(j=>j.transitionProperty==='visibility'&&!j.effect.pseudoElement&&!j.cancelled));passed++;}
const noCommit=code.replace('   for (const {el} of held) getComputedStyle(el).visibility;','');assert.notEqual(noCommit,code);const uncommitted=make(noCommit);uncommitted.S.expand(uncommitted.source,uncommitted.detail,{keyboard:false});assert.equal(uncommitted.env.getActive(),uncommitted.source,'Restoring clocks before committing visibility recreates the pending transition');passed++;
const retire="   for (const {el} of held) for (const animation of el.getAnimations?.() || []) if (animation.effect?.target === el && !animation.effect.pseudoElement && animation.transitionProperty === 'visibility') animation.cancel();";assert(code.includes(retire));
for(const omit of [false,true]){const f=make(omit?code.replace(retire,''):code);f.detail.dataset.stOpen='true';f.computed(f.surface);assert(f.jobs.some(j=>j.transitionProperty==='visibility'&&!j.effect.pseudoElement));f.S.expand(f.source,f.detail,{keyboard:false});assert.equal(f.env.getActive()===f.control,!omit,'A pending inherited visibility transition must retire before focus');passed++;}
const closeLine="   transferExpandVisibility(detail, () => { detail.dataset.stOpen = 'false'; delete detail.dataset.stClosing; active.delete(detail); });";
assert(code.includes(closeLine));const noClose=make(code.replace(closeLine,"   detail.dataset.stOpen = 'false'; delete detail.dataset.stClosing; active.delete(detail);"));noClose.S.expand(noClose.source,noClose.detail,{keyboard:false});noClose.S.collapse(noClose.detail,{keyboard:true});assert.equal(noClose.detail.dataset.stOpen,'false');assert.equal(noClose.computed(noClose.control).visibility,'visible','Removed final-state transfer leaves a logically closed child visible');passed++;
const hidden=make();hidden.surface.style.visibility='hidden';hidden.S.expand(hidden.source,hidden.detail,{keyboard:false});assert.equal(hidden.computed(hidden.control).visibility,'hidden','Explicit authored hidden content must stay hidden');assert.equal(hidden.surface.style.visibility,'hidden');passed++;
const redirected=make(),outside=new redirected.env.E('button');redirected.control.addEventListener('focus',()=>redirected.env.setActive(outside));redirected.S.expand(redirected.source,redirected.detail,{keyboard:false});assert.equal(redirected.env.getActive(),outside);assert.equal(redirected.focusCalls(),1);passed++;
for(const reopen of [false,true]){const f=make(code,{native:true});let first=true;const nativeShow=f.detail.showModal;f.detail.showModal=()=>{nativeShow();if(first){first=false;f.S.collapse(f.detail,{keyboard:true});if(reopen)f.S.expand(f.source,f.detail,{keyboard:true});}};f.S.expand(f.source,f.detail,{keyboard:false});assert.equal(f.detail.dataset.stOpen,String(reopen));assert.equal(f.source.style.visibility,reopen?'hidden':'');assert.equal(f.computed(f.control).visibility,reopen?'visible':'hidden');assert.deepEqual(saved(f.surface),f.original);passed++;}
const changed=make(code,{native:true});const nativeShow=changed.detail.showModal;changed.detail.showModal=()=>{nativeShow();changed.surface.style.setProperty('transition-property','color','important');};changed.S.expand(changed.source,changed.detail,{keyboard:false});assert.equal(changed.surface.style.getPropertyValue('transition-property'),'color','Host declaration updates during native focus remain owned by the host');assert.equal(changed.surface.style.getPropertyPriority('transition-property'),'important');assert.equal(changed.focusCalls(),1);passed++;
(async()=>{for(const supported of [true,false]){const f=make(code,{supported});f.env.setReduced(true);f.S.expand(f.source,f.detail,{keyboard:false});assert.equal(f.env.getActive(),f.control);f.S.collapse(f.detail,{keyboard:false});for(const a of f.animations)if(!a.cancelled)a.finish();for(let i=0;i<10;i++)await Promise.resolve();assert.equal(f.detail.dataset.stClosing,undefined);assert.equal(f.computed(f.control).visibility,'hidden');assert.deepEqual(saved(f.surface),f.original);passed++;}console.log(`${passed}/${passed} full-runtime semantic visibility controls pass; supported/fallback native focus, closed visibility, authored priorities, redirects and reentrant native ownership covered. Native gate still required.`);})().catch(e=>{console.error(e);process.exitCode=1});
