// Bounded CI-only source-unchanged supplement. No animation pausing or product patches.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {finalizeSupplementCase,finalizeSupplementReport,prepareDialogSupplement,assertDialogSupplementPreparation,fixturePins,spacingCSS,installSupplement,appendBounded,boundedFontsReady,collectPerformanceFlow,assertSettlement,assertControl,assertTrustedSequence,assertClosedOutcome,assertSpacing,assertZoom200} from './transitions-library-dialog-supplement-helpers.mjs';
const arg=(name,fallback)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1];};
assert.equal(process.env.CI,'true','CI-only harness; do not launch a local browser in the restricted workspace');
assert(arg('--playwright')&&arg('--gallery'),'Pass the existing pinned Playwright and exact unchanged gallery');
const gallery=resolve(arg('--gallery')),out=resolve(arg('--out','dialog-supplement-results'));mkdirSync(out,{recursive:true});
const sha=f=>createHash('sha256').update(readFileSync(f)).digest('hex');
const source=Object.fromEntries(Object.keys(fixturePins).map(name=>[name,sha(join(dirname(gallery),name))]));
assert.deepEqual(source,fixturePins,'The exact PR65 product fixture must be unchanged');
let commit;try{commit=execFileSync('git',['rev-parse','HEAD'],{cwd:dirname(gallery),encoding:'utf8'}).trim();}catch{commit=null;}
const report={schema:1,productBaseCommit:'53c56304749ecb84eea8d6a9b18d146cf25d6ed7',executionCommit:commit,source,harness:sha(fileURLToPath(import.meta.url)),helpers:sha(fileURLToPath(new URL('./transitions-library-dialog-supplement-helpers.mjs',import.meta.url))),scope:'Targeted diagnostic supplement:1440 normal-motion held states and actual keyboard focus paint in two themes;320 four-property text spacing in two themes;1440 Blur switch contract, post-demo-confirmation outcome, one scoped unpaused performance flow and genuine browser-zoom capability. No full preference matrix, physical-device evidence, pause/seek, screencast duplication, calibrated score or real deletion.',runs:[]};
const save=()=>{for(const r of report.runs)writeFileSync(join(out,r.label+'.json'),JSON.stringify(r,null,2)+'\n');writeFileSync(join(out,'results.json'),JSON.stringify({...report,runs:report.runs.map(({label,status,error})=>({label,status,error,file:label+'.json'}))},null,2)+'\n');};
save();let chromium;try{({chromium}=await import(pathToFileURL(resolve(arg('--playwright'))).href));}catch(error){report.bootstrapError=error.stack||String(error);save();throw error;}
let browser;
const selectors={Invoker:'#dialog-trigger',Cancel:'#dialog-1 [autofocus]',Delete:'#dialog-1 .dialog-destructive'};
async function newCase(label,{width=1440,theme='light',viewport=true}={},fn){
 const run={label,width,height:900,theme,motion:'no-preference',status:'running',captures:[],console:[],pageErrors:[],requestsFailed:[],actions:[]};report.runs.push(run);save();let context,page;
 try{
  context=await browser.newContext({viewport:viewport?{width,height:900}:null,colorScheme:theme,reducedMotion:'no-preference',serviceWorkers:'block',acceptDownloads:false});page=await context.newPage();page.setDefaultTimeout(4000);page.setDefaultNavigationTimeout(8000);
  page.on('console',msg=>{if(['warning','error'].includes(msg.type()))appendBounded(run,'console',{hostAt:performance.now(),type:msg.type(),text:msg.text(),location:msg.location()});});page.on('pageerror',e=>appendBounded(run,'pageErrors',{hostAt:performance.now(),message:e.message,stack:e.stack}));page.on('requestfailed',r=>appendBounded(run,'requestsFailed',{url:r.url(),failure:r.failure()}));
  await page.route(/^https?:/,route=>route.abort());await page.goto(pathToFileURL(gallery).href);run.fontReadiness=await page.evaluate(boundedFontsReady,{timeoutMs:2500});await page.locator('#library-search').fill('Dialog');await page.locator('#dialog-trigger').scrollIntoViewIfNeeded();await page.mouse.move(1,1);await page.evaluate(installSupplement);run.preparation=await page.evaluate(prepareDialogSupplement,{expectedQuery:'Dialog',timeoutMs:2500,maxObservations:240});assertDialogSupplementPreparation(run.preparation);save();await fn(page,run);run.collectionComplete=true;if(run.inventoryIncomplete)throw Error('Console/error/request inventory cap reached; evidence incomplete');if(run.pageErrors.length)throw Error('Page errors recorded');
 }catch(error){run.status='failed';run.error=error.stack||String(error);if(page){run.partialPerformance=await page.evaluate(()=>window.__supplementStopPerf?.('case-failed')??window.__supplementPerf??null).catch(e=>({retentionError:String(e)}));save();await page.screenshot({path:join(out,label+'-FAILED.png'),animations:'allow',timeout:3000}).catch(e=>{run.failureScreenshotError=String(e);});}}
 finally{if(page){const retained=await page.evaluate(()=>({observations:window.__dialogSupplement||null,performance:window.__supplementStopPerf?.('case-finalization')??window.__supplementPerf??null,fontReadiness:window.__dialogFontsReadiness||null,preparation:window.__dialogSupplementPreparation||null})).catch(e=>({error:String(e)}));run.observations=retained.observations??retained;run.preparation=retained.preparation??run.preparation;run.partialPerformance=retained.performance??run.partialPerformance;run.fontReadiness=retained.fontReadiness??run.fontReadiness;}save();await finalizeSupplementCase(run,async()=>{if(context)await context.close();});save();console.log(label+': '+run.status);}
}
const mark=(page,phase)=>page.evaluate(phase=>{window.__dialogSupplement.phase=phase;},phase);
async function settle(page,run,phase,requireOpen=null){await mark(page,phase);const result=await page.evaluate(o=>window.__supplementSettle(o),{timeoutMs:1800,requireOpen});run.actions.push({phase,settlement:result});save();assertSettlement(result);return result.snapshot;}
async function shot(page,run,label){const capture={label,file:run.label+'-'+label+'.png',status:'requested',before:await page.evaluate(()=>window.__supplementState()),hostRequestAt:performance.now()};run.captures.push(capture);save();try{await page.screenshot({path:join(out,capture.file),animations:'allow',timeout:4000});capture.hostCompletedAt=performance.now();capture.sha256=sha(join(out,capture.file));capture.status='captured';}catch(e){capture.status='failed';capture.error=String(e);throw e;}finally{capture.after=await page.evaluate(()=>window.__supplementState()).catch(e=>({error:String(e)}));save();}return capture;}
async function open(page,run,label){await mark(page,label+'-trusted-open');await page.locator(selectors.Invoker).click();return settle(page,run,label+'-open-settled',true);}
async function close(page,run,label){await mark(page,label+'-trusted-Cancel');await page.locator(selectors.Cancel).click();const s=await settle(page,run,label+'-closed-settled',false);assertClosedOutcome(s);return s;}
async function controlStates(page,run,name){
 assertDialogSupplementPreparation(run.preparation);
 if(name!=='Invoker'&&!await page.locator('#dialog-1').evaluate(d=>d.open))await open(page,run,name);
 const control=page.locator(selectors[name]);await control.scrollIntoViewIfNeeded();await page.mouse.move(1,1);let s=await settle(page,run,name+'-rest',name!=='Invoker');assertControl(s,name,'rest');await shot(page,run,name+'-rest');
 const rest=s.controls[name].rect;await mark(page,name+'-actual-hover');await control.hover();s=await settle(page,run,name+'-hover-settled',name!=='Invoker');assertControl(s,name,'hover');for(const k of ['x','y','width','height'])assert(Math.abs(s.controls[name].rect[k]-rest[k])<=.25,'Hover geometry stays stationary');await shot(page,run,name+'-hover');
 const begin=await page.evaluate(()=>window.__dialogSupplement.events.length);await mark(page,name+'-trusted-held-pointer');await page.mouse.down();s=await settle(page,run,name+'-held-settled',name!=='Invoker');assertControl(s,name,'held');await shot(page,run,name+'-held');
 await mark(page,name+'-trusted-release');await page.mouse.up();s=await settle(page,run,name+'-released-settled',name==='Invoker');const events=await page.evaluate(begin=>window.__dialogSupplement.events.slice(begin),begin);assertTrustedSequence(events,name);if(name!=='Invoker')assertClosedOutcome(s);else assert(s.open&&s.modal&&!s.inert);await shot(page,run,name+'-release');
 return s;
}
async function nativeAX(page,selector){const session=await page.context().newCDPSession(page);try{await session.send('Accessibility.enable');const {root}=await session.send('DOM.getDocument'),{nodeId}=await session.send('DOM.querySelector',{nodeId:root.nodeId,selector});assert(nodeId);const {nodes}=await session.send('Accessibility.getPartialAXTree',{nodeId,fetchRelatives:false});return nodes.map(n=>({ignored:n.ignored,role:n.role?.value,name:n.name?.value,properties:n.properties}));}finally{await session.detach();}}
async function blurContract(page,run){
 run.blurContract=[];
 for(const checked of [false,true]){if(await page.locator('#blur-toggle').isChecked()!==checked){await mark(page,'Blur-trusted-toggle-'+checked);await page.locator('label.blur-switch').click();await settle(page,run,'Blur-toggle-settled-'+checked,false);}const ax=await nativeAX(page,'#blur-toggle');assert(ax.some(n=>n.role==='switch'&&n.name==='Blur on fades'&&n.properties?.some(p=>p.name==='checked'&&String(p.value.value)===String(checked))));await open(page,run,'Blur-'+checked);const s=await page.evaluate(()=>window.__supplementState());assert.equal(s.blur.checked,checked);assert.equal(s.blur.rootAttribute,checked);run.blurContract.push({checked,ax,state:s});await shot(page,run,'Blur-'+checked+'-native-backdrop');await close(page,run,'Blur-'+checked);}
 run.blurObservation={visibleLabel:run.blurContract[0].state.blur.visibleLabel,accessibleName:run.blurContract[0].state.blur.ariaLabel,backdropBefore:run.blurContract[0].state.backdrop,backdropAfter:run.blurContract[1].state.backdrop,scope:'Measured switch and native backdrop separately. A difference, or no difference, is reported; no assumed product contract or behavioral edit.'};save();
}
try{
 browser=await chromium.launch({headless:true,...(process.env.SEENRY_CHROME_PATH?{executablePath:process.env.SEENRY_CHROME_PATH}:{})});report.browser=browser.version();save();
 for(const theme of ['light','dark'])await newCase('1440-'+theme+'-controls',{theme},async(page,run)=>{
  run.demoBefore=await page.locator('#dialog-trigger').evaluate(t=>({appText:t.closest('.app').textContent.trim(),invokerText:t.textContent.trim()}));
  await controlStates(page,run,'Invoker');await controlStates(page,run,'Cancel');await controlStates(page,run,'Delete');
  run.demoAfter=await page.locator('#dialog-trigger').evaluate(t=>({appText:t.closest('.app').textContent.trim(),invokerText:t.textContent.trim()}));assert.deepEqual(run.demoAfter,run.demoBefore,'Demo confirmation closes the modal and does not delete the project');run.confirmationOutcome={scope:'Demo only; Delete project is a close action with no real deletion',state:await page.evaluate(()=>window.__supplementState())};assertClosedOutcome(run.confirmationOutcome.state);
  await page.locator(selectors.Invoker).focus();await mark(page,'trusted-keyboard-Enter');await page.keyboard.press('Enter');let s=await settle(page,run,'Cancel-keyboard-focus',true);assertControl(s,'Cancel','keyboard-focus');await shot(page,run,'Cancel-keyboard-focus');await mark(page,'trusted-keyboard-Tab');await page.keyboard.press('Tab');s=await settle(page,run,'Delete-keyboard-focus',true);assertControl(s,'Delete','keyboard-focus');await shot(page,run,'Delete-keyboard-focus');await mark(page,'trusted-keyboard-Escape');await page.keyboard.press('Escape');s=await settle(page,run,'Escape-final-state',false);assertClosedOutcome(s);assertControl(s,'Invoker','keyboard-focus');await shot(page,run,'Invoker-keyboard-focus');
 });
 for(const theme of ['light','dark'])await newCase('320-'+theme+'-text-spacing',{width:320,theme},async(page,run)=>{
  await page.addStyleTag({content:spacingCSS});run.authorizedTestOverride={scope:'User text-spacing test only; source bytes unchanged',css:spacingCSS};await page.locator(selectors.Invoker).scrollIntoViewIfNeeded();await open(page,run,'spacing');const s=await settle(page,run,'spacing-final',true);run.spacingState=s;run.spacingAssertionScope='Measured computed spacing, text/control rectangles and intended hit ownership; not complete pixel paint or contrast acceptance';assertSpacing(s);await shot(page,run,'decision-and-actions');
  await page.locator(selectors.Cancel).focus();await page.keyboard.press('Tab');run.deleteKeyboardReachable=await page.locator(selectors.Delete).evaluate(n=>document.activeElement===n);assert(run.deleteKeyboardReachable);await mark(page,'spacing-trusted-keyboard-Delete');await page.keyboard.press('Enter');const final=await settle(page,run,'spacing-final-closed',false);assertClosedOutcome(final);await shot(page,run,'post-confirmation');
 });
 await newCase('1440-light-blur-contract',{},blurContract);
 await newCase('1440-light-unpaused-performance',{},async(page,run)=>{
  await settle(page,run,'performance-precondition',false);const session=await page.context().newCDPSession(page);
  const p=await collectPerformanceFlow({page,session,run,save,flow:async()=>{await mark(page,'performance-trusted-open');await page.locator(selectors.Invoker).click();await page.waitForFunction(()=>{const d=document.querySelector('#dialog-1');return d.open&&!d.inert&&d.getAnimations({subtree:true}).length===0;});await mark(page,'performance-trusted-Cancel');await page.locator(selectors.Cancel).click();await page.waitForFunction(()=>!document.querySelector('#dialog-1').open&&document.activeElement===document.querySelector('#dialog-trigger'));}});
  const deltas=p.rafTimes.slice(1).map((t,i)=>t-p.rafTimes[i]);assert(deltas.length>=2);run.scopedSummary={durationMs:p.finishedAt-p.startedAt,rafSamples:p.rafTimes.length,rafIntervalsMs:deltas,maxRAFIntervalMs:Math.max(...deltas),longTasksSupported:p.supported,longTaskCount:p.longTasks.length,totalLongTaskMs:p.longTasks.reduce((s,t)=>s+t.duration,0),scope:'One unpaused trusted open/Cancel flow on this CI runner. Lightweight post-production logical-event observers and RAF/long-task/CDP measurement are active. No PNG capture, full paint walk, animation pause, CPU throttle or calibrated performance score during measured window.'};assertClosedOutcome(await settle(page,run,'performance-final',false));
 });
 await newCase('native-browser-200-percent-zoom',{viewport:false},async(page,run)=>{
  run.route={kind:'documented-browser-zoom-keyboard-shortcut-capability-probe',headless:true,platform:process.platform,shortcut:process.platform==='darwin'?'Meta++':'Control++',docs:['https://support.google.com/chrome/answer/96810','https://playwright.dev/docs/api/class-keyboard'],prohibitedSubstitutesUsed:false,scope:'Documented native browser zoom shortcut attempted via existing Playwright keyboard. Actual layout zoom must be independently observed; dispatched keys alone are not zoom evidence.'};
  const read=()=>page.evaluate(()=>({at:performance.now(),dpr:devicePixelRatio,innerWidth,innerHeight,outerWidth,outerHeight,visualScale:visualViewport.scale,visualWidth:visualViewport.width,cssZoom:getComputedStyle(document.documentElement).zoom}));
  await page.locator(selectors.Invoker).focus();await page.keyboard.press(process.platform==='darwin'?'Meta+0':'Control+0');run.before=await read();run.attempts=[];
  // Five standard increments from100% reach200% if this runtime honors browser accelerators.
  for(let i=0;i<5;i++){await page.keyboard.press(run.route.shortcut);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));run.attempts.push(await read());}
  run.after=await read();try{assertZoom200(run.before,run.after);}catch(error){run.status='blocked';run.blocker={check:'Actual200% browser zoom',reason:error.message,before:run.before,after:run.after,capability:'Existing headless Chromium keyboard route did not establish genuine200% browser zoom. Browser UI/extension/system input routes are not provided by this CI harness; no new installs, access or substitutes attempted.'};return;}
  run.zoomVerified=true;await open(page,run,'genuine-200-percent');run.zoomDialog=await page.evaluate(()=>window.__supplementState());for(const name of ['Cancel','Delete'])assertControl(run.zoomDialog,name,'visible');await shot(page,run,'actual-200-percent-dialog');await close(page,run,'genuine-200-percent');
 });
}catch(error){report.fatalError=error.stack||String(error);process.exitCode=1;}finally{const finalized=await finalizeSupplementReport(report,async()=>{if(browser)await browser.close();});if(finalized.exitCode)process.exitCode=finalized.exitCode;save();}
console.log(JSON.stringify({captured:report.runs.filter(r=>r.status==='captured').length,blocked:report.runs.filter(r=>r.status==='blocked').map(r=>r.label),failed:report.runs.filter(r=>r.status==='failed').map(r=>r.label),scope:report.scope}));
if(report.runs.some(r=>r.status==='failed'))process.exitCode=1;
