// The synchronous native focus boundary can run a host handler that issues newer intent.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const input=path.resolve(process.argv[2]||path.join(__dirname,'../skills/seenry/assets/components/transitions/seenry-transitions.js')),source=fs.readFileSync(input,'utf8');
const fixtureSource=fs.readFileSync(path.join(__dirname,'transitions-library-reduced-expand-reopen.test.cjs'),'utf8');
const scope={require,__dirname,process:{argv:['node','test',input]},console};vm.runInNewContext(fixtureSource.slice(0,fixtureSource.indexOf('(async()=>{'))+'\nthis.createFixture=fixture;',scope);
function run(code,reopen){const f=scope.createFixture(code,true,false,false);f.env.context.DOMMatrix=class{constructor(){this.m42=0}};let handled=false;const focus=f.control.focus;f.control.focus=()=>{focus();if(handled)return;handled=true;f.S.collapse(f.detail);if(reopen)f.S.expand(f.source,f.detail);};f.S.expand(f.source,f.detail);const opacity=f.animations.filter(a=>a.owner===f.content&&a.frames.some(k=>'opacity'in k));return {open:f.detail.dataset.stOpen,closing:f.detail.dataset.stClosing,targets:Array.from(opacity,a=>Number(a.frames.at(-1).opacity)),activeTarget:opacity.filter(a=>!a.cancelled).at(-1)?.frames.at(-1).opacity};}
const guard='if (s.version !== v || !s.open) return; revealFocusedExpandClose(closeControl);';assert(source.includes(guard));const a=run(source,false),b=run(source,true);assert.equal(a.open,'false');assert.equal(a.closing,'true');assert.deepEqual(a.targets,[0]);assert.equal(b.open,'true');assert.deepEqual(b.targets,[0,1]);
const missing=source.replace(guard,'revealFocusedExpandClose(closeControl);'),badClose=run(missing,false),badReopen=run(missing,true);assert.deepEqual(badClose.targets,[0,1]);assert.deepEqual(badReopen.targets,[0,1,1]);
const redirected=scope.createFixture(source,true,false,false),external=new redirected.env.E('button');let acquired=0;redirected.control.matches=s=>s===':focus-visible'&&redirected.env.getActive()===redirected.control;redirected.control.focus=()=>{acquired++;redirected.env.setActive(redirected.control);redirected.control.dispatchEvent({type:'focus'});if(acquired===1)redirected.env.setActive(external);};redirected.S.expand(redirected.source,redirected.detail);assert.equal(acquired,1);assert.equal(redirected.env.getActive(),external,'A host focus redirect must remain owned by the host');assert.equal(redirected.detail.dataset.stOpen,'true');
console.log('5/5 synchronous Close-focus reentrancy/ownership checks pass; newer close/reopen and host focus redirect remain authoritative');
