// Execute the actual native-gate assertion against captured-paint models.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
(async()=>{const {cardReadableFindings}=await import('./transitions-library-card-readable.mjs'),source=fs.readFileSync(path.join(__dirname,'transitions-library-card-anchor-fallback.browser.mjs'),'utf8'),a=source.indexOf('const inside='),b=source.indexOf('const profiles=',a),scope={assert};vm.createContext(scope);scope.cardReadableFindings=row=>vm.runInContext(JSON.stringify(cardReadableFindings(row)),scope);assert(a>0&&b>a);vm.runInContext(source.slice(a,b)+'\nthis.readable=readable;',scope);
const rect={left:20,top:20,right:80,bottom:40,width:60,height:20},leaf=text=>({text,painted:true,visibility:'visible',display:'block',effectiveDisplay:true,opacity:1,colorAlpha:1,filter:'none',ancestorFilters:[{filter:'none'}],clipPath:'none',paintAncestors:[{clipPath:'none'}],glyphs:[rect]});
const row={open:'true',instant:true,sourceHidden:true,sourceGroupInert:true,focusedClose:true,blur:true,ghostCount:0,title:leaf('Night Swim'),paint:{painted:true,opacity:1,backgroundAlpha:1},close:{painted:true,opacity:1,ownsCenter:true,filter:'none',rect:{left:240,top:8,right:284,bottom:52}},shell:{left:0,top:0,right:300,bottom:300},viewport:{width:320,height:780},mode:null,animations:[],keyboardText:{cue:leaf('3-track preview'),tracks:[1,2,3].map(i=>({name:leaf('Track '+i),duration:leaf('3:12')}))}};
scope.readable(row,{title:'Night Swim'});let n=1;
for(const mutate of [x=>x.paint.backgroundAlpha=.83,x=>x.paint.opacity=.8,x=>x.paint.painted=false,x=>x.close.ownsCenter=false,x=>x.close.filter='blur(8px)',x=>x.close.opacity=0,x=>x.close.rect.right=350,x=>x.viewport.height=40,x=>x.sourceHidden=false,x=>x.sourceGroupInert=false,x=>x.focusedClose=false,x=>x.blur=false,x=>x.instant=false,x=>x.mode='css',x=>x.ghostCount=1,x=>x.title.text='Wrong album',x=>x.title.glyphs=[],x=>x.title.glyphs[0].right=400,x=>x.keyboardText.tracks[1].name.opacity=0,x=>x.animations.push({pseudo:null,properties:['clipPath']})]){const bad=structuredClone(row);mutate(bad);assert.throws(()=>scope.readable(bad,{title:'Night Swim'}));n++;}
const pinned=structuredClone(row);pinned.mode='css';Object.assign(pinned.close,{position:'fixed',positionVisibility:'always'});pinned.anchor={...pinned.close.rect};scope.readable(pinned,{title:'Night Swim',pinned:true});n++;
for(const mutate of [x=>x.close.position='absolute',x=>x.close.positionVisibility='anchors-visible',x=>x.anchor.top+=30,x=>x.mode=null]){const bad=structuredClone(pinned);mutate(bad);assert.throws(()=>scope.readable(bad,{title:'Night Swim',pinned:true}));n++;}
const hover=structuredClone(row);hover.animations.push({pseudo:'::before',properties:['opacity']});scope.readable(hover,{title:'Night Swim'});n++;
assert(source.includes("observedAt:'document-bubble',currentTargetIsDocument:event.currentTarget===document"));assert(source.includes("assert(run.closed.trusted&&run.closed.targetIsClose&&run.closed.currentTargetIsDocument)"));assert(source.includes("Object.values(run.nativeSupport).every(Boolean)"));assert(source.includes("assert.equal(run.scope,'all')"));
console.log(`${n}/${n} native fallback/relocation paint-gate controls pass; actual browser gate remains required`);
})().catch(e=>{console.error(e);process.exitCode=1});
