import NumberBlur from "./NumberBlur";
import React,{useState,useId,useRef} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {ArrowRight,Check,Plus,Link,Bookmark,Download,X} from 'lucide-react';
export const expressiveItems=[
 ['blur-words','Soft word reveal','Text','Words resolve from a soft blur in reading order.','Stagger words by 45ms, animate opacity 0→1, y 10→0 and blur 8→0px over 420ms. Replay cancels the previous word group. Reserve text height; expose one unfragmented accessible sentence.'],
 ['blur-digits','Blurred digit change','Text','Digits cross-blur with a short, staggered rise; units stay still.','Overlap incoming/outgoing glyphs in fixed tabular slots: ±8px travel, blur 2px, 500ms cubic-bezier(.34,1.45,.64,1), stagger 70ms. Two reusable layers per column; cancel and retarget rapid input, no exit-before-entry queue.'],
 ['blur-view','Focus transition','Navigation','Move between a collection and its detail through depth and blur.','Use one keyed layer at a time with wait presence. Outgoing scale 1→.97 and blur 0→5px in 140ms; incoming scale 1.035→1 and blur 5→0px in 260ms. Keep the control outside the animated layer and reserve the panel height.'],
 ['blur-status','Status cross-blur','Feedback','A status label changes without shifting its icon or frame.','Anchor the icon and 190px text slot. Cross-blur keyed labels with y ±8px and filter blur(5px) in 180ms, using wait mode to bound layers. Status is user-driven in the demo; bind real status in production.'],
 ['blur-image','Image focus reveal','Effects','A soft photograph resolves into its final crop.','Animate an already loaded image from scale 1.08 and blur 14px to scale 1 and blur 0px over 650ms with opacity .35→1. Clip to a fixed rounded frame; do not animate dimensions. Replay on demand, no infinite loop. Keep provenance and alt text.'],
 ['blur-actions','Expanding action cluster','Surfaces','Three actions emerge around a fixed trigger.','Use three staggered action buttons above a stationary plus control. Enter x/y from trigger to [-58,-66],[0,-94],[58,-66], scale .6→1, blur 6→0px in 260ms, stagger 35ms. Exit 140ms. Escape closes; closed actions cannot receive focus. Keep accessible names and touch/keyboard activation.'],
];
export default function ExpressiveMotion({id}){const [n,N]=useState(0);const [direction,D]=useState(1);const trigger=useRef();const [open,O]=useState(false);const reduced=useReducedMotion();const uid=useId();const blur=v=>`blur(${reduced?0:v}px)`;const t={duration:reduced?0:.32,ease:[.22,1,.36,1]};
if(id==='blur-words')return <div className="ex-words"><div aria-label="Every detail, considered." key={n}>{'Every detail, considered.'.split(' ').map((word,i)=><motion.span aria-hidden key={word} initial={{opacity:reduced?1:0,y:reduced?0:10,filter:blur(8)}} animate={{opacity:1,y:0,filter:blur(0)}} transition={{...t,duration:reduced?0:.42,delay:reduced?0:i*.045}}>{word} </motion.span>)}</div><button className="ml-action" onClick={()=>N(n+1)}>Replay reveal <ArrowRight size={14}/></button></div>;
if(id==='blur-digits'){const value=48+n;return <div className="ex-number"><div aria-hidden><NumberBlur value={value} direction={direction}/><small>saved</small></div><div className="ex-controls"><button aria-label="Decrease blurred count" disabled={n<=-48} onClick={()=>{D(-1);N(n-1)}}>−</button><button aria-label="Increase blurred count" disabled={n>=951} onClick={()=>{D(1);N(n+1)}}>+</button></div><button className="ex-carry" onClick={()=>{D(value===99?1:-1);N(value===99?52:51)}}>99 ↔ 100</button><span className="ml-sr" role="status">{value} saved</span></div>}
if(id==='blur-view')return <div className="ex-view"><div className="ex-view-window"><AnimatePresence mode="wait" initial={false}><motion.div key={String(open)} initial={{scale:reduced?1:1.035,opacity:0,filter:blur(5)}} animate={{scale:1,opacity:1,filter:blur(0)}} exit={{scale:reduced?1:.97,opacity:0,filter:blur(5)}} transition={t}>{open?<><div className="ex-swatch"/><strong>Material study</strong><p>Paper, ink and a quiet rhythm.</p></>:<><strong>Your collection</strong><div className="ex-mini"><i/><i/><i/></div><p>Three studies for your next project.</p></>}</motion.div></AnimatePresence></div><button className="ml-action" aria-expanded={open} onClick={()=>O(!open)}>{open?'← Back to collection':'Explore study →'}</button></div>;
if(id==='blur-status')return <div className="ex-status"><div role="status"><Check size={19}/><div><AnimatePresence mode="wait" initial={false}><motion.span key={n%3} initial={{y:reduced?0:8,opacity:0,filter:blur(5)}} animate={{y:0,opacity:1,filter:blur(0)}} exit={{y:reduced?0:-8,opacity:0,filter:blur(5)}} transition={{duration:reduced?0:.18}}>{['Draft ready','Review complete','Ready to publish'][n%3]}</motion.span></AnimatePresence></div></div><button className="ml-action" onClick={()=>N(n+1)}>Next status <ArrowRight size={14}/></button></div>;
if(id==='blur-image')return <div className="ex-photo"><div><motion.img key={n} src="https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?auto=format&fit=crop&w=500&q=80" alt="White architecture by Joel Filipe" initial={{scale:reduced?1:1.08,filter:blur(14),opacity:reduced?1:.35}} animate={{scale:1,filter:blur(0),opacity:1}} transition={{...t,duration:reduced?0:.65}}/></div><button onClick={()=>N(n+1)}>Refocus <ArrowRight size={14}/></button><a href="https://unsplash.com/photos/white-modern-cement-building-under-blue-sky-RFDP7_80v5A">Joel Filipe / Unsplash ↗</a></div>;
if(id==='blur-actions')return <div className="ex-actions" onKeyDown={e=>{if(e.key==='Escape'){O(false);trigger.current?.focus()}}}><AnimatePresence>{open&&[Bookmark,Link,Download].map((Icon,i)=><motion.button key={i} aria-label={['Save demo','Copy demo link','Prepare demo download'][i]} initial={{x:0,y:0,scale:.6,opacity:0,filter:blur(6)}} animate={{x:reduced?0:(i-1)*58,y:reduced?-(i+1)*46:[-66,-94,-66][i],scale:1,opacity:1,filter:blur(0)}} exit={{opacity:0,scale:reduced?1:.6,filter:blur(6)}} transition={{...t,duration:reduced?0:.26,delay:reduced?0:i*.035}} onClick={()=>{N(i+1);O(false);trigger.current?.focus()}}><Icon size={18}/></motion.button>)}</AnimatePresence><button ref={trigger} className="ex-trigger" aria-expanded={open} aria-label={open?'Close action cluster':'Open action cluster'} onClick={()=>O(!open)}><motion.span animate={{rotate:open?45:0}} transition={t}><Plus size={24}/></motion.span></button><span className="ex-action-status" role="status">{n?['Saved locally','Link selected (demo)','Download selected (demo)'][n-1]:''}</span></div>;
return null}
