import React, {useState,useRef,useEffect,useId} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {Copy,Check,Plus,ArrowRight,ChevronDown,Heart,LoaderCircle,X} from 'lucide-react';
import './motion-library.css';
import ExpressiveMotion,{expressiveItems} from './ExpressiveMotion';
const items=[
 ...expressiveItems,
 ['tabs','Sliding selection','Navigation','Move one shared pill between three choices without shifting the labels.','Use a shared layoutId for the active pill, spring stiffness 420 damping 34. Keep labels above it and aria-pressed on buttons.'],
 ['disclosure','Expanding details','Surfaces','Open and close a detail panel while its trigger stays in place.','Animate height from 0 to auto with opacity over 240ms. Rotate the chevron 180deg. Use aria-expanded and aria-controls; hide closed content from focus.'],
 ['menu','Anchored actions','Surfaces','A small action panel opens from its trigger.','Anchor an inline disclosure to the trigger bottom edge. Enter y -6 to 0, scale .96 to 1 and opacity over 180ms. Exit in 120ms. Escape closes and returns focus. Use ordinary focusable action buttons.'],
 ['switch','Switch response','Controls','The thumb follows the setting.','Use a role=switch button with aria-checked. Animate thumb x 0 to 28 with spring stiffness 500 damping 32. Keep its 60 by 32 track stable.'],
 ['like','Save a favorite','Controls','A pressed heart responds without moving the hit area.','Use aria-pressed. Animate the heart scale 1 to 1.22 to 1 in 220ms and fill on selection. Keep the button at least 44px.'],
 ['label','Action label swap','Feedback','A fixed-width action acknowledges a completed local change.','Crossfade keyed labels with y 6 to 0 to -6 in 160ms. Keep width fixed, announce completion through a polite status. Never claim a server operation succeeded before it does.'],
 ['toast','Bounded notifications','Feedback','New notices stack inside a fixed stage.','Keep at most 3 notifications with unique IDs. Use layout springs and 180ms opacity/y transitions. New input replaces the oldest. Include dismiss controls and keep the page geometry stable.'],
 ['progress','Progress to done','Feedback','A process reaches completion before showing its check.','Demo only: advance progress on user action, clamp 0–100; animate scaleX with left transform origin over 300ms. At 100 show a check. In production bind to real operation progress, not an arbitrary timer.'],
 ['reveal','Staggered reading','Text','Three lines enter in reading order.','On Replay, reveal 3 lines from y 12 to 0 and opacity 0 to 1; 320ms duration, 65ms stagger. Keep the text in accessible reading order and reserve its space.'],
 ['stack','Fanned cards','Effects','Hover, focus or tap to inspect a stack.','Keep a stable 180 by 120 stage. Animate 3 cards to x -35,0,35 and rotate -12,0,12 using spring stiffness 280 damping 24. Support focus and click as well as hover.'],
 ['pages','Directional navigation','Navigation','Move forward into details and back to the list.','Use keyed panels with direction-aware x offsets ±24 and opacity over 220ms. Reserve 210px of height, use a Back button and move focus to the newly displayed action after keyboard navigation.'],
 ['resize','Card expansion','Surfaces','Reveal more content without snapping the surface.','Use layout animation on the card and AnimatePresence for details. Spring stiffness 320 damping 30. Keep the outer demo stage fixed; use aria-expanded on its button.'],
];
function Demo({id}){const [n,S]=useState(0);const [open,O]=useState(false);const [toasts,T]=useState([]);const uid=useId();const serial=useRef(0);const reduce=useReducedMotion();const t={duration:reduce?0:.22};const trigger=useRef();const pageAction=useRef();const pageUsed=useRef(false);
 if(id.startsWith('blur-'))return <ExpressiveMotion id={id}/>;
 if(id==='tabs')return <div className="ml-tabs">{['Design','Build','Review'].map((v,i)=><button key={v} aria-pressed={n===i} onClick={()=>S(i)}>{n===i&&<motion.span layoutId={uid} transition={{type:'spring',stiffness:420,damping:34}}/>}<b>{v}</b></button>)}</div>;
 if(id==='switch')return <button className={'ml-switch '+(open?'on':'')} role="switch" aria-label="Enable notifications" aria-checked={open} onClick={()=>O(!open)}><motion.span animate={{x:open?28:0}} transition={reduce?{duration:0}:{type:'spring',stiffness:500,damping:32}}/></button>;
 if(id==='like')return <button className="ml-heart" aria-label="Favorite" aria-pressed={open} onClick={()=>O(!open)}><motion.span key={String(open)} animate={{scale:reduce?1:[1,1.22,1]}} transition={{duration:.22}}><Heart fill={open?'currentColor':'none'}/></motion.span></button>;
 if(id==='disclosure'||id==='resize')return <motion.div layout className="ml-detail"><button aria-expanded={open} aria-controls={uid} onClick={()=>O(!open)}>Project details <motion.span animate={{rotate:open?180:0}} transition={t}><ChevronDown size={17}/></motion.span></button><AnimatePresence initial={false}>{open&&<motion.div id={uid} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={t}><p>One shared system for type, spacing and motion.</p></motion.div>}</AnimatePresence></motion.div>;
 if(id==='menu')return <div className="ml-menu" onKeyDown={e=>{if(e.key==='Escape'){O(false);trigger.current?.focus()}}}><button ref={trigger} className="ml-action" aria-expanded={open} aria-controls={uid} onClick={()=>O(!open)}>Actions <Plus size={16}/></button><AnimatePresence>{open&&<motion.div id={uid} className="ml-pop" initial={{y:-6,scale:.96,opacity:0}} animate={{y:0,scale:1,opacity:1}} exit={{y:-6,scale:.96,opacity:0}} transition={t}>{['Save','Duplicate','Archive'].map(v=><button key={v} onClick={()=>{O(false);trigger.current?.focus();S(n+1)}}>{v}</button>)}</motion.div>}</AnimatePresence><span className="ml-sr" role="status">{n? 'Demo action completed':''}</span></div>;
 if(id==='label')return <button className="ml-action ml-fixed" onClick={()=>O(!open)}><AnimatePresence mode="wait" initial={false}><motion.span key={String(open)} initial={{y:6,opacity:0}} animate={{y:0,opacity:1}} exit={{y:-6,opacity:0}} transition={{duration:reduce?0:.16}}>{open?<><Check size={16}/> Saved</>:<><Plus size={16}/> Save</>}</motion.span></AnimatePresence><span className="ml-sr" role="status">{open?'Saved locally':''}</span></button>;
 if(id==='toast')return <><div className="ml-toast-area" aria-live="polite"><AnimatePresence initial={false}>{toasts.map(i=><motion.div layout key={i} initial={{y:14,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0,scale:.95}} transition={t}><Check size={14}/> Saved {i}<button aria-label={'Dismiss notification '+i} onClick={()=>T(toasts.filter(x=>x!==i))}><X size={13}/></button></motion.div>)}</AnimatePresence></div><button className="ml-action ml-bottom" onClick={()=>T(a=>[...a,++serial.current].slice(-3))}>Show notification</button></>;
 if(id==='progress')return <div className="ml-progress"><div role="progressbar" aria-label="Demo progress" aria-valuenow={n} aria-valuemin={0} aria-valuemax={100}><motion.span animate={{scaleX:n/100}} transition={t}/></div><button className="ml-action" onClick={()=>S(n===100?0:Math.min(100,n+25))}>{n===100?<><Check size={16}/> Reset</>:<>Advance {n}%</>}</button></div>;
 if(id==='reveal')return <div className="ml-reveal"><div key={n}>{['Choose a reference.','Study the details.','Build with intent.'].map((v,i)=><motion.p key={v} initial={{y:reduce?0:12,opacity:reduce?1:0}} animate={{y:0,opacity:1}} transition={{duration:.32,delay:reduce?0:i*.065}}>{v}</motion.p>)}</div><button onClick={()=>S(n+1)}>Replay <ArrowRight size={15}/></button></div>;
 if(id==='stack')return <button className="ml-stack" aria-label="Fan cards" aria-pressed={open} onMouseEnter={()=>O(true)} onMouseLeave={()=>O(false)} onFocus={()=>O(true)} onBlur={()=>O(false)} onClick={()=>O(!open)}>{[0,1,2].map(i=><motion.span key={i} animate={{x:open?(i-1)*35:(i-1)*7,rotate:open?(i-1)*12:(i-1)*3,y:open?Math.abs(i-1)*8:0}} transition={reduce?{duration:0}:{type:'spring',stiffness:280,damping:24}}>{['Aa','Bb','Cc'][i]}</motion.span>)}</button>;
 if(id==='pages')return <div className="ml-pages"><AnimatePresence mode="wait" initial={false}><motion.div key={String(open)} initial={{x:reduce?0:open?24:-24,opacity:0}} animate={{x:0,opacity:1}} exit={{x:reduce?0:open?24:-24,opacity:0}} transition={t} onAnimationComplete={()=>{if(pageUsed.current)pageAction.current?.focus()}}><h4>{open?'Project details':'Your projects'}</h4><p>{open?'A shared identity, from first screen to last.':'Open a project to inspect its details.'}</p><button ref={pageAction} className="ml-action" onClick={()=>{pageUsed.current=true;O(!open)}}>{open?'← Back':'Open project →'}</button></motion.div></AnimatePresence></div>;
}
export default function MotionLibrary(){const [category,C]=useState('All');const [query,Q]=useState('');const [copied,K]=useState('');const [fallback,F]=useState('');const timer=useRef();useEffect(()=>()=>clearTimeout(timer.current),[]);const visible=items.filter(x=>(category==='All'||x[2]===category)&&(x[0]+' '+x[1]+' '+x[3]).toLowerCase().includes(query.toLowerCase()));async function copy(item){const text=`Use Seenry Motion to implement ${item[1].toLowerCase()} in this project. Read the existing DESIGN.md / BRAND.md first and preserve its tokens, components and stack.\n\nBehavior: ${item[3]}\nImplementation: ${item[4]}\n\nUse the current project's animation library, or CSS/Web Animations when sufficient. Keep state authoritative and animations cancellable under rapid input. Respect live prefers-reduced-motion. Preserve visible focus, keyboard activation, touch targets and useful accessible names. Do not add unrelated effects. Test initial, active, exit, rapid reversal and narrow-screen states.\n\nWorking example and source: https://skill.seenry.design/#motion-library\nhttps://github.com/ayangabryl/seenry-skills/blob/main/site/src/MotionLibrary.jsx\nExpressive examples: https://github.com/ayangabryl/seenry-skills/blob/main/site/src/ExpressiveMotion.jsx\nInstall Seenry if absent: npx skills add ayangabryl/seenry-skills`;try{await navigator.clipboard.writeText(text);K(item[0]);clearTimeout(timer.current);timer.current=setTimeout(()=>K(''),1800)}catch{F(text)}}return <div className="ml-library" id="motion-library"><div className="ml-search"><input aria-label="Search motion examples" placeholder="Find a transition…" value={query} onChange={e=>Q(e.target.value)}/><span>{visible.length} examples</span></div><div className="ml-filters" role="group" aria-label="Motion categories">{['All','Surfaces','Navigation','Controls','Feedback','Text','Effects'].map(x=><button key={x} aria-pressed={category===x} onClick={()=>C(x)}>{x}</button>)}</div><div className="ml-grid">{visible.map(item=><article key={item[0]}><div className="ml-stage"><Demo id={item[0]}/></div><div className="ml-card-foot"><h3>{item[1]}</h3><button aria-label={'Copy prompt for '+item[1]} onClick={()=>copy(item)}>{copied===item[0]?<Check size={15}/>:<Copy size={15}/>} {copied===item[0]?'Copied':'Copy prompt'}</button></div><p>{item[3]}</p></article>)}</div>{!visible.length&&<p>No matching examples. <button onClick={()=>{Q('');C('All')}}>Reset filters</button></p>}<span className="ml-sr" role="status">{copied?'Prompt copied':''}</span>{fallback&&<label>Copy this prompt<textarea readOnly value={fallback} onFocus={e=>e.target.select()}/></label>}<p className="r-footnote">18 original interactive recipes. Copy a prompt to adapt one to your project. <a href="https://github.com/ayangabryl/seenry-skills/blob/main/site/src/MotionLibrary.jsx">View source ↗</a></p></div>}
