'use strict';
const $=s=>document.querySelector(s);
const reduceMotion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const ease='cubic-bezier(.22,.8,.24,1)';
const objectDialog=$('#object-dialog'), inquiryDialog=$('#inquiry-dialog');
let lastTrigger=null, currentObject='chair';
let inquiryMorph=null;
function morphInquiry(render){const start=inquiryDialog.getBoundingClientRect().height;if(inquiryMorph)inquiryMorph.cancel();render();const end=inquiryDialog.getBoundingClientRect().height;if(inquiryDialog.open&&!reduceMotion()&&Math.abs(end-start)>1){inquiryMorph=inquiryDialog.animate({height:[start+'px',end+'px']},{duration:320,easing:ease});inquiryMorph.onfinish=()=>{inquiryMorph.cancel();inquiryMorph=null;};}}
function moveIn(el,dy=10){el.getAnimations().forEach(a=>a.cancel());if(!reduceMotion())el.animate([{opacity:0,transform:`translateY(${dy}px)`},{opacity:1,transform:'translateY(0)'}],{duration:330,easing:ease});}
function openDialog(dialog,trigger){lastTrigger=trigger||document.activeElement;const gutter=window.innerWidth-document.documentElement.clientWidth;document.body.style.paddingRight=`${gutter}px`;document.body.style.overflow='hidden';dialog.showModal();moveIn(dialog,12);dialog.scrollTop=0;}
function closeDialog(dialog){dialog.getAnimations().forEach(a=>a.cancel());dialog.close();document.body.style.overflow='';document.body.style.paddingRight='';if(lastTrigger?.isConnected)lastTrigger.focus({preventScroll:true});}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...dialog.querySelectorAll('button,input,textarea,a[href]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}});dialog.querySelector('[data-close]').addEventListener('click',()=>closeDialog(dialog));dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(dialog)});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog)}});});
const studies={chair:{title:'The spindle chair',image:'assets/chair.png',alt:'Elm and oak spindle chair with a gently aged leather seat',description:'The shaped arm, the softened edge, the grain made visible by years of use. These are the details a careful repair can leave intact.',facts:[['Look closely','The arm-to-spindle connection and the shaped seat.'],['A possible approach','Assess the joints, retain the patina and discuss the seat.']],piece:'Chair'},table:{title:'The walnut table',image:'assets/workbench.png',alt:'Walnut table drawer and dovetail joint on a workbench',description:'A drawer should move freely. A surface can show its age. The aim is to make the piece useful without asking it to look newly made.',facts:[['Look closely','The drawer corner and the worn edge of the top.'],['A possible approach','Assess the drawer fit and test a sympathetic surface treatment.']],piece:'Table'}};
document.querySelectorAll('[data-object]').forEach(button=>button.addEventListener('click',()=>{currentObject=button.dataset.object;const item=studies[currentObject];$('#object-title').textContent=item.title;$('#detail-image').src=item.image;$('#detail-image').alt=item.alt;$('#object-description').textContent=item.description;$('#object-facts').replaceChildren(...item.facts.map(([name,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;row.append(dt,dd);return row}));setView('whole');openDialog(objectDialog,button)}));
function setView(view){$('.object-view').dataset.detail=String(view==='detail');document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===view)));}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
document.querySelectorAll('[data-inquiry]').forEach(button=>button.addEventListener('click',()=>openDialog(inquiryDialog,button)));
$('#similar-piece').addEventListener('click',()=>{const trigger=lastTrigger;closeDialog(objectDialog);document.querySelector(`input[name="piece"][value="${studies[currentObject].piece}"]`).checked=true;showForm();openDialog(inquiryDialog,trigger)});
// Animate disclosure height from the current frame so repeated input can reverse it.
document.querySelectorAll('.care-choices details').forEach(details=>{const summary=details.querySelector('summary');let animation=null;let desired=details.open;summary.addEventListener('click',event=>{if(reduceMotion()){desired=!details.open;return;}event.preventDefault();desired=!desired;const start=details.getBoundingClientRect().height;if(animation)animation.cancel();details.open=true;const end=desired?details.scrollHeight:summary.getBoundingClientRect().height;details.style.overflow='hidden';animation=details.animate({height:[start+'px',end+'px']},{duration:300,easing:ease});animation.onfinish=()=>{details.open=desired;details.style.overflow='';animation=null;};});});
const form=$('#inquiry-form');let brief=null;
const rules={story:el=>el.value.trim().length>=8?'':'Tell us a little more about what needs care.',name:el=>el.value.trim()?'':'Please add your name.',email:el=>el.value.trim()&&el.validity.valid?'':'Please enter a valid email address.'};
function validate(id){const el=$('#'+id),message=rules[id](el);$('#'+id+'-error').textContent=message;el.setAttribute('aria-invalid',String(!!message));return !message;}
Object.keys(rules).forEach(id=>$('#'+id).addEventListener('input',()=>{if($('#'+id).getAttribute('aria-invalid')==='true')validate(id)}));
form.addEventListener('submit',event=>{event.preventDefault();const invalid=Object.keys(rules).filter(id=>!validate(id));if(invalid.length){$('#'+invalid[0]).focus();return;}const data=new FormData(form);brief={piece:data.get('piece'),story:data.get('story').trim(),name:data.get('name').trim(),email:data.get('email').trim()};$('#review-piece').textContent=brief.piece;$('#review-story').textContent=brief.story;$('#review-contact').textContent=brief.name+'\n'+brief.email;morphInquiry(()=>{$('#form-view').hidden=true;$('#review-view').hidden=false;$('#inquiry-title').textContent='Your project brief.';});$('.download-status').textContent='';$('#download-brief span').textContent='Download brief';$('#download-brief use').setAttribute('href','#arrow');moveIn($('#review-view'),8);$('#edit-brief').focus({preventScroll:true});inquiryDialog.scrollTop=0;});
function showForm(){morphInquiry(()=>{$('#review-view').hidden=true;$('#form-view').hidden=false;$('#inquiry-title').replaceChildren(document.createTextNode('What would you'),document.createElement('br'),document.createTextNode('like to keep?'));});moveIn($('#form-view'),6);}
$('#edit-brief').addEventListener('click',()=>{showForm();$('#story').focus({preventScroll:true});});
$('#download-brief').addEventListener('click',()=>{if(!brief)return;const text=`Held project brief\n\nPiece: ${brief.piece}\n\nWhat needs care\n${brief.story}\n\nContact\n${brief.name}\n${brief.email}\n\nPrepared locally. This brief has not been sent.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='held-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#download-brief span').textContent='Download again';$('#download-brief use').setAttribute('href','#check');moveIn($('#download-brief svg'),3);$('.download-status').textContent='Your text file has been prepared. Check your downloads.';});
