import React,{useEffect,useState} from 'react';
import './dev-layout-grid.css';
// Mount only in development. Override selectors for the host project.
export default function DevLayoutGrid({selectors="[data-layout-region]"}){
 const [enabled,S]=useState(true),[boxes,B]=useState([]),[hover,H]=useState(null),[checks,C]=useState(false);
 useEffect(()=>{const key=e=>{if(e.target.closest?.('input,textarea,[contenteditable=true]'))return;if(e.altKey&&e.key.toLowerCase()==='c'){e.preventDefault();C(v=>!v)}if(e.altKey&&e.key.toLowerCase()==='g'){e.preventDefault();S(v=>!v)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!enabled)return;let frame;const read=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{B([...document.querySelectorAll(selectors)].map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return {name:el.classList[0],x:r.x+parseFloat(s.paddingLeft),y:r.y,width:r.width-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),height:r.height}}))})};const move=e=>{if(e.target.closest('[data-layout-tools]'))return;const el=e.target.closest('button,a,img,section,input,[role="tablist"]');if(!el)return H(null);const r=el.getBoundingClientRect(),s=getComputedStyle(el);H({x:r.x,y:r.y,width:r.width,height:r.height,radius:s.borderRadius,padding:s.padding,gap:s.gap,pt:parseFloat(s.paddingTop)||0,pr:parseFloat(s.paddingRight)||0,pb:parseFloat(s.paddingBottom)||0,pl:parseFloat(s.paddingLeft)||0,name:el.tagName.toLowerCase()})};read();window.addEventListener('resize',read);window.addEventListener('scroll',read,{passive:true});window.addEventListener('pointermove',move);const observer=new ResizeObserver(read);observer.observe(document.body);return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('resize',read);window.removeEventListener('scroll',read);window.removeEventListener('pointermove',move)}},[enabled,selectors]);
 return <><button data-layout-tools className="layout-check-toggle" onClick={()=>C(v=>!v)} aria-pressed={checks}>8px checks {checks?'on':'off'} · Alt C</button><button data-layout-tools className="layout-grid-toggle" onClick={()=>S(v=>!v)} aria-pressed={enabled}>Grid {enabled?'on':'off'} · Alt G</button>{enabled&&<div className="layout-grid-overlay" aria-hidden="true">{checks&&<div className="layout-grid-checks"/>}<div className="layout-grid-columns">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><div className="layout-grid-ruler"/>{boxes.map(b=><div className="layout-grid-box" key={b.name+":"+b.y} style={{left:b.x,top:b.y,width:b.width,height:b.height}}><span>{b.name} · {Math.round(b.width)}px</span></div>)}{hover&&<div className="layout-grid-hover" style={{left:hover.x,top:hover.y,width:hover.width,height:hover.height}}><span>{hover.name} · {Math.round(hover.width)} × {Math.round(hover.height)} · r {hover.radius} · padding {hover.padding} · gap {hover.gap}</span><i className="layout-content-edge" style={{inset:`${hover.pt}px ${hover.pr}px ${hover.pb}px ${hover.pl}px`}}/></div>}</div>}</>;
}
